- .github/workflows/main.yaml
Enables github actions for simple CI
Adding CI to project
Builds UCC executing ./autogen; configure; make sequence
> TEST: use github actions

- .clang-format
- docs/codestyle.md
Use clang-format for code style check
`clang-format -style=file *.c`
**Exhaustive list of options and description:** 
https://clang.llvm.org/docs/ClangFormatStyleOptions.html
> Use clang-format for code style check

- src/Makefile.am
- src/api/ucc.h
- src/api/ucc_status.h
- src/core/ucc_constructor.c
- src/core/ucc_global_opts.h
- src/utils/ucc_component.c
- src/utils/ucc_component.h
- src/utils/ucc_malloc.h
**What?**
Adds a framework to dynamically load .so components.
**Why?**
Currently it is used to load CL components. Will also be used for TL components and possibly others.
> UCC/UTIL: Components framework

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/codestyle.yaml
Add github pull request template and commits title check similar to UCX
Make automatic commits check
> UCC: pr template and check commit title

- .github/workflows/codestyle.yaml
Adds clang-format check for each pull request
Check code style automatically
Run clang-format only for changes introduced in pull request. If clang-formats finds any format issues it prints patch that can be used to fix it
> TEST: run clang-format in CI

- .github/workflows/codestyle.yaml
Add BUILD and CL/BASIC as allowed commit prefixes
> TOOLS: Commit title check: extend pattern

- src/api/ucc.h
Fixes the support of custom user reduction in the UCC/API
UCC v1.0 is supposed to support custom user reduction (over pre-defined ucc datatype)
- The reduction wrapper callback signature is fixed: now it takes ucc_datatype_t and "void* op" as well. op_t can store user defined context that defines the custom op. E.g. in the case of integration into ompi it will store ompi_op_t *.
- The custom reduction op is stored on the coll_args as void*
```
typedef void(*ucc_reduction_wrapper_t)(void *invec, void *inoutvec,
ucc_count_t *count, ucc_datatype_t dtype,  void *op) {
ompi_op_t *op = (ompi_op_t*)(op);
ompi_datatype_t dt = ucc_dt_to_ompi_dt(dtype); // for pre-defined types - fixed translation table
ompi_dt_reduce(invec, inoutvec, count, dt, op); //actual invocation for a callback
} …
```
> API: dtype/op/reduce changes

- src/core/ucc_constructor.c
Constructor bugfix: all code should be under singleton check
> CORE: constructor bugfix

- docs/doxygen/ucc_doxygen.conf
Fix doxygen build that is not handled by PR #44
> BUILD: Fix doxygen build not handled by PR #44

- .github/workflows/codestyle.yaml
- src/Makefile.am
- src/components/base/ucc_base_iface.h
- src/components/cl/basic/Makefile.am
- src/components/cl/basic/cl_basic.c
- src/components/cl/basic/cl_basic.h
- src/components/cl/basic/cl_basic_team.c
- src/components/cl/ucc_cl.c
- src/components/cl/ucc_cl.h
- src/components/tl/ucc_tl.c
- src/components/tl/ucc_tl.h
- src/components/tl/ucp/Makefile.am
- src/components/tl/ucp/tl_ucp.c
- src/components/tl/ucp/tl_ucp.h
- src/components/tl/ucp/tl_ucp_addr.c
- src/components/tl/ucp/tl_ucp_addr.h
- src/components/tl/ucp/tl_ucp_context.c
- src/components/tl/ucp/tl_ucp_ep.c
- src/components/tl/ucp/tl_ucp_ep.h
- src/components/tl/ucp/tl_ucp_team.c
- src/core/ucc_team.c
- src/core/ucc_team.h
- src/ucc/api/ucc.h
- test/gtest/Makefile.am
- test/gtest/core/test_multiproc.cc
- test/gtest/core/test_multiproc.h
Adds base team_create_post/test/destroy interface; cl and tl implementation; TL UCP non blocking team post/test implementation; gtest multiprocess env simulation + team_create_destroy test
> Team create

- config/m4/cuda.m4
- configure.ac
- src/Makefile.am
- src/components/mc/cuda/Makefile.am
- src/components/mc/cuda/mc_cuda.c
- src/components/mc/cuda/mc_cuda.h
- src/core/ucc_mc.c
- src/core/ucc_mc.h
- test/gtest/Makefile.am
- test/gtest/core/test_mc.cc
- test/gtest/core/test_mc_cuda.cc
Adding cuda memory component
Dynamically loadable component that implements base mc interface
> CORE: cuda memory component

- src/Makefile.am
- src/core/ucc_constructor.c
- src/ucc/api/ucc_def.h
- src/ucc/api/ucc_status.h
- src/utils/ucc_status.c
Adding ucc_status_string function
> CORE: ucc status string implementation

- src/core/ucc_lib.c
> CORE: fix tl lib finalize

- src/Makefile.am
- src/components/cl/ucc_cl.c
- src/components/tl/ucp/Makefile.am
- src/components/tl/ucp/allgather/allgather_ring.c
- src/components/tl/ucp/allgatherv/allgatherv.c
- src/components/tl/ucp/allgatherv/allgatherv.h
- src/components/tl/ucp/allgatherv/allgatherv_ring.c
- src/components/tl/ucp/allreduce/allreduce.c
- src/components/tl/ucp/allreduce/allreduce_knomial.c
- src/components/tl/ucp/alltoallv/alltoallv_pairwise.c
- src/components/tl/ucp/tl_ucp_coll.c
- src/components/tl/ucp/tl_ucp_coll.h
- src/core/ucc_coll.c
- src/schedule/ucc_schedule.h
- src/utils/ucc_coll_utils.h
- src/utils/ucc_log.h
- src/utils/ucc_math.h
- test/mpi/Makefile.am
- test/mpi/main.cc
- test/mpi/test_allgatherv.cc
- test/mpi/test_case.cc
- test/mpi/test_mpi.cc
- test/mpi/test_mpi.h
Adding ring allgatherv and data correctness check for it
> TL/UCP: allgatherv ring

- src/components/mc/cuda/kernel/mc_cuda_reduce.cu
Fix bug in cuda reduce, number of threads and number of blocks were messed up
> MC/CUDA: fix reduce num blocks

- test/gtest/common/test_helpers.h
- test/gtest/core/test_alltoall.cc
- test/gtest/core/test_alltoallv.cc
Put correct headers path when build is made outside src tree
> TEST: fixes gtest build

- src/components/tl/ucp/allgather/allgather_ring.c
- src/components/tl/ucp/allgatherv/allgatherv_ring.c
- src/components/tl/ucp/allreduce/allreduce_knomial.c
- src/components/tl/ucp/alltoall/alltoall_pairwise.c
- src/components/tl/ucp/alltoallv/alltoallv_pairwise.c
- src/components/tl/ucp/barrier/barrier_knomial.c
- src/components/tl/ucp/bcast/bcast_knomial.c
- src/components/tl/ucp/tl_ucp_sendrecv.h
- src/components/tl/ucp/tl_ucp_team.c
Checks return status of tl_ucp_send/recv_nb functions.
Error may happen (e.g. truncate or failure during on-demand ep connection)
Check status, set task->super.super.status, and return
> TL/UCP: check status of ucp_send/recv

- src/utils/ucc_log.h
- test/mpi/Makefile.am
- test/mpi/buffer.cc
- test/mpi/main.cc
- test/mpi/test_allgather.cc
- test/mpi/test_allgatherv.cc
- test/mpi/test_allreduce.cc
- test/mpi/test_alltoall.cc
- test/mpi/test_alltoallv.cc
- test/mpi/test_bcast.cc
- test/mpi/test_case.cc
- test/mpi/test_mpi.cc
- test/mpi/test_mpi.h
> TEST: added mpi alltoall[v] test

- src/components/mc/cuda/kernel/mc_cuda_reduce.cu
- test/gtest/Makefile.am
- test/gtest/core/test_mc_reduce.cc
- test/gtest/core/test_mc_reduce.h
- test/gtest/core/test_mc_reduce_cuda.cc
- test/gtest/core/test_mc_reduce_host.cc
> TEST: test reduction operations

- src/components/cl/basic/cl_basic_coll.c
- src/components/tl/nccl/tl_nccl_coll.c
- src/components/tl/nccl/tl_nccl_coll.h
- src/components/tl/nccl/tl_nccl_team.c
Adding allgather, allgatherv, allreduce and broadcast for nccl tl
> TL/NCCL: add more collectives

- test/mpi/buffer.cc
- test/mpi/test_alltoall.cc
- test/mpi/test_alltoallv.cc
- test/mpi/test_mpi.cc
Fixes:
- alltoall `inplace` support checking
- alltoallv mem limit checking
- compilation issues
> TEST: mpi: misc fixes

- src/components/tl/nccl/tl_nccl_lib.c
Fix variable name bug
Compilation is Failing
Change variable name
> TL/NCCL: Fix Compilation Bug

- src/components/mc/cuda/kernel/Makefile.am
- src/components/mc/cuda/kernel/mc_cuda_wait_kernel.cu
- src/components/mc/cuda/mc_cuda.c
- src/components/mc/cuda/mc_cuda.h
Adding stream task mode kernel
Fallback to kernel mode if driver mode is not available
Start wait kernel on cuda stream
> MC/CUDA: stream task kernel

- src/core/ucc_lib.c
Implementation of ucc_lib_get_attr function
> CORE: get lib attr implementation

- src/utils/ucc_mpool.c
Init thread mode properly based on input
> UTIL: mpool thread mode fix

- src/ucc/api/ucc.h
> API: Changing team destroy semantics from blocking to nonblocking

- README.md
> DOCS: Updates to README

- test/gtest/core/test_alltoall.cc
> TEST: fix gtest alltoall

- test/mpi/test_mpi.cc
> V0.1.x: TEST: test mpi oob.participants

- src/components/mc/cuda/kernel/mc_cuda_reduce.cu
- src/components/mc/cuda/kernel/mc_cuda_reduce_multi.cu
- test/mpi/main.cc
- test/mpi/test_mpi.cc
- test/mpi/test_mpi.h
> TEST: mpi: added set CUDA device

- src/coll_score/ucc_coll_score.c
- src/components/cl/basic/cl_basic_team.c
- src/components/mc/cpu/mc_cpu.c
- src/components/tl/ucp/tl_ucp_coll.c
- src/components/tl/ucp/tl_ucp_context.c
- src/components/tl/ucp/tl_ucp_ep.c
- src/core/ucc_ee.c
- src/core/ucc_progress_queue_mt.c
- src/schedule/ucc_schedule.c
Actual issues are fixed, unused vars are suppressed with NOLINT
> Fix linter warnings

- src/components/tl/nccl/tl_nccl_coll.c
Use proper offset into rbuf. Fixes corr failure in ucc_test_mpi (cuda, nccl, inplace).
> TL/NCCL: allgather INPLACE fix

- src/components/tl/nccl/tl_nccl_coll.c
> V0.1.x: TL/NCCL: allgather INPLACE fix

- .ci/Dockerfile.centos8
- .ci/Jenkinsfile.shlib
- .ci/configs/swx-clx01/hostfile.txt
- .ci/configs/swx-clx02/hostfile.txt
- .ci/job_matrix.yaml
- .ci/patches/dlrm/0001-Added-torch_ucc-support.patch
- .ci/patches/dlrm/0002-Fixed-arg-list.patch
- .ci/proj_jjb.yaml
- .ci/scripts/build_ucc.sh
- .ci/scripts/build_ucx.sh
- .ci/scripts/configure_python.sh
- .ci/scripts/env.sh
- .ci/scripts/install_torch.sh
- .ci/scripts/install_torch_ucc.sh
- .ci/scripts/run_dlrm.sh
- .ci/scripts/run_dlrm_docker.sh
- .ci/scripts/run_dlrm_s_pytorch.sh
- .ci/scripts/run_docker.sh
- .ci/scripts/run_tests_torch_ucc.sh
- .ci/scripts/run_tests_ucc.sh
- .ci/scripts/run_tests_ucc_mpi.sh
- .ci/scripts/run_tests_ucc_mpi_docker.sh
- .ci/scripts/stop_docker.sh
- .gitignore
Enabled extended CI with UCC unit tests, Torch-UCC and DLRM tests.
Improve UCC quality with increased test coverage.
> Enabled extended CI

- src/components/tl/ucp/alltoall/alltoall.c
- src/core/ucc_coll.c
> V0.1.x CORE: dbg log level for "unsupported"

- src/components/mc/cpu/mc_cpu.c
- src/components/mc/cuda/mc_cuda.c
> V0.1.x MC/CUDA: check device count

- src/components/cl/basic/cl_basic_lib.c
- src/components/tl/nccl/tl_nccl_lib.c
- src/components/tl/ucp/tl_ucp_lib.c
> V0.1.x CL/BASIC: fill coll_types attribute

- src/components/tl/ucp/allgather/allgather_ring.c
- src/components/tl/ucp/allgatherv/allgatherv_ring.c
- src/components/tl/ucp/allreduce/allreduce_knomial.c
- src/components/tl/ucp/alltoall/alltoall_pairwise.c
- src/components/tl/ucp/alltoallv/alltoallv_pairwise.c
- src/components/tl/ucp/barrier/barrier_knomial.c
- src/components/tl/ucp/bcast/bcast_knomial.c
- src/core/ucc_coll.c
- src/core/ucc_progress_queue_mt.c
- src/core/ucc_progress_queue_st.c
- src/schedule/ucc_schedule.h
- src/ucc/api/ucc.h
- src/ucc/api/ucc_def.h
- test/gtest/core/test_barrier.cc
> V0.1.x API: completion callback

- src/coll_score/ucc_coll_score.c
- src/core/ucc_lib.c
- src/core/ucc_team.c
- test/gtest/coll_score/test_score.cc
- test/gtest/coll_score/test_score_str.cc
- test/mpi/test_barrier.cc
Fixing memory leaks in different places found by address sanitizer
> CORE: fix memory leaks

- src/components/mc/base/ucc_mc_base.h
- src/components/mc/cpu/mc_cpu.c
- src/components/mc/cuda/mc_cuda.c
- src/core/ucc_mc.c
Return error if user tries to post execution engine task but corresponding memory component is not available
> EE: check ee available

- test/gtest/common/test_ucc.cc
fixes #185 
Output after fix:
```
[----------] 5 tests from test_team, where TypeParam =
[ RUN      ] test_team.team_create_multiple <> <>
[       OK ] test_team.team_create_multiple (3564 ms)
[ RUN      ] test_team.team_create_multiple_preconnect <> <>
[1620909051.934456] [jazz32:87543:0]            sock.c:139  UCX  ERROR socket create failed: Too many open files
[1620909051.934474] [jazz32:87543:0]            sock.c:139  UCX  ERROR socket create failed: Too many open files
[1620909051.934480] [jazz32:87543:0]            sock.c:139  UCX  ERROR socket create failed: Too many open files
[1620909051.935207] [jazz32:87543:0]  tl_ucp_context.c:88   TL_UCP ERROR failed to create ucp worker, Input/output error
[1620909051.938220] [jazz32:87543:0]     ucc_context.c:293  UCC  WARN  failed to …
```
> TEST: return error from UCCProcess constructor

- .ci/Dockerfile.centos8
- .ci/Jenkinsfile.shlib
- .ci/configs/swx-clx01/hostfile.txt
- .ci/configs/swx-clx02/hostfile.txt
- .ci/job_matrix.yaml
- .ci/proj_jjb.yaml
- .ci/scripts/build_ucc.sh
- .ci/scripts/build_ucx.sh
- .ci/scripts/configure_python.sh
- .ci/scripts/env.sh
- .ci/scripts/install_torch.sh
- .ci/scripts/install_torch_ucc.sh
- .ci/scripts/run_dlrm.sh
- .ci/scripts/run_dlrm_docker.sh
- .ci/scripts/run_dlrm_s_pytorch.sh
- .ci/scripts/run_docker.sh
- .ci/scripts/run_tests_torch_ucc.sh
- .ci/scripts/run_tests_ucc.sh
- .ci/scripts/run_tests_ucc_mpi.sh
- .ci/scripts/run_tests_ucc_mpi_docker.sh
- .ci/scripts/stop_docker.sh
- .gitignore
Enabled Jenkins CI (ported from master branch).
Enabled extended test scenarios.
> TEST: Enabled Jenkins CI (for v0.1.x)

- src/Makefile.am
- src/coll_patterns/recursive_knomial.h
- src/coll_patterns/sra_knomial.h
- src/coll_score/ucc_coll_score.c
- src/components/base/ucc_base_iface.h
- src/components/tl/ucp/Makefile.am
- src/components/tl/ucp/allgather/allgather.h
- src/components/tl/ucp/allgather/allgather_knomial.c
- src/components/tl/ucp/allreduce/allreduce.c
- src/components/tl/ucp/allreduce/allreduce.h
- src/components/tl/ucp/allreduce/allreduce_knomial.c
- src/components/tl/ucp/allreduce/allreduce_sra_knomial.c
- src/components/tl/ucp/barrier/barrier_knomial.c
- src/components/tl/ucp/reduce_scatter/reduce_scatter.h
- src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
- src/components/tl/ucp/tl_ucp.c
- src/components/tl/ucp/tl_ucp.h
- src/components/tl/ucp/tl_ucp_coll.h
- src/components/tl/ucp/tl_ucp_context.c
- src/components/tl/ucp/tl_ucp_lib.c
- src/core/ucc_coll.c
- src/schedule/ucc_schedule.c
- src/schedule/ucc_schedule.h
- src/utils/ucc_math.h
Adds knomial scatter-reduce-allgather (with arbitrary radix) algorithm.
This is one of the algs targeting large msg sizes
Implemented as a schedule constructed of reduce-scatter and allgather tasks
(depends on #159) 
Some perf data: 
[ucc_sra.xlsx](https://github.com/openucx/ucc/files/6351836/ucc_sra.xlsx)
> TL/UCP: SRA knomial allreduce

- src/components/mc/cpu/mc_cpu.c
- src/components/mc/cuda/mc_cuda.c
- src/components/tl/ucp/tl_ucp.c
- src/core/ucc_mc.c
porting https://github.com/openucx/ucc/pull/180
> MC: Fix mem_query when addr is NULL - v0.1.x

- test/gtest/core/test_alltoallv.cc
Fixing test to fit v collective. 
Found bug
Fixed info buffer to info_v buffer.
> Fix alltoallv test

- test/gtest/common/test_obj_size.cc
Fix test_obj_size test 
UCS ucs_log_component_config_t was changed recently
Adjust expected value
> TEST: Fix test_obj_size

- test/gtest/core/test_bcast.cc
Fix free in test_bcast 
Un-needed free
Add same condition as in allocation
> TEST: Fix data_finiliaze in test_bcast

- test/gtest/common/test_obj_size.cc
> V0.1.x: TEST: Fix test_obj_size (#209)

- .ci/Dockerfile.centos8
- .ci/Dockerfile.fedora33
- .ci/job_matrix.yaml
- .ci/scripts/build_ucc.sh
- .ci/scripts/build_ucx.sh
- .ci/scripts/check_code_format.sh
- .ci/scripts/install_torch_ucc.sh
- .ci/scripts/run_dlrm.sh
- .ci/scripts/run_dlrm_docker.sh
- .ci/scripts/run_dlrm_s_pytorch.sh
- .ci/scripts/run_tests_torch_ucc.sh
- .ci/scripts/run_tests_ucc.sh
- .ci/scripts/run_tests_ucc_mpi.sh
- .ci/scripts/run_tests_ucc_mpi_docker.sh
Enabled code format checks (based on clang-format)
To improve code quality.
> TEST: Enabled clang-format

- src/schedule/ucc_schedule.h
> V0.1.x: CORE: bugfix in ucc_task_complete

- config/m4/configure.m4
- configure.ac
- src/Makefile.am
- src/components/tl/ucp/allgather/allgather_knomial.c
- src/components/tl/ucp/allgather/allgather_ring.c
- src/components/tl/ucp/allreduce/allreduce_sra_knomial.c
- src/components/tl/ucp/alltoall/alltoall_pairwise.c
- src/components/tl/ucp/alltoallv/alltoallv_pairwise.c
- src/components/tl/ucp/barrier/barrier_knomial.c
- src/components/tl/ucp/bcast/bcast_knomial.c
- src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
- src/components/tl/ucp/tl_ucp.h
- src/components/tl/ucp/tl_ucp_coll.h
- src/core/ucc_coll.c
- src/core/ucc_constructor.c
- src/core/ucc_global_opts.c
- src/core/ucc_global_opts.h
- src/core/ucc_mc.c
- src/utils/profile/ucc_profile.c
- src/utils/profile/ucc_profile.h
- src/utils/profile/ucc_profile_core.h
- src/utils/profile/ucc_profile_off.h
- src/utils/profile/ucc_profile_on.h
- src/utils/ucc_compiler_def.h
- src/utils/ucc_parser.h
- test/gtest/common/test_obj_size.cc
Profiling MC functions (reduce, multi reduce, alloc) and TL UCP collectives
UCC profiling is based on UCS profile. It was extended here to support profiling external libraries https://github.com/openucx/ucx/pull/6827
Supported profiler API:
UCC_PROFILE_FUNC - function profiling
UCC_PROFILE_REQUEST_NEW, UCC_PROFILE_REQUEST_EVENT, UCC_PROFILE_REQUEST_FREE  - capture nb progress.
ucx_read_profile should be user to print profiling results
allreduce profiling example:
accum mode
```
ucs lib : libucs.so.0
command : ucc_perftest
pid     : 51205
threads : 1  (showing thread 1)
NAME    AVG (usec)  TOTAL (usec)      %OVERALL        COUNT               FILE:LINE   FUNCTION                            THREADS
ucc_mc_reduce_multi      1276.049     571669.90        44.480          448 …
```
> UCC Profile

- src/components/mc/cuda/kernel/mc_cuda_reduce.cu
- src/components/mc/cuda/kernel/mc_cuda_reduce_multi.cu
- src/components/mc/cuda/kernel/mc_cuda_reduce_ops.h
Added support for UCC_DT_FLOAT16 in cuda memory component
> MC/CUDA: fp16 reduce

- src/schedule/ucc_schedule.c
porting https://github.com/openucx/ucc/pull/227
> v0.1.x CORE: call task complete for schedule

- src/components/mc/cuda/mc_cuda.c
Backporting part of https://github.com/openucx/ucc/pull/207
> v0.1.x MC/CUDA: decrease getAddressRange log level

- Makefile.am
- src/ucc/api/ucc.h
- fixed ucc_context_create params
- fixed building with --with-docs-only
- added ref to ucc_status_t
> DOCS: fixing doxygen

- src/ucc/api/ucc.h
To clarify https://github.com/openucx/ucc/pull/221
> API: Adding details for buffer info

- .ci/Dockerfile.centos8
- .ci/Dockerfile.fedora33
- .ci/job_matrix.yaml
Updated torch_ucc repo, fixed cmake issue
CI failed.
> TEST: Updated torch_ucc repo, fixed cmake issue

- src/components/tl/ucp/allreduce/allreduce_sra_knomial.c
Sets triggered_post fn pointer
> TL/UCP: triggered post for sra

- test/gtest/common/test_ucc.cc
Disables NCCL and GDR in gtest
NCCL is not supported due to blocking team creation
GDR currently may result in a hang (known issue)
internally sets env vars: UCC_TL_NCCL_TUNE=0 and UCX_IB_GPU_DIRECT_RDMA=no
> TEST: disable NCCL and GDR

- src/components/tl/nccl/tl_nccl_coll.c
- src/components/tl/ucp/allgather/allgather_ring.c
- src/components/tl/ucp/alltoall/alltoall_pairwise.c
- test/gtest/core/test_allgather.cc
- test/gtest/core/test_alltoall.cc
- test/mpi/test_allgather.cc
- test/mpi/test_alltoall.cc
> V0.1.x: Adjust allgather, alltoall count

- .ci/Dockerfile.centos8
W/A for DLRM installation https://github.com/onnx/onnx/issues/3621
DLRM installation failed.
> TEST: W/A for DLRM installation

- src/components/tl/ucp/tl_ucp.h
- src/components/tl/ucp/tl_ucp_context.c
- src/components/tl/ucp/tl_ucp_ep.c
- src/components/tl/ucp/tl_ucp_ep.h
- test/gtest/common/test_ucc.h
Change ep close proccess and fix small bug in gtest.
https://github.com/openucx/ucx/pull/7140
Causing hang in great without the change
Change ep close according to UCX examples, with consideration to special cases where we don't have OOB and need to ignore errors in ep close, which are expected
> TL/UCP: Fix bug in ep close

- config/m4/ucx.m4
- src/utils/ucc_proc_info.c
- src/utils/ucc_proc_info.h
Add use of UCS ucs_get_system_id in proc_info 
More accurate machine id in various cases
Check for function existence in UCS, is yes - use it, else keep same.
> UTILS: Add ucs machine id

- README.md
Adding front matter as per UCF legal counsel recommendation
> DOC: Adding UCF legal frontmatter

- src/coll_score/ucc_coll_score_map.c
- src/components/mc/cuda/mc_cuda.c
- src/components/tl/nccl/tl_nccl.h
- src/components/tl/nccl/tl_nccl_coll.c
- src/components/tl/nccl/tl_nccl_coll.h
- src/components/tl/nccl/tl_nccl_team.c
- src/utils/ucc_log.h
- test/mpi/Makefile.am
- test/mpi/main.cc
- test/mpi/test_allgatherv.cc
- test/mpi/test_case.cc
- test/mpi/test_mpi.cc
- test/mpi/test_mpi.h
- test/mpi/test_reduce.cc
- test/mpi/test_reduce_scatter.cc
Adding reduce scatter and reduce to NCCL TL and corresponding tests.
For discussion:
In case of in-place reduce-scatter how the destination vector should look like. Rank N will have result shifted by N * count?
> TL/NCCL: add reduce scatter and reduce

- config/m4/cuda.m4
- src/components/mc/cuda/kernel/Makefile.am
Fix building UCC when CUDA is not in default path 
Use nvcc absolute path
> BUILD: fix nvcc configure

- .ci/Dockerfile.centos8
- .ci/scripts/install_torch.sh
Updated PyTorch.
To support latest PyTorch versions.
> Updated pytorch

- config/m4/ucx.m4
- src/core/ucc_lib.c
- src/utils/ucc_parser.h
Fix compilation error in ucc_config_names_search
openucx/ucx#7379
> UTIL: ucs_config_names_search signature

- src/components/tl/nccl/tl_nccl_coll.c
- src/components/tl/ucp/allreduce/allreduce.h
- src/components/tl/ucp/tl_ucp.h
- src/ucc/api/ucc.h
Add Average reduce operation to ucc API 
Add new type of reduce operation
Add to API
> API: Add Average Reduce Operation

- src/ucc/api/ucc.h
Addressing issue https://github.com/openucx/ucc/issues/270
> API: Clarifying semantics for coll args flags and adding documentation

- .github/workflows/main.yaml
Adds ompi/coll/ucc to github checks
Keep ompi/coll/ucc up-to-date with ucc devel
Clone ompi v5.0.x, build with ucx, build Intel-MPI-benchmark with "data-check" option and run basic sanity correctness checks with ompi/coll/ucc.
> TEST: add ompi/coll/ucc to github actions

- src/Makefile.am
- src/components/tl/ucp/tl_ucp_coll.c
- src/core/ucc_coll.c
- src/core/ucc_progress_queue_mt.c
- src/core/ucc_progress_queue_st.c
- src/schedule/ucc_schedule.h
- src/ucc/api/ucc.h
- src/ucc/api/ucc_status.h
- src/utils/ucc_coll_utils.h
- src/utils/ucc_status.c
- src/utils/ucc_time.h
- test/gtest/Makefile.am
- test/gtest/common/test_ucc.cc
- test/gtest/common/test_ucc.h
- test/gtest/core/test_timeout.cc
Adds the TIMEOUT option to the ucc_coll_args
> API: coll timeout option

- src/components/tl/ucp/tl_ucp.h
- src/components/tl/ucp/tl_ucp_context.c
- src/components/tl/ucp/tl_ucp_ep.c
- src/components/tl/ucp/tl_ucp_ep.h
Fixes array eps storage in TL/UCP
The flow was not enabled before due to incorrect check during tl ucp context create.
> TL/UCP: fix eps array storage

- src/components/tl/ucp/tl_ucp.c
Add broadcast algs description to ucc_info
> TL/UCP: add bcast algs to info

- src/components/tl/ucp/allreduce/allreduce_knomial.c
- src/components/tl/ucp/allreduce/allreduce_sra_knomial.c
- test/gtest/core/test_allreduce.cc
- test/mpi/test_allreduce.cc
Modify tests (gtest/mpi) accordingly to stress the potential
garbage in coll_args.src for INPLACE.
Fix SRA schedule for INPLACE.
> TL/UCP: fix inplace SRA

- src/components/tl/sharp/tl_sharp_coll.c
Remove unused ucc_sharp_check_dt_supported
Fix building with clang
> TL/SHARP: remove unused check dt

- src/components/tl/nccl/tl_nccl_coll.c
Fix converting ucc datatype to nccl datatype
> TL/NCCL: fix ucc to nccl dt convert

- src/components/cl/hier/allreduce/allreduce_rab.c
- src/components/cl/hier/cl_hier.h
Fix correctness for inplace RAB allreduce
> CL/HIER: fix inplace allreduce

- src/components/tl/ucp/allreduce/allreduce_sra_knomial.c
- src/components/tl/ucp/bcast/bcast_sag_knomial.c
- src/components/tl/ucp/tl_ucp_coll.h
Set base args for schedule in TL UCP
Fixes false timeout error for broadcast
> TL/UCP: fix bcast schedule timeout

- .ci/Dockerfile.centos8
- .ci/build_base_docker/Dockerfile.centos8.base
- .ci/build_base_docker/job_matrix.yaml
- .ci/build_base_docker/proj_jjb.yaml
Do nightly build for docker image and use it in PR
Build docker image take many time
do separate jenkins job for nightly build with (UCX, torch, dlrm)
> TEST: Refactor ci

- src/components/tl/ucp/Makefile.am
- src/components/tl/ucp/alltoall/alltoall.c
- src/components/tl/ucp/alltoall/alltoall.h
- src/components/tl/ucp/alltoall/alltoall_onesided.c
- src/components/tl/ucp/tl_ucp.c
- src/components/tl/ucp/tl_ucp_coll.c
- src/components/tl/ucp/tl_ucp_coll.h
Adding a one-sided alltoall implementation for the UCP TL. The algorithm implemented is a naive, linear algorithm with synchronization on exit.  
This will add a basic, one-sided alltoall algorithm, which does not exist.
> TL/UCP: One-sided A2A

- src/components/base/ucc_base_iface.c
- src/core/ucc_team.c
minor fixes to make linter happy
> CORE: fix linter warnings

- .ci/Dockerfile.centos8
Docker image use incorrect source ucc
> TEST: Fix work with source in docker image

- src/components/tl/ucp/tl_ucp.h
- src/components/tl/ucp/tl_ucp_context.c
- src/components/tl/ucp/tl_ucp_sendrecv.h
- src/components/tl/ucp/tl_ucp_team.c
Query UCP for supported memory types and enable TL UCP collectives for them only
> TL/UCP: query supported memory types

- .gitignore
Add generated makefiles to gitignore
> BUILD: gitignore plugins generated makefile

- configure.ac
bump version after creating 1.0 branch
> BUILD: bump version to 1.1.0

- src/utils/ucc_mpool.c
> V1.0.x:  UTIL: fix ucs mpool v1.13.x

- src/Makefile.am
- src/components/cl/hier/cl_hier_context.c
- src/components/mc/cpu/mc_cpu.c
- src/components/mc/cuda/mc_cuda.c
- src/components/tl/nccl/tl_nccl_context.c
- src/components/tl/sharp/tl_sharp_context.c
- src/components/tl/ucp/tl_ucp_context.c
- src/utils/arch/aarch64/cpu.h
- src/utils/arch/cpu.h
- src/utils/arch/ppc64/cpu.h
- src/utils/arch/x86_64/cpu.h
- src/utils/ucc_compiler_def.h
Adding CPU architecture specific functions
Required to implement TL CUDA and TL SHM
Copy of needed functions from UCS
> UTIL: ucc cpu arch specific functions

- src/ucc/api/ucc.h
- tools/perf/Makefile.am
- tools/perf/ucc_pt_benchmark.cc
- tools/perf/ucc_pt_coll.h
- tools/perf/ucc_pt_coll_allgather.cc
- tools/perf/ucc_pt_coll_reduce_scatter.cc
- tools/perf/ucc_pt_config.cc
add reduce_scatter to perftest
> TOOLS: add reduce_scatter to perftest

- NEWS
Update NEWS file to reflect the release
> DOCS: Updating NEWS

- .github/workflows/docs.yaml
- config/m4/check_tls.m4
- configure.ac
- src/components/tl/ucp/configure.m4
- src/ucc/api/ucc.h
* Fix building documentation with --with-docs-only flag
* Fix doxygen syntax
* Build and upload docs using github actions, pdf file will be available for 7 days
> DOCS: fix docs build

- src/components/tl/ucp/allgather/allgather.c
Fixes incorrect datatype check for inplace allgather in TL UCP
> TL/UCP: fix allgather dt check

- src/components/tl/ucp/allgather/allgather.c
Backport https://github.com/openucx/ucc/pull/383
> TL/UCP: fix allgather dt check - v1.0

- AUTHORS
> DOCS: Adding Authors (#386)

- docs/doxygen/collectives.md
> DOCS: Adding Collective Operations Semantics (#384)

- src/components/tl/ucp/alltoall/alltoall_onesided.c
- src/ucc/api/ucc.h
- test/gtest/common/test_ucc.cc
- test/gtest/common/test_ucc.h
- test/gtest/core/test_alltoall.cc
- test/gtest/core/test_context.cc
Adds some onesided and onesided alltoall unit tests
This adds the tests missing from PR #309 and #323.
> TEST/GTEST: adds onesided alltoall test

- src/components/tl/ucp/alltoall/alltoall_onesided.c
- src/ucc/api/ucc.h
- test/gtest/common/test_ucc.cc
- test/gtest/common/test_ucc.h
- test/gtest/core/test_alltoall.cc
- test/gtest/core/test_context.cc
Port of #374 to v1.0.x release branch
> TEST/GTEST: adds onesided alltoall test (#374)

- .azure/azure-pipelines-pr.yml
> TEST: add gtest ucc on BF2

- README.md
- config/m4/cuda.m4
- src/components/mc/cuda/mc_cuda.c
Check minimum required CUDA version
Fixes https://github.com/openucx/ucc/issues/370
> BUILD: check cuda version

- .azure/azure-pipelines-pr.yml
- .ci/job_matrix.yaml
Move code check format to azure
need to add warning flag in error case
> TEST: Move check code format to azure and add warning flag

- src/ucc/api/ucc.h
> API: Fix spelling in comment

- .azure/azure-pipelines-pr.yml
> TEST: azure warning

- src/core/ucc_coll.c
- src/utils/ucc_coll_utils.h
- test/gtest/common/test_ucc.h
- test/gtest/core/test_allgather.cc
- test/gtest/core/test_allgatherv.cc
- test/gtest/core/test_allreduce.cc
- test/gtest/core/test_alltoall.cc
- test/gtest/core/test_alltoallv.cc
- test/gtest/core/test_bcast.cc
- test/gtest/core/test_reduce.cc
- test/gtest/core/test_reduce_scatter.cc
- test/mpi/test_barrier.cc
init/finalize reqs for multiple barriers
Fixes incorrect UCC API usage in barrier test
> TEST: mpi/barrier test fix

- src/components/tl/ucc_tl.h
- src/core/ucc_team.c
- src/utils/ucc_coll_utils.c
- src/utils/ucc_coll_utils.h
- src/utils/ucc_datastruct.h
- src/utils/ucc_sys.c
- src/utils/ucc_sys.h
Additions within util, needed to support tl/shm.
> UTIL: additions needed for tl/shm

- src/components/tl/cuda/alltoall/alltoall.c
Check inplace alltoall in TL CUDA
Fixes crash with ucc_test_mpi
> TL/CUDA: alltoall inplace check

- .github/workflows/clang-tidy.yaml
Replace clang11 with clang12 in tests
> TEST: use clang12 for tests

- src/ucc/api/ucc.h
> DOCS: Fix make docs error

- src/Makefile.am
- src/utils/arch/aarch64/cpu.c
- src/utils/arch/aarch64/cpu.h
- src/utils/arch/cpu.h
- src/utils/arch/ppc64/cpu.h
- src/utils/arch/x86_64/cpu.c
- src/utils/arch/x86_64/cpu.h
- src/utils/ucc_compiler_def.h
Adding CPU model & vendor detection
Needed for TL SHM implementation
Copy of needed functions from UCS
> UTIL: cpu model and vendor detection

- src/coll_score/ucc_coll_score_map.c
Resolve boundary between neighbour ranges:
if ranges share a msg size as boundary leave that msgsize to the range wit higher score. That way components that report higher scores do not get overwritten at range boundary.
Example: TL/SHM can support bcast up to segment_size (say 4096), it enables the corresponding msg_range [0-4096]. However, w/o the fix msgsize=4096 would go to tl/ucp still.
> CORE: score fix on range boundary

- src/components/tl/ucp/Makefile.am
- src/components/tl/ucp/reduce_scatterv/reduce_scatterv.c
- src/components/tl/ucp/reduce_scatterv/reduce_scatterv.h
- src/components/tl/ucp/reduce_scatterv/reduce_scatterv_ring.c
- src/components/tl/ucp/tl_ucp.c
- src/components/tl/ucp/tl_ucp.h
- src/components/tl/ucp/tl_ucp_coll.c
- src/components/tl/ucp/tl_ucp_coll.h
- src/utils/ucc_coll_utils.h
- test/gtest/Makefile.am
- test/gtest/core/test_reduce_scatterv.cc
- test/mpi/Makefile.am
- test/mpi/main.cc
- test/mpi/test_case.cc
- test/mpi/test_mpi.cc
- test/mpi/test_mpi.h
- test/mpi/test_reduce_scatterv.cc
Implements ReduceScatterV ring algorithm in TL/UCP
Adds RSV to test/mpi and gtest
> TL/UCP: reduce_scatterV ring algorithm

- src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
Fixes memory corruption caused by tl_ucp_reduce_scatter_knomial algorithm. It can be reproduced when SRA allreduce is enabled for very small msg sizes (e.g. 4 bytes AR) - this is not default. In those cases dst buffer can not be used as scratch (amount of recv data can overrun it)
> TL/UCP: correct RS knomial scratch size

- src/components/tl/nccl/tl_nccl_coll.c
Set task completion immediately if stream is captruing
> TL/NCCL: check stream capturing

- src/components/tl/ucp/reduce/reduce.c
- src/components/tl/ucp/reduce/reduce_knomial.c
Porting reduce avg pre op fix from PR #449
> TL/UCP: reduce_kn avg pre op fix (#449)

- src/components/tl/ucp/bcast/bcast_sag_knomial.c
bug fix
compilation error
Fix compilation error in TL/UCP bcast
> TL/UCP: fix compilation error

- src/components/tl/cuda/tl_cuda_team_topo.c
Changed the algorithm to find proxy ranks for alltoall
Better performance on HCM topology
New algorithm considers link bandwidth between ranks before choosing proxy
> TL/CUDA: find better proxies for alltoall

- src/components/tl/nccl/tl_nccl.h
- src/components/tl/nccl/tl_nccl_coll.c
- src/components/tl/nccl/tl_nccl_coll.h
- src/components/tl/nccl/tl_nccl_team.c
- test/mpi/Makefile.am
- test/mpi/main.cc
- test/mpi/test_case.cc
- test/mpi/test_gather.cc
- test/mpi/test_mpi.h
Adding support for UCC_COLL_TYPE_GATHER to TL NCCL and adding gather test to ucc_test_mpi
NCCL doesn't have native support for gather operation, implementation in TL NCCL is base on ncclSend/ncclRecv
> TL/NCCL: add gather

- src/schedule/ucc_schedule.c
- src/schedule/ucc_schedule.h
- src/schedule/ucc_schedule_pipelined.c
- src/schedule/ucc_schedule_pipelined.h
V1.0.x of #463 
* SCHEDULE: fix race in n_completed_tasks
* SCHEDULE: fix race in pipelined sched finalize
* SCHEDULE: fix race in sched task cleanup
(cherry picked from commit b07ebd9795cc4f98a96553adf5686651be44b42d)
> V1.0.x Multithreading fixes (#463)

- src/schedule/ucc_schedule.h
removes unused code (committed accidentally as part #463)
> SCHEDULE: remove unused fn

- test/gtest/utils/test_ep_map.cc
fix leak in test nested ep map
> TEST: fix leak in test nested ep map

- src/components/tl/nccl/tl_nccl.h
- src/components/tl/nccl/tl_nccl_coll.c
- src/components/tl/nccl/tl_nccl_coll.h
- src/components/tl/nccl/tl_nccl_team.c
- test/mpi/Makefile.am
- test/mpi/main.cc
- test/mpi/test_case.cc
- test/mpi/test_gatherv.cc
- test/mpi/test_mpi.h
Adding support for UCC_COLL_TYPE_GATHERV to TL NCCL and adding gatherv test to ucc_test_mpi
NCCL doesn't have native support for gatherv operation, implementation in TL NCCL is base on ncclSend/ncclRecv
> TL/NCCL: add gatherv

- .ci/scripts/run_tests_ucc_mpi.sh
- src/components/ec/cuda/ec_cuda.c
- src/components/ec/cuda/ec_cuda.h
- src/components/mc/cuda/mc_cuda.c
- src/components/mc/cuda/mc_cuda.h
- src/utils/ucc_atomic.h
- test/mpi/main.cc
- test/mpi/test_mpi.cc
- test/mpi/test_mpi.h
Fixes threading in ucc_test_mpi (incorrect thread_mode parsing/init order)
Verbose option (less output by default)
Run MT tests in jenkins
> Fix multi-threading of ucc_test_mpi

- src/components/tl/nccl/tl_nccl.h
- src/components/tl/nccl/tl_nccl_coll.c
- src/components/tl/nccl/tl_nccl_coll.h
- src/components/tl/nccl/tl_nccl_team.c
- test/mpi/Makefile.am
- test/mpi/main.cc
- test/mpi/test_case.cc
- test/mpi/test_mpi.h
- test/mpi/test_scatter.cc
Adding support for UCC_COLL_TYPE_SCATTER to TL NCCL and adding scatter test to ucc_test_mpi
NCCL doesn't have native support for scatter operation, implementation in TL NCCL is base on ncclSend/ncclRecv
> TL/NCCL: add scatter

- src/components/cl/hier/cl_hier_team.c
- src/core/ucc_team.c
Proper CL/HIER team clean
Proper release of CL team in case of failure at core level
> CL/HIER: team cleanup fix

- src/components/tl/cuda/alltoallv/alltoallv_ce.c
fix sync on remote event in tl cuda alltoallv
> TL/CUDA: fix sync on remote event

- src/components/ec/cuda/ec_cuda.c
- src/components/ec/cuda/ec_cuda.h
- src/components/mc/cuda/mc_cuda.h
- src/components/tl/nccl/tl_nccl.c
- src/components/tl/nccl/tl_nccl_coll.c
- src/utils/arch/cuda_def.h
Add more checks in TL NCCL, MC CUDA, EC CUDA
> TL/NCCL: fix status checks in nccl and cuda

- src/components/tl/ucp/allgather/allgather_ring.c
- src/components/tl/ucp/alltoall/alltoall_pairwise.c
- src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
- src/components/tl/ucp/scatter/scatter_knomial.c
- src/core/ucc_coll.c
> TEST: fix clang tidy warns

- tools/perf/Makefile.am
- tools/perf/ucc_pt_benchmark.cc
- tools/perf/ucc_pt_coll.h
- tools/perf/ucc_pt_coll_gather.cc
- tools/perf/ucc_pt_coll_gatherv.cc
- tools/perf/ucc_pt_coll_scatter.cc
- tools/perf/ucc_pt_coll_scatterv.cc
- tools/perf/ucc_pt_config.cc
Adding perf tests for scatter, scatterv, gather, gatherv.
Depends on PR: #472 #473 #474
> TOOLS: adding perftest for scatter,scatterv,gather,gatherv

- src/components/cl/hier/allreduce/allreduce.c
- src/components/cl/hier/cl_hier.c
- src/components/tl/ucp/allgather/allgather.c
- src/components/tl/ucp/allgather/allgather.h
- src/components/tl/ucp/allgatherv/allgatherv.c
- src/components/tl/ucp/allgatherv/allgatherv.h
- src/components/tl/ucp/allreduce/allreduce.c
- src/components/tl/ucp/alltoallv/alltoallv.c
- src/components/tl/ucp/alltoallv/alltoallv.h
- src/components/tl/ucp/barrier/barrier.c
- src/components/tl/ucp/barrier/barrier.h
- src/components/tl/ucp/bcast/bcast.c
- src/components/tl/ucp/fanin/fanin.c
- src/components/tl/ucp/fanin/fanin.h
- src/components/tl/ucp/fanout/fanout.c
- src/components/tl/ucp/fanout/fanout.h
- src/components/tl/ucp/reduce/reduce.c
- src/components/tl/ucp/reduce/reduce.h
- src/components/tl/ucp/tl_ucp.c
- tools/info/ucc_info.c
Adds alg_info descriptors for TL/UCP for all colls.
Adds alg_info for CL/HIER colls.
update ucc_info -A print
Print up-to-date info about algorithms
```
[~/workspace/build/debug/ucc]
[valentinp@hpchead]>  ./install/bin/ucc_info -A
cl/hier algorithms:
Allreduce
0 :              rab : innode reduce, followed by inter node allreduce, followed by innode broadcast
1 :       split_rail : innode reduce scatter, followed by PPN concurrent inter node allreduces, followed by innode allgather
Alltoall
0 :       node_split : splitting alltoall into two concurrent a2av calls withing the node and outside of it
Alltoallv
0 :       node_split : splitting alltoallv into two concurrent a2av calls withing the node and outside of it
tl/nccl algorithms:
Allgatherv
0 :              p2p : allgatherv based on …
```
> alg info update

- config/m4/ucx.m4
- src/utils/ucc_mpool.c
Detect changes in ucs/datastruct/mpool.h regarding ucs_mpool_init signature. Fix build/usage.
> UTIL: adjust to ucs mpool changes

- src/components/ec/cuda/ec_cuda_executor_interruptible.c
- src/components/tl/cuda/allgather/allgather_ring.c
- src/components/tl/cuda/allgatherv/allgatherv_ring.c
- src/components/tl/cuda/reduce_scatterv/reduce_scatterv_ring.c
- src/components/tl/cuda/tl_cuda.c
- src/components/tl/cuda/tl_cuda.h
- src/components/tl/cuda/tl_cuda_lib.c
- src/components/tl/cuda/tl_cuda_ring.h
Support multiple rings in TL CUDA allgather and allgatherv
> TL/CUDA: multiring allgatherv and reduce_scatterv

- .azure/azure-pipelines-pr.yml
- .ci/job_matrix.yaml
test take more time than existing timeout on slow hosts
> TEST: Increase CI timeouts

- src/components/topo/ucc_sbgp.h
- src/components/topo/ucc_topo.h
- src/core/ucc_team.h
Adds 2 simple helper functions to TOPO framework: both used in TL/MLX5.
> (tl_mlx5_1) TOPO: helper utilities

- src/components/tl/ucp/Makefile.am
- src/components/tl/ucp/gather/gather.c
- src/components/tl/ucp/gather/gather.h
- src/components/tl/ucp/gather/gather_knomial.c
- src/components/tl/ucp/tl_ucp.c
- src/components/tl/ucp/tl_ucp.h
- src/components/tl/ucp/tl_ucp_coll.c
- src/components/tl/ucp/tl_ucp_coll.h
- src/components/tl/ucp/tl_ucp_lib.c
- src/utils/ucc_math.h
- test/gtest/Makefile.am
- test/gtest/coll/test_gather.cc
- test/gtest/common/test_ucc.h
- test/mpi/test_gather.cc
- TL/UCP: Add gather collective
- TEST: Fix a bug in the MPI Test
- TEST: add gather in Gtest
gather is performed with a k-nomial algorithm
> TL/UCP: add gather with k-nomial algorithm

- src/components/tl/ucc_tl.h
- src/components/tl/ucp/bcast/bcast.h
- src/components/tl/ucp/tl_ucp.c
- src/components/tl/ucp/tl_ucp_service_coll.c
- src/core/ucc_service_coll.c
- src/core/ucc_service_coll.h
Adds Bcast to service team interface and support in tl/ucp.
> (tl_mlx5_2) TL/UCP: service bcast

- src/components/tl/cuda/alltoallv/alltoallv_ce.c
Alltoall fixes
* Fix executor task finalize is not being called
* Don't post executor task with zero size
> TL/CUDA: fix exec task finalize

- src/ucc/api/ucc.h
Fix doc in ucc.h
* fix ucc_coll_type_t description, supported collectives depends on TLs available
* start all arguments with capital letter
* fix https://github.com/openucx/ucc/issues/341
> DOCS: fix ucc.h inline doc

- src/components/tl/self/tl_self_context.c
> TL/SELF: fix linter warnings

- src/core/ucc_context.h
- src/core/ucc_team.c
- src/ucc/api/ucc.h
> CORE: fix spelling

- src/components/ec/base/ucc_ec_base.h
- src/components/ec/cpu/ec_cpu.c
- src/components/ec/cuda/ec_cuda_executor_interruptible.c
- src/components/ec/cuda/kernel/ec_cuda_executor.cu
- src/components/tl/cuda/allgatherv/allgatherv_ring.c
- src/components/tl/cuda/alltoallv/alltoallv_ce.c
- src/components/tl/cuda/reduce_scatterv/reduce_scatterv_ring.c
- src/components/tl/cuda/tl_cuda.c
- src/components/tl/cuda/tl_cuda.h
- src/components/tl/cuda/tl_cuda_lib.c
- src/components/tl/cuda/tl_cuda_team_topo.c
- src/utils/ucc_coll_utils.h
* Add copy multi operation to executor (multiple sources and destinations in 1 task)
* Change multiting allgatherv algorithm in TL CUDA to use copy multi operation.
* Split into fragments with alignment to use vectorized load/stores in EC CUDA
> TL/CUDA: multicopy allgatherv

- src/components/tl/cuda/Makefile.am
- src/components/tl/cuda/allgather/allgather.c
- src/components/tl/cuda/allgather/allgather.h
- src/components/tl/cuda/allgather/allgather_linear.c
- src/components/tl/cuda/allgather/allgather_ring.c
- src/components/tl/cuda/allgatherv/allgatherv.c
- src/components/tl/cuda/allgatherv/allgatherv.h
- src/components/tl/cuda/allgatherv/allgatherv_linear.c
- src/components/tl/cuda/allgatherv/allgatherv_ring.c
- src/components/tl/cuda/tl_cuda.c
- src/components/tl/cuda/tl_cuda.h
- src/components/tl/cuda/tl_cuda_coll.c
- src/components/tl/cuda/tl_cuda_coll.h
- src/components/tl/cuda/tl_cuda_team.c
Adding linear allgather algorithm in TL CUDA. Each rank broadcasts its source buffer to each other rank. Supported only on NVSwtich topology. Also added selection logic to allow user to choose what algorithm (ring or linear) to use.
> TL/CUDA: allgather(v) linear alg

- .ci/scripts/run_tests_ucc_mpi.sh
Improves/fixes ucc_test_mpi in Jenkins CI
Runs multi-ppn job, which enables actual CL/HIER flows (before we run only ppn=1 where CL/HIER would be disqualified)
Adds explicit TL/CUDA testing
Adds default configuration run with multi-ppn
TODO: add "triggered". Need to fix TL/UCP scatter/gather which still use ucc_mc_memcpy
> Improve ucc_test_mpi coverage in CI

- src/coll_score/ucc_coll_score.c
- src/components/ec/cuda/ec_cuda.c
- src/components/ec/cuda/ec_cuda.h
- src/components/ec/cuda/kernel/ec_cuda_executor.cu
- src/components/mc/base/ucc_mc_base.c
- src/components/mc/cuda/mc_cuda.c
- src/components/mc/cuda/mc_cuda.h
- src/components/tl/cuda/allgatherv/allgatherv_ring.c
- src/components/tl/cuda/alltoallv/alltoallv_ce.c
- src/components/tl/cuda/reduce_scatterv/reduce_scatterv_ring.c
- src/components/tl/cuda/tl_cuda_topo.c
- src/components/tl/nccl/tl_nccl_coll.c
- src/components/tl/self/tl_self_coll.c
- src/components/tl/ucp/allreduce/allreduce_sra_knomial.c
- src/components/tl/ucp/bcast/bcast_sag_knomial.c
- src/components/tl/ucp/reduce_scatter/reduce_scatter_ring.c
- src/components/tl/ucp/reduce_scatterv/reduce_scatterv_ring.c
- src/components/tl/ucp/tl_ucp.c
- src/components/tl/ucp/tl_ucp_coll.h
- src/components/tl/ucp/tl_ucp_sendrecv.h
- src/components/topo/ucc_sbgp.c
- src/core/ucc_coll.c
- src/core/ucc_constructor.c
- src/core/ucc_dt.h
- src/core/ucc_lib.c
- src/core/ucc_team.c
- src/utils/arch/cuda_def.h
- src/utils/ucc_component.c
- src/utils/ucc_proc_info.c
- src/utils/ucc_string.c
Fixes multiple defects found by Coverity. 
(So far the tool have been run manually, it'll be added to the Jenkins)
The defects mostly benign:
Some of the fixes just a comments to ignore false-positives.
Several memory leaks
Dead-code refactoring
Potential read beyond array size
> Coverity fixes

- src/coll_score/ucc_coll_score.c
- src/components/ec/cuda/ec_cuda.c
- src/components/ec/cuda/ec_cuda.h
- src/components/ec/cuda/kernel/ec_cuda_executor.cu
- src/components/mc/base/ucc_mc_base.c
- src/components/mc/cuda/mc_cuda.c
- src/components/mc/cuda/mc_cuda.h
- src/components/tl/cuda/allgatherv/allgatherv_ring.c
- src/components/tl/cuda/alltoallv/alltoallv_ce.c
- src/components/tl/cuda/reduce_scatterv/reduce_scatterv_ring.c
- src/components/tl/cuda/tl_cuda_topo.c
- src/components/tl/nccl/tl_nccl_coll.c
- src/components/tl/self/tl_self_coll.c
- src/components/tl/ucp/allreduce/allreduce_sra_knomial.c
- src/components/tl/ucp/bcast/bcast_sag_knomial.c
- src/components/tl/ucp/reduce_scatter/reduce_scatter_ring.c
- src/components/tl/ucp/reduce_scatterv/reduce_scatterv_ring.c
- src/components/tl/ucp/tl_ucp.c
- src/components/tl/ucp/tl_ucp_coll.h
- src/components/tl/ucp/tl_ucp_sendrecv.h
- src/components/topo/ucc_sbgp.c
- src/core/ucc_coll.c
- src/core/ucc_constructor.c
- src/core/ucc_dt.h
- src/core/ucc_lib.c
- src/core/ucc_team.c
- src/utils/arch/cuda_def.h
- src/utils/ucc_component.c
- src/utils/ucc_proc_info.c
- src/utils/ucc_string.c
> V1.1.x Coverity fixes

- config/m4/rocm.m4
check ROCm version in configure logic
This allows us to be more accurate when specifying include paths. Reduces the number of warnings generated for the rocm ec component.
> BUILD/ROCM: check ROCm version in configure logic

- config/m4/rocm.m4
> V1.1.x EC/ROCM: check ROCm version in configure

- src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
No need for extra copy if scratch buffer is used (e.g. INPLACE)
> TL/UCP: RS knomial optimization

- src/components/tl/ucp/allgather/allgather_knomial.c
Fixes incorrect ee task test in tl/ucp allgather knomial
> TL/UCP: allgather kn etask test fix

- .ci/scripts/run_tests_ucc_mpi.sh
Set UCX_NET_DEVICES in the CI tests with ucc_test_mpi
to workaround ucp rndv multirail issue
> TEST: set UCX_NET_DEVICE in CI

- src/components/cl/hier/allreduce/allreduce_rab.c
- src/components/tl/ucp/scatter/scatter_knomial.c
> V1.1.x CL/HIER: allreduce rab fix

- src/components/ec/rocm/kernel/ec_rocm_reduce.cu
minor change to unify header include in ec/rocm/kernel
> EC/ROCM: unify header include

- src/components/tl/ucp/allreduce/allreduce_knomial.c
- src/core/ucc_coll.c
- test/mpi/main.cc
- test/mpi/test_allgather.cc
- test/mpi/test_allgatherv.cc
- test/mpi/test_allreduce.cc
- test/mpi/test_alltoall.cc
- test/mpi/test_alltoallv.cc
- test/mpi/test_barrier.cc
- test/mpi/test_bcast.cc
- test/mpi/test_case.cc
- test/mpi/test_gather.cc
- test/mpi/test_gatherv.cc
- test/mpi/test_mpi.cc
- test/mpi/test_mpi.h
- test/mpi/test_reduce.cc
- test/mpi/test_reduce_scatter.cc
- test/mpi/test_reduce_scatterv.cc
- test/mpi/test_scatter.cc
- test/mpi/test_scatterv.cc
Adding support for persistent colls to test mpi
> TEST: adding support for persistent coll to mpi test

- src/components/ec/base/ucc_ec_base.h
- src/components/ec/cuda/ec_cuda_executor_interruptible.c
- src/components/ec/cuda/ec_cuda_executor_persistent.c
- src/components/ec/cuda/kernel/ec_cuda_executor.cu
- src/components/ec/cuda/kernel/ec_cuda_reduce.cu
- src/components/ec/rocm/kernel/ec_rocm_executor_kernel.cu
- src/components/tl/cuda/allgatherv/allgatherv_ring.c
- src/components/tl/cuda/reduce_scatterv/reduce_scatterv_ring.c
- src/components/tl/cuda/tl_cuda.c
- src/components/tl/cuda/tl_cuda.h
- src/components/tl/cuda/tl_cuda_lib.c
- src/components/tl/cuda/tl_cuda_ring.h
Reimplement TL/CUDA reduce scatter ring algorithm using multireduce executor operation
Better bandwidth utilization, support arbitrary number of rings
> TL/CUDA: multireduce reduce scatterv

- .clang-tidy
- .github/workflows/clang-tidy.yaml
- src/components/cl/hier/allreduce/allreduce_split_rail.c
- src/core/ucc_coll.c
- src/schedule/ucc_schedule.c
- src/utils/khash.h
- src/utils/ucc_parser.c
Fixes linter errors. Adds check for new errors/warnings. CI will fail if any new are introduced.
> REVIEW: fix/suppress linter warnings

- src/components/cl/basic/cl_basic.h
- src/components/cl/basic/cl_basic_context.c
- src/components/cl/basic/cl_basic_team.c
- src/components/cl/hier/cl_hier.h
- src/components/cl/hier/cl_hier_context.c
- src/components/cl/ucc_cl.h
- src/core/ucc_context.c
> V1.1.x ctx epilog fail handle

- test/gtest/Makefile.am
- test/gtest/core/test_ec_cuda.cc
> TEST: add basic tests for ec cuda

- src/components/cl/hier/allreduce/allreduce_rab.c
- src/components/cl/hier/allreduce/allreduce_split_rail.c
- src/components/cl/hier/cl_hier.c
- src/components/cl/hier/cl_hier.h
- src/components/tl/ucp/allreduce/allreduce_sra_knomial.c
- src/components/tl/ucp/tl_ucp.c
- src/components/tl/ucp/tl_ucp.h
- src/schedule/ucc_schedule_pipelined.h
- src/utils/ucc_parser.c
- src/utils/ucc_parser.h
> CORE: ucc_pipeline_params

- src/components/tl/ucp/Makefile.am
- src/components/tl/ucp/allgatherv/allgatherv.c
- src/components/tl/ucp/allgatherv/allgatherv_ring.c
- src/components/tl/ucp/alltoall/alltoall_pairwise.c
- src/components/tl/ucp/alltoallv/alltoallv_pairwise.c
- src/components/tl/ucp/scatterv/scatterv.c
- src/components/tl/ucp/scatterv/scatterv.h
- src/components/tl/ucp/scatterv/scatterv_linear.c
- src/components/tl/ucp/tl_ucp.c
- src/components/tl/ucp/tl_ucp.h
- src/components/tl/ucp/tl_ucp_coll.c
- src/core/ucc_coll.c
- src/utils/ucc_coll_utils.h
Adding implementation of linear scatterv algorithm
> TL/UCP: add scatterv

- tools/perf/Makefile.am
- tools/perf/ucc_pt_benchmark.cc
- tools/perf/ucc_pt_coll.h
- tools/perf/ucc_pt_coll_reduce_scatterv.cc
- tools/perf/ucc_pt_config.cc
Add reduce_scatterv collective to UCC perftest
> TOOLS: add reduce_scatterv to perftest

- src/components/tl/ucp/Makefile.am
- src/components/tl/ucp/gatherv/gatherv.c
- src/components/tl/ucp/gatherv/gatherv.h
- src/components/tl/ucp/gatherv/gatherv_linear.c
- src/components/tl/ucp/scatterv/scatterv.c
- src/components/tl/ucp/tl_ucp.c
- src/components/tl/ucp/tl_ucp.h
- src/components/tl/ucp/tl_ucp_coll.c
Adding implementation of linear gatherv algorithm
> TL/UCP: add gatherv

- .github/workflows/main.yaml
Add IMB data check for allgatherv
> TEST: check allgatherv with imb

- src/components/tl/cuda/allgather/allgather_linear.c
- src/components/tl/cuda/allgather/allgather_ring.c
- src/components/tl/cuda/allgatherv/allgatherv_linear.c
- src/components/tl/cuda/allgatherv/allgatherv_ring.c
- src/components/tl/cuda/alltoall/alltoall.c
- src/components/tl/cuda/alltoallv/alltoallv.c
- src/components/tl/cuda/reduce_scatter/reduce_scatter.c
- src/components/tl/cuda/reduce_scatterv/reduce_scatterv.c
- src/components/tl/cuda/tl_cuda_coll.h
- src/components/tl/nccl/allgatherv/allgatherv.c
- src/components/tl/nccl/tl_nccl_coll.c
- src/components/tl/nccl/tl_nccl_coll.h
- src/components/tl/nccl/tl_nccl_team.c
- src/components/tl/self/tl_self_coll.c
- src/components/tl/sharp/tl_sharp_coll.c
- src/components/tl/ucp/allgather/allgather.c
- src/components/tl/ucp/allgatherv/allgatherv.c
- src/components/tl/ucp/alltoall/alltoall.h
- src/components/tl/ucp/alltoallv/alltoallv.h
- src/components/tl/ucp/gatherv/gatherv.c
- src/components/tl/ucp/scatterv/scatterv.c
- src/core/ucc_coll.c
- src/utils/ucc_coll_utils.c
- src/utils/ucc_coll_utils.h
Add single function to check userdefined datatype. Return UCC_ERR_NOT_SUPPORTED if TL doesn't support userdefined datatype
> CORE: unify check for userdefined dt

- config/m4/compiler.m4
- src/coll_patterns/recursive_knomial.h
- src/coll_score/ucc_coll_score.c
- src/coll_score/ucc_coll_score_map.c
- src/components/ec/cpu/ec_cpu_reduce.c
- src/components/tl/cuda/tl_cuda_team_topo.c
- src/components/tl/cuda/tl_cuda_team_topo.h
- src/components/tl/cuda/tl_cuda_topo.c
- src/components/tl/cuda/tl_cuda_topo.h
- src/components/tl/sharp/tl_sharp_context.c
- src/components/tl/ucp/allgatherv/allgatherv_ring.c
- src/components/tl/ucp/tl_ucp.h
- src/components/topo/ucc_topo.c
- src/core/ucc_context.h
- src/utils/ucc_parser.c
- src/utils/ucc_proc_info.c
Fix building UCC with nvc https://docs.nvidia.com/hpc-sdk/compilers/hpc-compilers-user-guide/index.html
Fixed bugs:
error 68: integer conversion resulted in a change of sign [integer_sign_change]
error 167: argument of type "int *" is incompatible with parameter of type "unsigned int *" [incompatible_param]
error 188: enumerated type mixed with another type [mixed_enum_type]
error 546: transfer of control bypasses initialization of: [branch_past_initialization]
error 191: type qualifier is meaningless on cast type [cast_to_qualified_type]
error 111: statement is unreachable [code_is_unreachable]
error 1144: arithmetic on pointer to void or function type [nonobject_pointer_arithmetic]
suppressed 
error 301: typedef name has already been declared (with same type) [duplicate_typedef]
> BUILD: fix building with nvc

- .github/workflows/clang-tidy-nvidia.yaml
- src/components/tl/sharp/tl_sharp.c
- src/components/tl/sharp/tl_sharp.h
- src/components/tl/sharp/tl_sharp_context.c
- src/components/tl/sharp/tl_sharp_team.c
> TL/SHARP: fix assert check

- src/components/tl/cuda/Makefile.am
- src/components/tl/cuda/allgather/allgather_linear.c
- src/components/tl/cuda/allgatherv/allgatherv_linear.c
- src/components/tl/cuda/reduce_scatter/reduce_scatter.c
- src/components/tl/cuda/reduce_scatter/reduce_scatter.h
- src/components/tl/cuda/reduce_scatter/reduce_scatter_linear.c
- src/components/tl/cuda/reduce_scatter/reduce_scatter_ring.c
- src/components/tl/cuda/reduce_scatterv/reduce_scatterv.c
- src/components/tl/cuda/reduce_scatterv/reduce_scatterv.h
- src/components/tl/cuda/reduce_scatterv/reduce_scatterv_linear.c
- src/components/tl/cuda/reduce_scatterv/reduce_scatterv_ring.c
- src/components/tl/cuda/tl_cuda.c
- src/components/tl/cuda/tl_cuda.h
- src/components/tl/cuda/tl_cuda_coll.c
- src/components/tl/cuda/tl_cuda_coll.h
- src/components/tl/ucp/reduce_scatter/reduce_scatter.c
- tools/perf/ucc_pt_config.cc
Adding linear reduce scatter algorithm in TL CUDA. Each rank broadcasts its source buffer to each other rank following by local reduce operation. Supported only on NVSwtich topology.
> TL/CUDA: reduce scatter linear

- .ci/scripts/run_tests_ucc_mpi.sh
- src/utils/ucc_parser.c
- test/gtest/coll/test_allreduce.cc
Updating frag piplene env vars usage in gtest and CI, based on PR #675
> TEST: updating frag pipeline env vars

- src/components/tl/ucp/tl_ucp_coll.c
- tools/perf/ucc_pt_benchmark.cc
- tools/perf/ucc_pt_benchmark.h
- tools/perf/ucc_pt_comm.cc
- tools/perf/ucc_pt_config.cc
- tools/perf/ucc_pt_config.h
Add perftest options to set collective root and root shift
> TOOLS: add root and rootshift to perftest

- src/components/tl/cuda/allgather/allgather.c
- src/components/tl/cuda/allgather/allgather_linear.c
- src/components/tl/cuda/allgatherv/allgatherv.c
- src/components/tl/cuda/allgatherv/allgatherv_linear.c
- src/components/tl/cuda/reduce_scatter/reduce_scatter.c
- src/components/tl/cuda/reduce_scatter/reduce_scatter_linear.c
- src/components/tl/cuda/reduce_scatterv/reduce_scatterv.c
- src/components/tl/cuda/reduce_scatterv/reduce_scatterv_linear.c
- src/components/tl/cuda/tl_cuda_team_topo.h
Choose allgather(v) and reduce_scatter(v) algorithm based on NVLink topology. Linear algorithm for fully connected team, ring otherwise.
> TL/CUDA: alg selection based on topo

- src/components/tl/nccl/tl_nccl_team.c
Disable TL NCCL for team size 1
> TL/NCCL: disable for team size 1

- config/m4/compiler.m4
- config/m4/sysdep.m4
- configure.ac
> BUILD: update autoconf

- src/components/tl/nccl/allgatherv/allgatherv.c
Add support for inplace allgatherv in TL NCCL
> TL/NCCL: add support for inplace allgatherv

- src/components/tl/mlx5/Makefile.am
- src/components/tl/mlx5/tl_mlx5.c
- src/components/tl/mlx5/tl_mlx5.h
- src/components/tl/mlx5/tl_mlx5_ib.c
- src/components/tl/mlx5/tl_mlx5_ib.h
- src/components/tl/mlx5/tl_mlx5_team.c
- test/gtest/Makefile.am
- test/gtest/tl/mlx5/test_tl_mlx5.cc
- test/gtest/tl/mlx5/test_tl_mlx5.h
IB utilities of TL/MLX:
* ib context creation
* rc/dc qp creation/connection interfaces
> (tl_mlx5_7) TL/MLX5: ib utilities

- contrib/ucc.conf
Aligning ucc.conf to be similar to that in ucc_private.
For future users who use this file as a template/example for their configurations. This way they will see up to date multiple architectures tuning.
> DOCS: aligning conf file

- .azure/azure-pipelines-pr.yml
Increase azure pipeline timeout for UCX build
Fixes Azure CI failure
> TEST: increase azure timeout

- src/components/tl/rccl/tl_rccl_coll.c
make the datatype checking uniform across all functions in TL/RCCL. Some functions were completely missing this part, which lead to failures in ucc_test_mpi.
Also, use ucc_debug() instead of ucc_error() when reporting unsupported datatypes.
make ucc_test_mpi for rccl/tl pass again and reduces noisiness
> TL/RCCL: cleanup datatype check

- test/gtest/Makefile.am
- test/gtest/coll/test_gatherv.cc
- test/gtest/coll/test_scatterv.cc
Adding gtests for gatherv and scatterv
> Add gatherv scatterv gtests

- .github/workflows/clang-tidy-nvidia.yaml
- src/components/tl/mlx5/tl_mlx5_context.c
- src/components/tl/mlx5/tl_mlx5_ib.c
- src/components/tl/mlx5/tl_mlx5_ib.h
- src/components/tl/mlx5/tl_mlx5_team.c
- test/gtest/tl/mlx5/test_tl_mlx5.h
> TEST: Linter for tl/mlx5

- src/components/tl/mlx5/Makefile.am
- src/components/tl/mlx5/tl_mlx5.h
- src/components/tl/mlx5/tl_mlx5_ib.c
- src/components/tl/mlx5/tl_mlx5_wqe.c
- src/components/tl/mlx5/tl_mlx5_wqe.h
- test/gtest/Makefile.am
- test/gtest/tl/mlx5/test_tl_mlx5.cc
- test/gtest/tl/mlx5/test_tl_mlx5.h
- test/gtest/tl/mlx5/test_tl_mlx5_qps.cc
- test/gtest/tl/mlx5/test_tl_mlx5_qps.h
- test/gtest/tl/mlx5/test_tl_mlx5_wqe.cc
- test/gtest/tl/mlx5/test_tl_mlx5_wqe.h
Implements the WQEs for transpose, wait_on_data, umr, and rdma
> TL/MLX5: custom ib wqes

- src/ucc/api/ucc.h
Reworking #624 , so the hints are in a different structure.
> API: Add hints for coll args

- src/Makefile.am
- src/coll_patterns/bruck_alltoall.h
- src/components/tl/ucp/Makefile.am
- src/components/tl/ucp/alltoall/alltoall.c
- src/components/tl/ucp/alltoall/alltoall.h
- src/components/tl/ucp/alltoall/alltoall_bruck.c
- src/components/tl/ucp/alltoallv/alltoallv_hybrid.c
- src/components/tl/ucp/tl_ucp_coll.c
- src/components/tl/ucp/tl_ucp_coll.h
- src/components/tl/ucp/tl_ucp_team.c
- src/utils/ucc_math.h
Adding alltoall bruck algorithm to TL UCP 
Small message alltoall oriented algorithm
> TL/UCP: add bruck alltoall

- test/mpi/test_mpi.cc
Check operation is supported for given datatype in ucc_test_mpi
> TEST: check op and dt compatibility

- src/components/tl/ucp/alltoallv/alltoallv.h
- src/components/tl/ucp/tl_ucp_coll.c
- src/components/tl/ucp/tl_ucp_coll.h
Default enable hybrid alltoallv added in PR https://github.com/openucx/ucc/pull/687 for comm size 64 and bigger
> TL/UCP: enable hybrid alltoallv

- configure.ac
bump version after creating 1.2 branch
> BUILD: bump version to 1.3.0

- NEWS
> DOCS: Updating NEWS for v1.2

- NEWS
(cherry picked from commit 135e830aa6e2975308f77c0309d91716a854122b)
Adding news for 1.2
> DOCS: Updating NEWS for v1.2 (#791)

- src/components/cl/hier/bcast/bcast_2step.c
- src/components/tl/ucp/alltoall/alltoall_bruck.c
- src/utils/ucc_parser.c
Fixes warning found by coverity
> BUILD: fix coverity warns

- test/gtest/common/gtest-all.cc
Fix building gtest with gcc 13
> BUILD: fix compiling with gcc13

- .github/workflows/codestyle.yaml
add SHM to commit title option
> CI: add shm to commit title option

- config/m4/rdmacm.m4
- configure.ac
- src/components/tl/mlx5/configure.m4
TL/MLX5: [HW Multicast] adding --with-rdmacm configure option
> TL/MLX5: [HW Multicast] adding --with-rdmacm configure option

- src/components/tl/ucp/alltoallv/alltoallv_hybrid.c
Fix recycling of scratch buffer in hybrid alltoallv algorithm. Need to use memmove instead of memcpy for overlapping regions.
Fixes internal issue https://redmine.mellanox.com/issues/3522429
> TL/UCP: fix recycle in hybrid a2av

- src/components/ec/cpu/ec_cpu_reduce.c
- src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
Add additional checks in SRA algorithm. Continue improvements after https://github.com/openucx/ucc/pull/743
> TL/UCP: allreduce sra knomial opt

- .github/workflows/main.yaml
Add more IMB correctness tests
> CI: add more imb tests

- src/components/tl/ucp/allreduce/allreduce_knomial.c
Add reorder ranks in allreduce kn
ranks/peers already using basic 1:1 mapping in default task->subset.map, so no change needed in start/progress, only setting task->subset.map to correct reordering map in init is needed.
> TL/UCP: add reorder ranks in allreduce kn

- src/components/ec/cuda/ec_cuda.h
> EC/CUDA: remove unused macro

- tools/perf/ucc_pt_config.cc
Add support for CUDA managed memory type in UCC perftest
> TOOLS: add cuda managed mtype to perftest

- test/mpi/buffer.cc
- test/mpi/test_allgather.cc
- test/mpi/test_alltoall.cc
- test/mpi/test_bcast.cc
- test/mpi/test_mpi.h
Compute correct buf locally instead of rely on MPI.
> TEST: do local check in mpi tests

- src/components/tl/ucp/Makefile.am
- src/components/tl/ucp/alltoallv/alltoallv.c
- src/components/tl/ucp/alltoallv/alltoallv.h
- src/components/tl/ucp/alltoallv/alltoallv_onesided.c
- src/components/tl/ucp/tl_ucp_coll.c
- src/components/tl/ucp/tl_ucp_coll.h
- src/components/tl/ucp/tl_ucp_sendrecv.h
- test/mpi/main.cc
- test/mpi/test_alltoallv.cc
- test/mpi/test_mpi.cc
Adds one-sided alltoallv to TL/UCP
> TL/UCP: add onesided alltoallv

- test/mpi/main.cc
Print error and help messages only from rank 0 in ucc_test_mpi
> TEST: fix help print

- config/m4/ucx.m4
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_rcache.c
- src/components/tl/mlx5/tl_mlx5_rcache.c
- src/components/tl/sharp/tl_sharp_context.c
- src/utils/ucc_rcache.h
Fixes UCC build after change in https://github.com/openucx/ucx/pull/9441
> BUILD: fix regcache alignment

- src/components/cl/hier/allreduce/allreduce.c
homogenize between innode and intra_node
homogenize between innode and intra_node
homogenize between innode and intra_node
> CL/HIER: homogenize names

- config/m4/ucx.m4
- src/utils/ucc_parser.h
Fixes UCC build after changes in https://github.com/openucx/ucx/pull/9553
> BUILD: fix ucs parser set value

- .github/workflows/clang-tidy-nvidia.yaml
- config/m4/sharp.m4
- src/components/tl/sharp/tl_sharp.h
- src/components/tl/sharp/tl_sharp_coll.c
- src/components/tl/sharp/tl_sharp_coll.h
- src/components/tl/sharp/tl_sharp_team.c
Add support SHARP reduce_scatter collective
> TL/SHARP: Add reduce-scatter support

- .ci/Dockerfile.ngc_pytorch
- .ci/build_base_docker/Dockerfile.ngc_pytorch.base
- .ci/job_matrix.yaml
- .ci/scripts/env.sh
- .ci/scripts/run_docker.sh
- .ci/scripts/run_tests_ucc_mpi.sh
Migrated to NGC pytorch image 
Updated CUDA & Mofed, using the image that active develop
NGC pytorch is  the newest image included PyTorch & CUDA 12.3.
Added MOFED 23.10-0.5.5.0
> CI: Update CUDA, MOFED & CI image

- src/components/tl/cuda/tl_cuda_team.c
porting https://github.com/openucx/ucc/pull/908
> TL/CUDA: initialize remote cuda scratch to NULL (#908) - v1.3.x

- src/components/tl/mlx5/tl_mlx5_context.c
- src/components/tl/mlx5/tl_mlx5_team.c
> TL/MLX5: disable mcast init

- src/components/tl/mlx5/tl_mlx5_context.c
TL/MLX5: enhance error handling in mlx5 ctx
Thanks to @samnordmann for the suggestion
> TL/MLX5: enhance error handling in mlx5 ctx

- config/m4/ucx.m4
- src/utils/ucc_parser.h
Fixes build with recent UCS. Partially ported from https://github.com/openucx/ucc/pull/848
> UTIL: add parser doc V1.3.x

- src/components/cl/hier/Makefile.am
- src/components/cl/hier/cl_hier.c
- src/components/cl/hier/cl_hier.h
- src/components/cl/hier/cl_hier_coll.c
- src/components/cl/hier/cl_hier_coll.h
- src/components/cl/hier/reduce/reduce.c
- src/components/cl/hier/reduce/reduce.h
- src/components/cl/hier/reduce/reduce_2step.c
- src/components/tl/ucp/Makefile.am
- test/gtest/coll/test_reduce.cc
Moving last piece from https://github.com/openucx/ucc/pull/621
Originally implemented by @vspetrov
> CL/HIER: 2step reduce algorithm

- src/utils/ucc_component.c
- src/utils/ucc_log.h
- test/mpi/test_allgather.cc
- test/mpi/test_bcast.cc
- test/mpi/test_gather.cc
- test/mpi/test_gatherv.cc
- test/mpi/test_scatter.cc
Do correctness check of Gather and Gatherv locally.
Continues work from https://github.com/openucx/ucc/pull/884 and https://github.com/openucx/ucc/pull/789
> TEST: do local checks for gather

- src/coll_score/ucc_coll_score_map.c
- src/core/ucc_coll.c
- src/utils/ucc_coll_utils.c
- src/utils/ucc_coll_utils.h
Fixes collective trace prints if log level "trace" is used
Can print collective traces without UCX debug build
> CORE: fix colltrace print with trace log level

- src/utils/arch/aarch64/cpu.h
- src/utils/arch/cpu.h
Add Nvidia Grace CPU detection
> UTIL: add Nvidia Grace CPU detection

- src/components/tl/mlx5/Makefile.am
- src/components/tl/mlx5/mcast/p2p/ucc_tl_mlx5_mcast_p2p.c
- src/components/tl/mlx5/mcast/p2p/ucc_tl_mlx5_mcast_p2p.h
- src/components/tl/mlx5/mcast/tl_mlx5_mcast.h
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_coll.c
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_coll.h
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_context.c
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.c
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.h
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_progress.c
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_progress.h
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_rcache.c
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_rcache.h
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c
- src/components/tl/mlx5/tl_mlx5_coll.c
- src/components/tl/mlx5/tl_mlx5_coll.h
TL/MLX5: adding mcast bcast algo
> TL/MLX5: adding mcast bcast algo

- src/components/tl/mlx5/mcast/tl_mlx5_mcast.h
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_context.c
- src/components/tl/mlx5/tl_mlx5.h
- src/components/tl/mlx5/tl_mlx5_coll.c
- src/components/tl/mlx5/tl_mlx5_team.c
TL/MLX5: MCAST HCA selection and COLL score
> TL/MLX5: MCAST HCA selection and COLL score

- NEWS
> DOCS: Update NEWS for 1.3

- src/components/tl/ucp/reduce/reduce.c
> TL/UCP: fix reduce dbt description

- src/components/cl/hier/alltoall/alltoall.c
> CL/HIER: fix int overflow in alltoall

- src/components/tl/mlx5/mcast/p2p/ucc_tl_mlx5_mcast_p2p.c
- src/components/tl/mlx5/mcast/tl_mlx5_mcast.h
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_coll.c
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_progress.c
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_progress.h
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c
TL/MLX5: enhance reliability protocol in Mcast
> TL/MLX5: enhance reliability protocol in Mcast

- src/core/ucc_coll.c
Fixes ucc_collective_triggered_post for zero size collectives
> CORE: fix triggered post for zero colls

- NEWS
* DOCS: Update NEWS for 1.3
(cherry picked from commit e1b289898c910581b61c8ce5937f28394daf4eb0)
> DOCS: Update NEWS for 1.3 (#937)

- src/components/tl/mlx5/tl_mlx5_context.c
TL/MLX5: disable mcast for thread multiple
> TL/MLX5: disable mcast for thread multiple

- configure.ac
bump version after creating 1.3 release
> BUILD: bump version to 1.4.0

- src/components/tl/ucp/Makefile.am
- src/components/tl/ucp/allgather/allgather.c
- src/components/tl/ucp/allgather/allgather.h
- src/components/tl/ucp/allgather/allgather_bruck.c
- src/components/tl/ucp/allgather/allgather_sparbit.c
- src/components/tl/ucp/tl_ucp_coll.c
- src/components/tl/ucp/tl_ucp_coll.h
- src/utils/ucc_math.h
- test/gtest/coll/test_allgather.cc
Implementation on Sparbit algorithm from https://arxiv.org/pdf/2109.08751.pdf
- Allgather on could benefit from locality of large transfers
- no post steps
inspired by https://github.com/open-mpi/ompi/blob/main/ompi/mca/coll/base/coll_base_allgather.c implementation
`mpirun -x UCC_TL_UCP_TUNE=allgather:0-inf:@4 --mca coll ^hcoll --mca coll_ucc_enable 0 -x LD_LIBRARY_PATH=/home/ikryukov/work/ucc/install/lib:/home/ikryukov/work/ucx/install/lib:$LD_LIBRARY_PATH -x UCC_CLS=basic -x UCC_TLS=ucp -x UCC_CL_BASIC_TLS=ucp -x UCC_LOG_LEVEL=info -np 16 ./install/bin/ucc_test_mpi -c allgather --teams world`
> TL/UCP: Allgather Sparbit algorithm

- src/components/base/ucc_base_iface.c
- src/components/tl/ucp/tl_ucp.c
> TL/UCP: BASE: Minor typo corrections

- src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
Fix work buffers initialization in reduce scatter knomial
> TL/UCP: fix wbuf init in rs knomial

- test/mpi/main.cc
Return non zero exit status if user provided argument is not valid
> TEST: return non zero status for invalid arg

- contrib/doca_urom_ucc_plugin/DOCA_UROM_README.md
Add a DOCA_UROM and DOCA_UROM plugin readme into the contrib folder of DOCA_UROM plugin
To better explain the plugin and the how to build/run
it's a markdown file with instructions and scripts of example runs.
> DOCS: Adding DOCA_UROM readme

- config/m4/configure.m4
- src/utils/ucc_parser.c
> BUILD: fix build with nvc

- src/components/tl/mlx5/alltoall/alltoall_coll.c
- src/components/tl/mlx5/tl_mlx5_team.c
Minor cleanup and add some profiling steps
> TL/MLX5: minor clean and profiler

- src/components/tl/ucp/tl_ucp_service_coll.c
TL/UCP: fix in-place for service Allgather
> TL/UCP: fix in-place for service AG

- src/core/ucc_context.c
Refactor ucc_context_destroy to safely handle service team destruction. The service team is now only destroyed after all other contexts have been cleaned up, preventing potential use conflicts.
> CORE: destroy service team last

- src/components/tl/ucp/allgather/allgather.c
- src/components/tl/ucp/allgather/allgather.h
- src/components/tl/ucp/tl_ucp_team.c
- src/components/topo/ucc_topo.h
- src/utils/ucc_coll_utils.c
- add a helper function to check for 1 PPN
- choose knomial for 1ppn & cuda memtype
- helpful when called by NCCLnet 
- for this case knomial has best performance 
- can be overwritten if needed
> TL/UCP: Knomial allgather default for cuda mem

- AUTHORS
- NEWS
> DOCS: Update NEWS for 1.4

- src/components/tl/mlx5/mcast/tl_mlx5_mcast.h
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_allgather.c
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_coll.c
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.h
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_one_sided_progress.c
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c
- src/components/tl/mlx5/tl_mlx5.c
TL/MLX5: add cuda support for zcopy mcast and some enhancement in the checks for supports
> TL/MLX5: add cuda support for zcopy mcast

- configure.ac
Update master branch version after creating v1.4.x branch
> BUILD: bump version to v1.5

- src/components/tl/ucp/Makefile.am
- src/components/tl/ucp/allgather/allgather.c
- src/components/tl/ucp/allgather/allgather.h
- src/components/tl/ucp/allgather/allgather_bruck.c
- src/components/tl/ucp/allgather/allgather_linear.c
- src/components/tl/ucp/allgather/allgather_neighbor.c
- src/components/tl/ucp/allgather/allgather_sparbit.c
- src/components/tl/ucp/tl_ucp.c
- src/components/tl/ucp/tl_ucp.h
- src/components/tl/ucp/tl_ucp_coll.c
- src/components/tl/ucp/tl_ucp_coll.h
- src/components/tl/ucp/tl_ucp_sendrecv.h
- test/gtest/coll/test_allgather.cc
Added linear algorithm implementation for allgather collective operation in the UCP .
To check and validate how a one-shot approach affects network congestion
spawns N-1 send and receive
> TL/UCP: Allgather linear

- src/components/tl/ucp/allgather/allgather_linear.c
`UCC_TL_UCP_ALLGATHER_BATCHED_NUM_POSTS=0` is a single-pass linear algorithm. 
closes internal issue: 4438823
> TL/UCP: fix allgather linear parameter

- src/components/tl/ucp/tl_ucp_context.c
- src/core/ucc_context.c
- src/core/ucc_context.h
- src/utils/ucc_log.h
- src/utils/ucc_parser.c
- src/utils/ucc_parser.h
Addin UCC_NET_DEVICES env variable to be able to set network devices for different TLs and through ucc_context_config_modify. So far only TL UCP is supported
> CORE: add ucc net devices config

- .ci/scripts/coverity.sh
> Changed to CUDA 12.9

- config/m4/compiler.m4
- config/m4/cuda.m4
- configure.ac
> BUILD: update cuda arch

- src/components/cl/hier/allgatherv/allgatherv.c
- src/components/tl/mlx5/mcast/p2p/ucc_tl_mlx5_mcast_p2p.c
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_context.c
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.c
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.h
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_progress.c
- src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c
- src/components/tl/mlx5/tl_mlx5_team.c
- src/components/tl/ucp/alltoall/alltoall_bruck.c
- src/components/tl/ucp/gather/gather_knomial.c
- src/core/ucc_context.c
- src/utils/ucc_coll_utils.c
> BUILD: fix coverity issues

- config/m4/rocm.m4
Adjusting rocm gfx targets for rocm 
The relevant gfx targets have changed since the last year
> BUILD: rocm gfx target updates

- cmake/ucc-targets.cmake.in
Fixes https://github.com/openucx/ucc/issues/1172
> BUILD: check if target exists in cmake

- src/components/cl/hier/cl_hier_context.c
- src/components/tl/self/tl_self_context.c
Fixes https://github.com/openucx/ucc/issues/1178
> CL/HIER: Fix Wlto-type-mismatch

- src/components/tl/ucp/tl_ucp_context.c
> TL/UCP: remove debug print

- config/m4/rocm.m4
Adjusting rocm gfx targets for rocm 
The relevant gfx targets have changed since the last year
> BUILD/:rocm cherrypick

- NEWS
- configure.ac
Docs / news update
Preparation for minor release and update news for previous
self explanatory
> DOCS: Update NEWS of v1.5.0 and bump version

- NEWS
v1.5.x: update NEWS in v1.5.x branch, and add v1.5.1 update
update news to recent changes
> v1.5.x: update NEWS

- test/gtest/coll/test_scatter.cc
> TEST: fix build with gcc14
