src/Makefile.am, src/api/ucc_status.h, src/core/ucc_constructor.c, src/core/ucc_global_opts.c, src/core/ucc_global_opts.h, src/core/ucc_lib.c, src/utils/ucc_compiler_def.h, src/utils/ucc_log.h, src/utils/ucc_malloc.h, src/utils/ucc_parser.h
Depends on #8 and #11 
**What?**
- ucc_constructor/ucc_destructor. Constructor just reads global options now.
- Global options definition: log_level, component path
=> UCC constructor/destructor

src/core/ucc_constructor.c, src/utils/ucc_compiler_def.h, src/utils/ucc_component.c, src/utils/ucc_log.h
**What?**
Adds utils/ucc_log.h: set of macros that define logging utils for the global UCC scope: ucc_error, ucc_info, etc. The global verbose level is controlled by UCC_LOG_LEVEL. Any component that requires its own log level (to be profiled separately when needed) should define similar macros: e.g. cl_basic_error and add separate log_component entry in the config table.
**Why?**
general purpose logging
**How?**
Using ucs logging infra
=> UCC/UTIL: Logger

configure.ac, src/Makefile.am, src/api/ucc.h, src/core/ucc_constructor.c, src/core/ucc_global_opts.c, src/core/ucc_global_opts.h, src/core/ucc_lib.c, src/core/ucc_lib.h, src/utils/ucc_compiler_def.h, src/utils/ucc_component.c, src/utils/ucc_component.h, src/utils/ucc_log.h, src/utils/ucc_malloc.h, src/utils/ucc_parser.h
**What?**
Adds implementation of the ucc_lib_config_read API. Currently the lib config table only holds the list of CLs to use. To be extended in the future.
**Why?**
API function implementation
**How?**
Using ucs_lib_config_read. The only specialty is the construction of the "full_prefix".
full_prefix for a UCC lib config is either just  (i)  "UCC_" - if not "env_prefix" is provided, or (ii) "UCC_AAA_" - where AAA is the value of "env_prefix". If user specifies env_prefix when performs ucc_lib_config_read he then can control the configuration of his UCC job specifically using set of params prefixed with UCC_<ENV_PREFIX>_ w/o affecting other UCC lib objects (potentially co-existing in the same runtime).
=> CORE: ucc_lib_config_read implementation

src/api/ucc.h, src/api/ucc_def.h
Adds extern "C" protection when c++ i used
Otherwise c++ app that uses libucc wouldn't link
=> API: protect headers for c++ usage

.github/workflows/main.yaml, src/Makefile.am, src/core/ucc_global_opts.c, src/utils/ucc_compiler_def.h, src/utils/ucc_datastruct.h, src/utils/ucc_parser.h, tools/info/Makefile.am, tools/info/build_info.c, tools/info/ucc_info.c, tools/info/ucc_info.h
Add -c option to ucc_info to print UCC config variables
CI runs ucc_info
Convenient way to print all config variables in UCC 
ucs_config_print_all_opts is used. Changes in this PR requires latest version of UCS to work properly (https://github.com/openucx/ucx/pull/5876).
config tables of UCC separated from UCX config tables
=> TOOLS: ucc info print config variables

configure.ac, src/Makefile.am, src/api/ucc.h, src/api/ucc_def.h, src/api/ucc_status.h, src/cl/ucc_cl.c, src/cl/ucc_cl.h, src/cl/ucc_cl_type.h, src/core/ucc_global_opts.h, src/core/ucc_lib.c, src/core/ucc_lib.h, src/core/ucc_version.c.in, src/utils/ucc_compiler_def.h, src/utils/ucc_component.c, src/utils/ucc_component.h, src/utils/ucc_math.h, src/utils/ucc_parser.h
**What?**
- UCC/CORE: check version compatibility during lib_init (similarly to ucp)
- API: pass handle to lib_config inti ucc_init. Not a pointer to a handle (ie pointer to a pointer)
- API: thread mode should be UCC_BIT. This way CL components may defined the mask of supported thread modes
- CORE: basic lib_init implementation:
- Check UCC_CLS: parse the requested list of CLs and check if the
corresponding dynamic objects have been successfully loaded
- Filter/select only those components that satisfy params/config
requirements
- Initialize the CL lib objects using cl_iface: init
**Why?**
Implementation of UCC API ucc_lib_init/finalize.
=> CORE: basic ucc_lib_init implementation

config/m4/ucx.m4, configure.ac, src/Makefile.am, src/cl/basic/Makefile.am, src/cl/basic/cl_basic.h, src/cl/basic/cl_basic_lib.c, src/cl/ucc_cl.c, src/cl/ucc_cl.h, src/cl/ucc_cl_log.h, src/core/ucc_lib.c, src/utils/ucc_class.h, src/utils/ucc_component.c, src/utils/ucc_component.h
- Adds CL_BASIC component: build infra, lib_init/finalize, logging
- Sets min required UCX version to 1.10
- Minor change in ucc_framework: look for libucc_*.so objects instead of ucc_*.so (prefix lib appears due to libtool usage)
UCX 1.10 contains the UCS config table changes that used by UCC.
=> UCC/CL: cl basic starting implementation

src/Makefile.am, src/api/ucc.h, src/cl/basic/cl_basic.h, src/cl/basic/cl_basic_lib.c, src/cl/ucc_cl.c, src/cl/ucc_cl.h, src/cl/ucc_cl_type.h, src/core/ucc_context.c, src/core/ucc_context.h, src/utils/ucc_parser.h
Implementation of CORE UCC functionality: ucc_context_config_read/release
Additionally added ucc_context_config_print and modify to UCC API.
context_config_print is needed both for consistency of the API and for usability (we will use it at least in ucc_info).
context_config_modify is a key functionality when user wants to tweak ctx from the code (not from the env var, use case - multiple rails hca setting). 
Note ucc_context is a combination of cl_contexts, hence ucc_context_config is a combination of the corresponding cl_context_configs. Different CL contexts will have different configuration variables. This is why some modify parameters (name, value) will only be applicable to the specific CLS. Because of that the API ucc_context_config_modify also takes a const char* string  - comma …
=> CORE: context_config_read/modify/print/release

config/module.am, configure.ac, src/cl/basic/Makefile.am, test/gtest/Makefile.am, test/gtest/core/test_lib.cc, test/gtest/core/test_lib_config.cc
Adds first set of tests for ucc_lib_config_read/modify/release and ucc_lib_init/finalize
Minimal gtest coverage for already implemented API
Straight forward gtest. The only comment: gtest binary is linked against libucc.la from ${top_builddir}/src/.libs/libucc.la. This is why in runtime ucc would search for dynamic modules in ${top_builddir}/src/.libs/ucc. So in order to have it working w/o specifying UCC_COMPONENT_PATH, i've added the config/module.am (logic borrowed from ucx) which would place all the dynamical modules into ${top_builddir}/modules and also make a symlink from that folder to ${top_builddir}/src/.libs/ucc.
=> ucc config/lib gtests

configure.ac
Make docs depends on UCX
No need to depend on UCX, when requesting only to build the doxygen spec
Disable check for UCX
=> BUILD: Fixing make docs

.github/workflows/codestyle.yaml
Change git-clang-format link from svn to github
LLVM SVN seems to be down for quite some time already
Should fix CI issues in https://github.com/openucx/ucc/pull/46 and https://github.com/openucx/ucc/pull/47
=> TEST: change git-clang-format link

.github/workflows/codestyle.yaml, config/m4/ucx.m4, configure.ac, src/Makefile.am, src/components/base/ucc_base_iface.h, src/components/cl/ucc_cl.h, src/components/cl/ucc_cl_log.h, src/components/tl/ucc_tl.c, src/components/tl/ucc_tl.h, src/components/tl/ucc_tl_log.h, src/components/tl/ucp/Makefile.am, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_context.c, src/components/tl/ucp/tl_ucp_lib.c, src/components/tl/ucp/tl_ucp_tag.h, src/core/ucc_constructor.c, src/core/ucc_global_opts.h, src/utils/ucc_compiler_def.h, src/utils/ucc_log.h, test/gtest/common/test_obj_size.cc
Adds TL Framework and interface
Adds TL/UCP lib init/finalize, context create/destroy
TLs are internal "transport" layers. Their interface is very similar to CL and it is inherited from the "base" interface (similarly to CL)
=> TL framework

src/core/ucc_lib.c, src/utils/ucc_class.h
Redefine UCC_CLASS_INIT_FUNC and UCC_CLASS_DECLARE 
Original versions of these macros in UCS define ucs_status_t as return code. It is not consistent with CL and TL implementation in which we return ucc_status_t
=> CORE: redefine ucc class functions

src/components/base/ucc_base_iface.h, src/components/cl/basic/Makefile.am, src/components/cl/basic/cl_basic.c, src/components/cl/basic/cl_basic.h, src/components/cl/basic/cl_basic_context.c, src/components/cl/basic/cl_basic_lib.c, src/components/cl/ucc_cl.h, src/components/cl/ucc_cl_log.h, src/components/tl/ucc_tl.c, src/components/tl/ucc_tl.h, src/components/tl/ucc_tl_log.h, src/components/tl/ucp/Makefile.am, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp_context.c, src/components/tl/ucp/tl_ucp_lib.c, src/core/ucc_context.c, src/core/ucc_context.h, src/core/ucc_lib.c, src/core/ucc_lib.h
Adds TL context creation/destruction logic
Core functionality
Everything is handled by CORE: 
- core ucc_lib/context queries CLs which TLs are required
- CORE allocates necessary TL libs/contexts
- CLs can then get a pointer to TL context based on type enum value
This is one of the alternative approaches (#53 ) and it is more clear, logical and convenient imo.
=> CORE: init TL contexts

configure.ac, src/Makefile.am, src/components/mc/base/ucc_mc_base.c, src/components/mc/base/ucc_mc_base.h, src/components/mc/cpu/Makefile.am, src/components/mc/cpu/mc_cpu.c, src/components/mc/cpu/mc_cpu.h, src/components/mc/ucc_mc_log.h, src/core/ucc_constructor.c, src/core/ucc_global_opts.h, src/core/ucc_lib.c, src/core/ucc_mc.c, src/core/ucc_mc.h, test/gtest/Makefile.am, test/gtest/common/test_obj_size.cc, test/gtest/core/test_mc.cc
Memory components (MC) interface to work with different kinds of memory
Provides functionality for CLs and TLs to allocate memory and perform reduce for predefined datatypes and operations.
Each MC is loadable object to avoid dependency on third party libraries (e.g. libcudart). There is exactly one instance of MC per library. Functions in core provides proxy to access each MC.
=> CORE: added memory component interface

src/components/tl/ucc_tl.c
Found when build UCC with clang. Maybe add clang build to our tests?
=> TL: fix base tl config table

src/core/ucc_context.c
estimated_num_eps/ppn were uninitialized and let to bugs in ucp init.
BugFix (found with gtest + valgrind)
=> CORE: properly init b_params for cl/tl_ctx_creat

.github/workflows/codestyle.yaml, configure.ac, src/Makefile.am, src/components/base/ucc_base_iface.h, src/components/cl/basic/Makefile.am, src/components/cl/basic/cl_basic.c, src/components/cl/basic/cl_basic_coll.c, src/components/cl/ucc_cl.h, src/components/tl/ucc_tl.h, src/components/tl/ucp/Makefile.am, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_coll.c, src/components/tl/ucp/tl_ucp_coll.h, src/components/tl/ucp/tl_ucp_context.c, src/core/ucc_coll.c, src/schedule/ucc_schedule.c, src/schedule/ucc_schedule.h, src/ucc/api/ucc.h, src/ucc/api/ucc_def.h, src/utils/ucc_compiler_def.h, src/utils/ucc_list.h, src/utils/ucc_mpool.h, test/mpi/Makefile.am, test/mpi/test_mpi.c, test/mpi/test_mpi.h, test/mpi/test_mpi_barrier.c
Implements ucc_collective_init/post/test/finalize
Core API
Firstly, the ucc_coll_req_t is defined in ucc_def.h to have ucc_status_t status field. All the internally allocated requests (during collective_init) will inherit from ucc_coll_req_t. Then ucc_collective_test is just inline "status == UCC_OK".
Second: we define ucc_coll_task_t and ucc_schedule_t. Both eventually inherit from ucc_coll_req_t. So both task and schedule can be used as user request. Why? - because, in case of, for example, basic CL we don't need any complicated schedules and might want to have as thin layer as possible on top of TL UCP (returning tl_ucp-task_t to user). At the same time we can still build schedules (both at CL and TL levels) and use them with the same interface.
Thirdly, to reduce number of branches in …
=> Collective init

.clang-tidy, .github/workflows/clang-tidy.yaml, src/core/ucc_lib.c
Additional CI check that build UCC with clang and runs clang-tidy
clang-tidy is open source linter performing static code analysis. Here what it was able to find with current codebase
https://gist.github.com/Sergei-Lebedev/96141700ddd9de008802602c32ba780f
Warnings looks relevant
Github actions runs clang build and clang-tidy
=> TEST: clang build and clang-tidy

src/components/mc/cuda/mc_cuda.c
Update memory type detection in CUDA memory component  
cudaMemoryTypeUnregistered is a catchall category for any pointer CUDA doesn't know about. We also need to check for possible errors.
=> CORE: update memory type detection in CUDA memory component 

src/components/cl/basic/cl_basic_context.c, src/components/cl/basic/cl_basic_lib.c, src/components/cl/ucc_cl.c, src/components/cl/ucc_cl.h, src/components/mc/cpu/mc_cpu.c, src/components/tl/ucc_tl.c, src/components/tl/ucc_tl.h, src/components/tl/ucp/tl_ucp_addr.c, src/components/tl/ucp/tl_ucp_context.c, src/components/tl/ucp/tl_ucp_ep.c, src/components/tl/ucp/tl_ucp_lib.c, src/core/ucc_coll.c, src/core/ucc_constructor.c, src/core/ucc_context.c, src/core/ucc_lib.c, src/utils/ucc_class.h, src/utils/ucc_component.c
Fixes clang-tidy warnings
Some functions are marked with NOLINT to suppress warnings because those functions are not fully implemented or not implemented at all
=> TEST: fix clang-tidy warnings

src/Makefile.am, src/components/base/ucc_base_iface.h, src/components/cl/basic/cl_basic_context.c, src/components/cl/ucc_cl.c, src/components/cl/ucc_cl.h, src/components/tl/ucc_tl.c, src/components/tl/ucc_tl.h, src/components/tl/ucp/Makefile.am, src/components/tl/ucp/barrier/barrier.c, src/components/tl/ucp/barrier/barrier.h, src/components/tl/ucp/barrier/barrier_knomial.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_coll.c, src/components/tl/ucp/tl_ucp_coll.h, src/components/tl/ucp/tl_ucp_context.c, src/core/ucc_coll.c, src/core/ucc_context.c, src/core/ucc_context.h, src/core/ucc_progress_queue.c, src/core/ucc_progress_queue.h, src/core/ucc_progress_queue_st.c, src/schedule/ucc_schedule.h, src/utils/ucc_list.h, test/mpi/test_mpi_barrier.c
Implements ucc_context_progress
core api
ucc_context_progress consists of 2 parts.
- Firstly, any internal component may register a progress callback fn that it needs. For example, TL UCP needs to call ucp_worker_progress (even if there are no active tasks locally), mcast needs to check for potential NACKs in a progress etc. So, this PR adds a simple interface to register/deregister progress callbacks into core ucc_context_t.
- Secondly, the actual collective requests (implemented as schedules & tasks) are progressed on a ucc_context_t via progress_queue. This PR adds basic progress_queue interface and single threaded implementation (linked list).
- TL UCP : adds barrier fn stubs. Basically now we can run ucc_barrier test that triggers all the flow: collective_init -> CL_BASIC->TL_UCP …
=> Context progress

src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_addr.c, src/components/tl/ucp/tl_ucp_team.c
Speeds up address exchange during team creation by introducing more polling for oob allgather req. It is still non-blocking. Amount of polling is controlled with env var.
=> TL/UCP: additional polling in the addr exchange

src/Makefile.am, src/components/cl/basic/Makefile.am, src/components/mc/cpu/Makefile.am, src/components/mc/cuda/Makefile.am, src/components/tl/ucp/Makefile.am
Adding explicit dependency for each cl, tl and mc on libucc
UCC component depends on some symbols from libucc e.g. ucc_global_config. Thus in some environments ld fails to find such symbols if there is no dependency.
Build libucc first, add libadd=libucc.la in each component.
=> BUILD: add libucc dependency for cl,tl,mc

src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_coll.c, src/components/tl/ucp/tl_ucp_coll.h, src/components/tl/ucp/tl_ucp_team.c, test/gtest/common/test_ucc.cc, test/gtest/common/test_ucc.h, test/gtest/core/test_team.cc
Fixes tl/ucp team preconnect implementation. Additionally preconnect is set to 0 by-default (off). If RC TLS is used in UCP preconnect might result in O(N^2) RC QPs connection and will have a significant impact on the team create cost. Functionality is still used by some applications - it can be enabled manually there.
Need to complete actual p2p to guarantee a ucp wireup. 
Preconnected is implemented as pairwise exchange with 0 len messages.
=> Tl ucp preconnect fix

src/components/tl/ucp/tl_ucp_addr.c, src/core/ucc_team.c
Currently ucc_free() == free(), but in UCC sometimes we use free and sometimes ucc_free. In this PR all free() replaced with ucc_free()
=> TL/UCP: replace free with ucc_free

.github/workflows/clang-tidy.yaml, .github/workflows/codestyle.yaml
Use specific clang version for tests
In gh actions we use latest available clang, clang-format and clang-tidy. It's not reliable because clang upstream changes might cause fails in ucc ci scripts. In this PR clang version is set to latest stable clang-11
=> TEST: use specific clang version

.github/workflows/codestyle.yaml, src/components/mc/base/ucc_mc_base.h, src/components/mc/cpu/mc_cpu.c, src/components/mc/cuda/mc_cuda.c, src/components/mc/cuda/mc_cuda.h, src/components/tl/ucp/Makefile.am, src/components/tl/ucp/allgather/allgather.c, src/components/tl/ucp/allgather/allgather.h, src/components/tl/ucp/allgather/allgather_ring.c, src/components/tl/ucp/tl_ucp_coll.c, src/core/ucc_mc.c, src/core/ucc_mc.h, test/mpi/Makefile.am, test/mpi/main.cc, test/mpi/test_allgather.cc, test/mpi/test_case.cc, test/mpi/test_mpi.h
Adds ring allgather algorithm into TL/UCP + test_mpi::allgather
Also adds ucc_mc_memcpy interface which is used by the allgather and potentially will be used in other algs/tls/cls.
=> TL/UCP: allgather ring

src/core/ucc_coll.c, src/core/ucc_team.h
Do memory type detection if UCC_MEMORY_TYPE_UNKNOWN is set in coll_args.
We want to know memory type as earlier as possible to do CL, TL or algorithm selection. If user doesn't specify memory type then UCC will try to detect it in collective init.
Following collective args description in [doc](https://github.com/openucx/ucc/blob/master/docs/images/ucc_coll_args_table1.pdf)
ucc_coll_args_check_mem_type function checks if memory type is unknown and in that case uses mc detect to get memory type.
Questions:
1. The large switch can be collapsed if we move mem_type and data_type from info/info_v to src and dst in coll_args, but it requires changes in ucc_coll_args_t again.
2. For allreduce specification says that in case of inplace src.info.buffer is ignored, but src.info.mem_type and …
=> CORE: check memtype in collective init

src/components/tl/ucp/Makefile.am, src/components/tl/ucp/bcast/bcast.c, src/components/tl/ucp/bcast/bcast.h, src/components/tl/ucp/bcast/bcast_knomial.c, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_coll.c, src/components/tl/ucp/tl_ucp_coll.h, test/mpi/Makefile.am, test/mpi/buffer.cc, test/mpi/main.cc, test/mpi/test_bcast.cc, test/mpi/test_case.cc, test/mpi/test_mpi.cc, test/mpi/test_mpi.h
Knomial tree bcast algorithm in  TL/UCP
TEST/MPI/bcast
OSU Bcast (max lat), n8ppn28
msgsize | ucc | xccl | tuned
-- | -- | -- | --
1 | 4.9 | 5.27 | 6.64
2 | 4.79 | 5.16 | 8.13
4 | 4.77 | 5.09 | 8.42
8 | 4.68 | 5.23 | 8.16
16 | 4.99 | 5.16 | 8.23
32 | 4.94 | 5.02 | 8.84
64 | 5.28 | 5.56 | 9.29
128 | 6.42 | 6.79 | 10.87
256 | 7.82 | 8.43 | 13.24
512 | 8.42 | 8.9 | 14.37
1024 | 10.93 | 10.04 | 16.21
2048 | 12.05 | 12.29 | 21.16
4096 | 17.1 | 17.08 | 36.56
8192 | 24.8 | 25.75 | 55.14
16384 | 50.45 | 33.77 | 213.19
32768 | 82.18 | 55.01 | 142.74
65536 | 109.38 | 102.13 | 104.63
131072 | 190.1 | 192.68 | 205.2
262144 | 345.93 | 370.24 | 412.62
524288 | 659.53 | 725.5 | 819.11
1048576 | 1274.36 | 1250.17 | 1463.39
=> TL/UCP: bcast knomial

test/gtest/Makefile.am, test/gtest/common/test_helpers.h, test/gtest/common/test_ucc.cc, test/gtest/common/test_ucc.h, test/gtest/core/test_alltoall.cc, test/gtest/core/test_alltoallv.cc
Added gtest alltoall & alltoallv:
- single/multiple UCC teams
- covering dtypes UCC_DT_INT8..UCC_DT_FLOAT64
- runs for proc numbers: 1,3,16
- alltoallv: generates a different amount of data counts for send/recv
=> TEST: introduced alltoall[v] gtest

.github/workflows/codestyle.yaml, config/m4/nccl.m4, configure.ac, src/Makefile.am, src/components/cl/basic/cl_basic.h, src/components/cl/basic/cl_basic_coll.c, src/components/cl/basic/cl_basic_context.c, src/components/cl/basic/cl_basic_lib.c, src/components/cl/basic/cl_basic_team.c, src/components/tl/nccl/Makefile.am, src/components/tl/nccl/tl_nccl.c, src/components/tl/nccl/tl_nccl.h, src/components/tl/nccl/tl_nccl_coll.c, src/components/tl/nccl/tl_nccl_coll.h, src/components/tl/nccl/tl_nccl_context.c, src/components/tl/nccl/tl_nccl_lib.c, src/components/tl/nccl/tl_nccl_team.c, src/components/tl/ucc_tl.c, src/components/tl/ucc_tl.h, test/mpi/Makefile.am
Adding TL NCCL
TL NCCL can be used for GPU collectives
New TL has been added, it's available only if CUDA and NCCL libs are there. NCCL comm is mapped to UCC team, so each new team creates new NCCL comm. CL Basis tries to initialize NCCL TL but if it can't it simply ignores it and proceed.
=> TL/NCCL: add control path and alltoall

src/components/cl/basic/cl_basic.h, src/components/cl/basic/cl_basic_team.c, src/components/tl/ucc_tl.c, src/components/tl/ucc_tl.h
TL interface to destroy multiple teams in a non-blocking way 
We defined internal team destruction interface to be non-blocking (at least if TL/CL supports it)
=> CL/BASIC: destroy tl team multiple

src/components/base/ucc_base_iface.h, src/components/cl/basic/cl_basic_lib.c, src/components/cl/ucc_cl.h, src/core/ucc_lib.c
Makes proper CL libs filtering based on user thread mode requirement: params.thread_mode
Currently filtering is not correct and uses uninitialized cl_iface.attr.thread_mode. Works only because all our tests use THREAD_SINGLE.
cl_iface.attr is not initialized/used - removed it.
thread_mode is queried from cl lib objects.
The highest and lowest supported thread_mode is detected among all the available CL libs. Next, we first try to satisfy user requirement: ie, if at least some CL supports required thread_mode (highest_tm >= params.thread_mode) then we keep it as active thread_mode and filter out those CLs that might have lower supported tm (lowest_tm < highest_tm). If NO CL libs can support user requirement (highest_tm < params.thread_mode) then we set active thread_mode of ucc_lib to …
=> CORE: fixes CL libs filtering

src/components/mc/base/ucc_mc_base.h, src/components/mc/cpu/mc_cpu.c, src/components/mc/cpu/mc_cpu_reduce.h, src/components/mc/cuda/kernel/Makefile.am, src/components/mc/cuda/kernel/mc_cuda_reduce.cu, src/components/mc/cuda/kernel/mc_cuda_reduce_multi.cu, src/components/mc/cuda/mc_cuda.c, src/components/mc/cuda/mc_cuda.h, src/core/ucc_mc.c, src/core/ucc_mc.h, src/utils/ucc_math.h
Implementation of reduce multi for cuda memory component
Reduce multi allows to do a reduction for multiple vectors in one call hence only one kernel launch is needed. This is useful for allreduce/reduce collectives with radix greater than 2.
Reduce multi is added to base memory component interface. In CPU MC reduce multi is implemented as N calls to normal reduce.
=> MC/CUDA: reduce multi implementation

test/gtest/common/test_ucc.h, test/gtest/core/test_alltoall.cc, test/gtest/core/test_alltoallv.cc, test/gtest/core/test_barrier.cc
- Collective tests (currently barrier, alltoall, alltoallv) should
be using UccJob::getStaticTeams() instead of creating/destroying
new team for each TestFixture. Otherwise known UCX (ucp) cleanup
issue may happen which leads to memory leak.
- Disable alltoall(v) "mutliple" tests. Right now UCC (over UCP tl)
does not support this yet. Will be re-enabled once team-id
allocation feature is merged to  UCC master.
=> TEST: gtest: use static teams

src/Makefile.am, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_addr.c, src/components/tl/ucp/tl_ucp_addr.h, src/components/tl/ucp/tl_ucp_context.c, src/components/tl/ucp/tl_ucp_ep.c, src/components/tl/ucp/tl_ucp_ep.h, src/components/tl/ucp/tl_ucp_ep_hash.h, src/components/tl/ucp/tl_ucp_team.c, src/core/ucc_constructor.c, src/core/ucc_context.c, src/core/ucc_context.h, src/utils/khash.h, src/utils/ucc_proc_info.c, src/utils/ucc_proc_info.h
Changes the way ucp ep are stored in TL. Now we use a hash table located on ucc_tl_ucp_contet_t. The hash implementation is a "khash" - opensource free license MIT implementation also used by UCX. 
Storing eps on team results in huge memory leak (#108) and team create overhead doe to connect-disconnect
The key to the hash table is ucc_context_id_t structure which consists of a triplet: host_id, pid, and ucc context sequence number.
TL/UCP exchanges ucp_worker addresses + the keys during team creation (exchange during ctx create or PMIx-like iface is not yet implemented). The ep is then created only once and put into hash based on the key.
OVerheads:
1. i've measured the cost of the hash itself (implemented a simple benchmark):
1.1 for the size of the hash ~1000 the overhead to find the ep …
=> TL/UCP: endpoints hash

config/m4/ucx.m4, src/components/cl/basic/cl_basic_lib.c, src/components/tl/nccl/tl_nccl_lib.c, src/components/tl/ucc_tl.h, src/components/tl/ucp/tl_ucp_lib.c
This PR Fixes the setting of ucc_lib_attr.thread_mode of CL.
Currently thread_mode is not correct and uses uninitialized cl_iface.attr.thread_mode. Works only because all our tests use THREAD_SINGLE.
CL thread mode is decided according to the min thread support of all of its TLs. Each TL has its own get_lib_attributes method, which include thread_mode.
=> COMPONENTS: Fix Thread Mode Query

src/Makefile.am, src/components/mc/cuda/mc_cuda.c, src/components/mc/cuda/mc_cuda.h, src/components/tl/nccl/tl_nccl_context.c, src/components/tl/ucp/tl_ucp_context.c, src/core/ucc_context.h, src/core/ucc_progress_queue.c, src/core/ucc_progress_queue_mt.c, src/schedule/ucc_schedule.c, src/schedule/ucc_schedule.h, src/utils/ucc_atomic.h, src/utils/ucc_compiler_def.h, src/utils/ucc_datastruct.h, src/utils/ucc_list.h, src/utils/ucc_mpool.c, src/utils/ucc_mpool.h, src/utils/ucc_parser.h, src/utils/ucc_spinlock.h, test/mpi/main.cc, test/mpi/test_mpi.cc, test/mpi/test_mpi.h
Implements MT ucc_context_progress 
Core API
In a multi-threaded environment, where we have multiple threads inserting and progressing collective requests to the progress_queue, we need a thread safe data structure.
Here we use double array structure where all new tasks inserted to the primary array and old tasks to the secondary. tasks are being extracted only from the primary array. when primary is empty, they switch roles. All insertions & deletions are performed with atomic operations.
=> CORE: Add Multi-threaded context progress queue

src/components/mc/cuda/mc_cuda.c, src/components/mc/cuda/mc_cuda.h
fix mc/cuda env vars setting
ucc_info -c crashes with segv
add [LAST] = NULL to enum names array
=> MC/CUDA: fix parser segv

src/schedule/ucc_schedule.c
Set task flags to zero.
Undefined task flags leads to double finalize
=> CORE: set default task type

src/components/tl/nccl/tl_nccl_coll.c
Fixes allreduce run with NCCL
Don't use dst type. For allreduce it is always in src. (user might not set dst.info.datatype)
=> TL/NCCL: fix allreduce type check

src/components/mc/cuda/kernel/mc_cuda_wait_kernel.cu, src/components/mc/cuda/mc_cuda.c, src/components/mc/cuda/mc_cuda.h
Fixes race condition between cuda kernel and cpu thread, when new ee wait request might grab inprogress wait request from memory pool
CPU waits for kernel to finish before returning wait request back to memory pool
=> MC/CUDA: wait for ack from cuda wait task

test/gtest/Makefile.am, test/gtest/common/test.h, test/gtest/common/test_ucc.cc, test/gtest/common/test_ucc.h, test/gtest/core/test_allgather.cc, test/gtest/core/test_allgatherv.cc, test/gtest/core/test_allreduce.cc, test/gtest/core/test_alltoall.cc, test/gtest/core/test_alltoallv.cc, test/gtest/core/test_bcast.cc
- Added collectives:
- allgather
- allgatherv
- allreduce (will be available after merge https://github.com/openucx/ucc/pull/95, due to common code)
- bcast
- Added CUDA for all collectives
- Added `inplace` option support
=> TEST: gtest extended collectives tests

src/core/ucc_team.c, src/core/ucc_team.h, test/gtest/common/test_ucc.cc, test/mpi/test_mpi.cc
Makes ucc_team_destroy non-blocking. User now has to call this fn in a loop checking return status. E.g.:
```
while (UCC_INPROGRESS == (status = ucc_team_destroy(team))) {
if (UCC_OK != status) {
/* handle error */
break;
}
/* runtime progress could be there */
} 
```
According the API Spec change #74 
@Sergei-Lebedev need to update Torch UCC PG when this change is merged.
=> CORE: ucc_team_destroy nb implementation

test/mpi/test_mpi.cc
Fixes uninitialized value - potential crash in ucc_test_mpi finalize flow.
When oob.participants is not initialized mem corruption may happen.
=> TEST: test mpi oob.participants

src/coll_score/ucc_coll_score.c, src/components/base/ucc_base_iface.c, test/gtest/coll_score/test_score_str.cc
Changes separator character in UCC_*_COLL_SCORE parsing from ";"
to "#". The reason is that some runtimes (MPIs, e.g. OpenMPI)
incorrectly parse ";" token. W/o that change one has to always use
quote marks to guard the string.
This is just minor usability improvement.
=> CORE: change COLL_SCORE separator

src/coll_score/ucc_coll_score.c, src/components/base/ucc_base_iface.c, test/gtest/coll_score/test_score_str.cc
=> V0.1.x: CORE: change SCORE separator

test/mpi/Makefile.am
Fixes build with cuda:
```bash
...
04:39:16  In file included from /opt/nvidia/torch-ucc/src/ucc/test/mpi/mpi_util.h:9,
04:39:16                   from /opt/nvidia/torch-ucc/src/ucc/test/mpi/mpi_util.cc:7:
04:39:16  /opt/nvidia/torch-ucc/src/ucc/test/mpi/test_mpi.h:21:10: fatal error: cuda.h: No such file or directory
04:39:16   #include <cuda.h>
04:39:16            ^~~~~~~~
...
```
=> TEST: fixed mpi test build with cuda

test/mpi/test_allgather.cc, test/mpi/test_allgatherv.cc, test/mpi/test_allreduce.cc, test/mpi/test_alltoall.cc, test/mpi/test_alltoallv.cc, test/mpi/test_bcast.cc, test/mpi/test_case.cc, test/mpi/test_mpi.h
If the UCC returns that something is not supported, these tests are flagged as skipped. In this case, updating tests won't be required if UCC starts supporting something.
=> TEST: MPI: fixes tests skipping

src/components/mc/cpu/mc_cpu.c, src/components/mc/cuda/mc_cuda.c, test/mpi/test_mpi.cc
Don't initialize cuda memory component if there are no cuda devices.
Set component name for logger
fixing #163
=> MC/CUDA: check device count

src/components/tl/ucp/alltoall/alltoall.c, src/core/ucc_coll.c
Decrease logging level of the ucc coll_init flow from "error" to "debug" for UCC_ERR_NOT_SUPPORTED
Runtime can handle UCC_ERR_NOT_SUPPORTED (e.g. MPI would fallback
to another coll component). Don't spam the output with the error messages.
=> CORE: dbg log level for "unsupported"

Makefile.am, config/m4/mpi.m4, configure.ac, src/utils/ucc_coll_utils.h, tools/perf/Makefile.am, tools/perf/ucc_perftest.cc, tools/perf/ucc_perftest.h, tools/perf/ucc_pt_benchmark.cc, tools/perf/ucc_pt_benchmark.h, tools/perf/ucc_pt_bootstrap.h, tools/perf/ucc_pt_bootstrap_mpi.cc, tools/perf/ucc_pt_bootstrap_mpi.h, tools/perf/ucc_pt_coll.cc, tools/perf/ucc_pt_coll.h, tools/perf/ucc_pt_comm.cc, tools/perf/ucc_pt_comm.h, tools/perf/ucc_pt_config.cc, tools/perf/ucc_pt_config.h
Adding UCC internal performance tests
UCC perftest is not a replacement for other well known benchmark such as OSU, instead the goal here is to cover different usage scenarios specific for UCC such as persistent collectives, asymmetric memory type, multithreading, measuring collective bw.
ucc_perftest is compiled as a separate binary file in tools/perftest. Different backends might be used for OOB, but right now only MPI is available.
ucc_pt_benchmark - common logic for starting benchmark
ucc_pt_coll - collective abstraction for benchmarking
ucc_pt_bootstrap - OOB backend abstraction
ucc_pt_comm - ucc_lib + ucc_context + ucc_team
Running allreduce on 8 ranks with ucc_perftest and OSU with ucc coll component (using Val's MPI driver):
* UCC Perftest
```shell
Collective: Allreduce
Memory …
```
=> TOOLS/PERFTEST: ucc perftest

src/components/cl/basic/cl_basic_lib.c, src/components/tl/nccl/tl_nccl_lib.c, src/components/tl/ucp/tl_ucp_lib.c
Fill lib_attr.coll_types for CL/BASIC 
Part of the API. Used in ompi/coll/ucc component (https://github.com/open-mpi/ompi/pull/8843)
Check TL/ucp/nccl attrs
=> CL/BASIC: fill coll_types attribute

config/m4/compiler.m4, configure.ac, src/Makefile.am, src/coll_score/ucc_coll_score.c, src/components/cl/basic/Makefile.am, src/components/mc/cpu/Makefile.am, src/components/mc/cuda/Makefile.am, src/components/mc/cuda/mc_cuda.h, src/components/tl/nccl/Makefile.am, src/components/tl/nccl/tl_nccl_team.c, src/components/tl/ucp/Makefile.am, src/utils/ucc_class.h, test/mpi/Makefile.am, tools/info/Makefile.am, tools/perf/Makefile.am
- Use compiler and preprocessor flags configured from compiler.m4
- Unify flags across different components. Use BASE_CPFFLAGS, BASE_CFLAGS, BASE_CXXFLAGS as common options
- Print configure summary table
- Fix incorrect statuses (ucs_status messed up with ucc_status)
=> Cleanup build flags

src/components/tl/ucp/allgather/allgather_ring.c, src/components/tl/ucp/allgatherv/allgatherv_ring.c, src/components/tl/ucp/allreduce/allreduce_knomial.c, src/components/tl/ucp/alltoall/alltoall_pairwise.c, src/components/tl/ucp/alltoallv/alltoallv_pairwise.c, src/components/tl/ucp/barrier/barrier_knomial.c, src/components/tl/ucp/bcast/bcast_knomial.c, src/core/ucc_coll.c, src/core/ucc_progress_queue_mt.c, src/core/ucc_progress_queue_st.c, src/schedule/ucc_schedule.h, src/ucc/api/ucc.h, src/ucc/api/ucc_def.h, test/gtest/core/test_barrier.cc
According to the decision made in WG: Adds the API option to set completion callback for ucc_coll_args_t. 
Used to implement the support for non-blocking collectives in OpenMPI coll/ucc driver (other use-cases also possible): https://github.com/vspetrov/ompi/tree/coll_ucc_v2 . It used to handle ompi/ucc requests allocation/progress/signalling.
User can set UCC_COLL_ARGS_FIELD_CB flag to coll_args and pass a callback function which is invoked upon collective completion. The only UCC api allowed from the callback is ucc_collective_finalize.
=> API: completion callback

test/gtest/common/test.h, test/gtest/common/test_ucc.h, test/gtest/core/test_allgather.cc, test/gtest/core/test_allgatherv.cc, test/gtest/core/test_allreduce.cc, test/gtest/core/test_alltoall.cc, test/gtest/core/test_alltoallv.cc, test/gtest/core/test_bcast.cc
in gtest: Invoke EXPECT_EQ macro only on the result of data_validate
If the data validation failed in gtest the output would be totally clogged due to EXPECT_EQ failure for every position in a buffer.
=> TEST: reduce amount of err output

src/Makefile.am, src/components/base/ucc_base_iface.h, src/components/cl/basic/cl_basic_context.c, src/components/cl/basic/cl_basic_lib.c, src/components/cl/ucc_cl.c, src/components/cl/ucc_cl.h, src/components/tl/ucc_tl.c, src/components/tl/ucc_tl.h, src/core/ucc_lib.c, src/core/ucc_lib.h, src/core/ucc_team.c, src/utils/ucc_parser.c, src/utils/ucc_parser.h
Now TLs are black boxes discovered in runtime and accessed via  component->name. CLs define the required TLs via
ucc_config_names_array (registered with parser) instead of tl_type_t bits.
This is the first PR the allows 3rd parties to create dynamically loadable TL plugins w/o ANY code integration into UCC.
TLs are accessed via the "name" key which is part of .so tl library. No more "ucc_tl_type_t" that would require integration into ucc code.
=> CORE: remove ucc_tl_type_t

src/components/cl/basic/cl_basic.c, src/components/cl/basic/cl_basic.h, src/components/cl/basic/cl_basic_context.c, src/components/cl/basic/cl_basic_team.c, src/components/cl/ucc_cl.c, src/core/ucc_context.c, src/core/ucc_context.h, src/utils/ucc_component.c, src/utils/ucc_component.h, test/gtest/core/test_context_config.cc
All CLs (even though we have only 1 at the moment  - basic) have the parameter UCC_CL_BASIC_TLS which defines the TLS the given CL requires. It can be ALL which is set to default for BASIC. CL/BASIC will try to use ALL tls specified with this variable (can be controlled). The logic of tl context/team/score creation in CL/BASIC is unified. 
After that change any 3rd party TL plugin (.so) can be just distributed separately and will be enabled via CL basic OOB according to default scoring settings.
=> CL/BASIC: use ALL available TLs by default

src/core/ucc_context.c
Adds ucc core context configuration to the global config list
Otherwise it is not listed in ucc_info
=> CORE: register ucc ctx config table

src/components/tl/ucp/allreduce/allreduce.c, src/components/tl/ucp/allreduce/allreduce.h, src/components/tl/ucp/allreduce/allreduce_knomial.c, src/components/tl/ucp/tl_ucp_service_coll.c
Split knomial allreduce post into init and post. Init function allocates memory.
1. In case of triggered post cuda malloc might hang if wait kernel is running, we can do allocation earlier in init and free it in finalize to avoid deadlock
2. For persistent collectives we don't need to allocate/free scratch space on each collective post, instead do it just once in init/finalize.
=> TL/UCP: knomial allreduce move memory allocation from post to init

tools/perf/Makefile.am, tools/perf/ucc_perftest.cc, tools/perf/ucc_perftest.h, tools/perf/ucc_pt_benchmark.cc, tools/perf/ucc_pt_benchmark.h, tools/perf/ucc_pt_bootstrap.h, tools/perf/ucc_pt_bootstrap_mpi.cc, tools/perf/ucc_pt_bootstrap_mpi.h, tools/perf/ucc_pt_coll.cc, tools/perf/ucc_pt_coll.h, tools/perf/ucc_pt_coll_allgather.cc, tools/perf/ucc_pt_coll_allgatherv.cc, tools/perf/ucc_pt_coll_allreduce.cc, tools/perf/ucc_pt_coll_alltoall.cc, tools/perf/ucc_pt_coll_alltoallv.cc, tools/perf/ucc_pt_coll_barrier.cc, tools/perf/ucc_pt_coll_bcast.cc, tools/perf/ucc_pt_comm.cc, tools/perf/ucc_pt_comm.h, tools/perf/ucc_pt_config.cc, tools/perf/ucc_pt_config.h
in ucc_perftest added support for:
- allgather, alltoall, broadcast, barrier
- different memory types
- different datatypes
- set esimated num eps and ppn
=> TOOLS: adding more options to perftest

src/components/cl/basic/cl_basic.h, src/components/cl/basic/cl_basic_lib.c
Query all TLs when building CL/BASIC lib attributes.
CL Basic now (after #191 ) can operate with arbitrary TLs found in runtime. New TLs that will be added later (e.g. sharp, dpu) will not need to modify this function any more.
=> CL/BASIC: generalize get_lib_attr

.ci/scripts/build_ucc.sh, Makefile.am, test/mpi/Makefile.am
Currently mpi is hardcoded in mpi tests instead we can use paths found during configure steps.
=> TEST: build mpi tests if mpi found

src/components/base/ucc_base_iface.h, src/components/cl/basic/cl_basic.c, src/components/cl/basic/cl_basic_context.c, src/components/cl/basic/cl_basic_lib.c, src/components/cl/ucc_cl.h, src/components/tl/nccl/tl_nccl.c, src/components/tl/nccl/tl_nccl_context.c, src/components/tl/nccl/tl_nccl_lib.c, src/components/tl/ucc_tl.h, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp_context.c, src/components/tl/ucp/tl_ucp_lib.c, src/core/ucc_context.c, src/core/ucc_context.h, src/ucc/api/ucc.h, src/ucc/api/ucc_def.h, src/utils/ucc_component.c, src/utils/ucc_component.h, src/utils/ucc_math.h, test/gtest/core/test_context.cc, test/gtest/core/test_context.h
Implements ucc_context_get_attr with UCC_CONTEXT_ATTR_FIELD_CTX_ADDR flag.
CORE API. It serves 2 purposes:
1. User can use PMIx-like (key-value storage) method for UCC address exchange.
2. Internally this will unify the address-exchange of different TLs. E.g. currently TL/UCP and TL/NCCL use 2 separate allgathers to collect addressing info. We will be able to move that to 1 common place in CORE team create (or ctx create if it has oob): we will query the TLs addresses and pack the data, do allgather once and then each TL will extract its own part of address. Additional data will be later added to the packed address: e..g ctx id hash (used for ep hash in tl/ucp currently); generic process info (bound socket/numa/core number, pid, nodename/nodehash) - will be used for hierarchical CL.
The …
=> UCC context address query

src/schedule/ucc_schedule.h
Finalize task AFTER calling the callback
Otherwise crash in the CB will happen
=> CORE: bugfix in ucc_task_complete

src/Makefile.am, src/core/ucc_progress_queue.h, src/core/ucc_progress_queue_mt.c, src/schedule/ucc_schedule.c, src/schedule/ucc_schedule.h, src/utils/ucc_atomic.h, src/utils/ucc_lock_free_queue.h, test/gtest/Makefile.am, test/gtest/utils/test_lock_free_queue.cc
Fix bug in MT progress queue. In addition, move to Utils and add gtests.
Hang while using mt progress queue after PR 125
Create locked queue per pool instead of global. Also, organize the structs in a more accurate way.
In addition, remove counters (seems like only hurt performance) - add unnecessary actions per call. When empty, dequeue func simply finish the iteration.
=> CORE: Fix MT progress queue

test/gtest/common/test_ucc.h, test/gtest/core/test_allgather.cc, test/gtest/core/test_allgatherv.cc, test/gtest/core/test_allreduce.cc, test/gtest/core/test_alltoall.cc, test/gtest/core/test_alltoallv.cc, test/gtest/core/test_bcast.cc, test/mpi/buffer.cc, test/mpi/test_allgather.cc, test/mpi/test_allgatherv.cc, test/mpi/test_allreduce.cc, test/mpi/test_alltoall.cc, test/mpi/test_alltoallv.cc, test/mpi/test_bcast.cc, test/mpi/test_case.cc, test/mpi/test_mpi.h, tools/perf/ucc_perftest.h, tools/perf/ucc_pt_coll_allgatherv.cc, tools/perf/ucc_pt_coll_alltoallv.cc
Changed unnecessary mc allocation to ucc_malloc in tests.
To reduce mc usage unless needed.
Any place in tests that called ucc_mc_alloc with UCC_MEMORY_TYPE_HOST directly was changed to ucc_malloc.
=> TEST: fix ucc allocations

src/components/mc/base/ucc_mc_base.h, src/components/mc/cpu/mc_cpu.c, src/components/mc/cuda/mc_cuda.c, src/components/tl/ucp/tl_ucp.c, src/core/ucc_coll.c, src/core/ucc_mc.c, src/core/ucc_mc.h, test/gtest/core/test_mc_cuda.cc
- Removed ucc_mc_type function since it is a duplication of ucc_mem_query
- Added docs for some functions in mc
- Changed log level for cuMemGetAddressRange to make it less verbose. It was producing following output for cpu alltoall
```
tc=Alltoall team=world mtype=host msgsize=8
[1622199941.339627] [swx-dgx04:67160:0]         mc_cuda.c:353  cuda mc ERROR cuMemGetAddressRange(0x8abb730) error: 500(no error)
[1622199941.340636] [swx-dgx04:67160:0]         mc_cuda.c:353  cuda mc ERROR cuMemGetAddressRange(0x9276110) error: 500(no error)
[1622199941.340665] [swx-dgx04:67161:0]         mc_cuda.c:353  cuda mc ERROR cuMemGetAddressRange(0x91046c0) error: 500(no error)
tc=Alltoall team=world mtype=host msgsize=64
[1622199941.342563] [swx-dgx04:67160:0]         mc_cuda.c:353  cuda mc ERROR …
```
=> MC: cleanup interface

src/components/mc/cpu/mc_cpu.c, src/components/mc/cuda/mc_cuda.c, src/components/tl/ucp/allreduce/allreduce_knomial.c, src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c, src/core/ucc_mc.c, src/core/ucc_mc.h, test/gtest/core/test_allgather.cc, test/gtest/core/test_allgatherv.cc, test/gtest/core/test_allreduce.cc, test/gtest/core/test_alltoall.cc, test/gtest/core/test_alltoallv.cc, test/gtest/core/test_bcast.cc, test/gtest/core/test_mc.cc, test/gtest/core/test_mc_cuda.cc, test/gtest/core/test_mc_reduce.h, test/mpi/buffer.cc, test/mpi/test_case.cc, tools/perf/ucc_pt_coll_allgather.cc, tools/perf/ucc_pt_coll_allgatherv.cc, tools/perf/ucc_pt_coll_allreduce.cc, tools/perf/ucc_pt_coll_alltoall.cc, tools/perf/ucc_pt_coll_alltoallv.cc, tools/perf/ucc_pt_coll_bcast.cc
Save memory type info to ucc_mc_buffer_header_t
* simplify ucc_mc_free function
* fix bug in mpi tests
```
tc=Allreduce team=world msgsize=262144 inplace=0 dt=float64 op=max
tc=Allreduce team=world msgsize=2097152 inplace=0 dt=int32 op=sum
*** UCC TEST FAIL: ucc_mc_free(check_sbuf_mc_header, mem_type)
[1623745418.771668]          mc_cuda.c:340  cuda mc ERROR failed to free mem at 0x47db4b0, cuda error 1(invalid argument)
```
=> MC: save memtype in header

src/components/mc/cpu/mc_cpu.c, src/components/mc/cpu/reduce/mc_cpu_reduce.h, src/components/mc/cpu/reduce/mc_cpu_reduce_double.c, src/components/mc/cpu/reduce/mc_cpu_reduce_float.c, src/components/mc/cpu/reduce/mc_cpu_reduce_int16.c, src/components/mc/cpu/reduce/mc_cpu_reduce_int32.c, src/components/mc/cpu/reduce/mc_cpu_reduce_int64.c, src/components/mc/cpu/reduce/mc_cpu_reduce_int8.c, src/components/mc/cpu/reduce/mc_cpu_reduce_uint16.c, src/components/mc/cpu/reduce/mc_cpu_reduce_uint32.c, src/components/mc/cpu/reduce/mc_cpu_reduce_uint64.c, src/components/mc/cpu/reduce/mc_cpu_reduce_uint8.c
Remove unnecessary  dt param from ucc_mc_cpu_reduce_multi_* functions
Fix clang-tidy warnings
```
reduce/mc_cpu_reduce_uint16.c:12:64: warning: parameter 'dt' is unused [misc-unused-parameters]
ucc_datatype_t     dt,
```
=> MC/CPU: remove unnecessary dt param

tools/perf/ucc_pt_benchmark.cc
Fixing number of iterations in perftest and check for zero before division.
=> TOOLS: fixing warmup in perftest

src/schedule/ucc_schedule.c
Since schedule is a task need to call task_complete function for it.
Fixing bug when callback function is not called after collective complete
=> CORE: call task complete for schedule

src/components/mc/cuda/kernel/mc_cuda_reduce.cu, src/components/mc/cuda/kernel/mc_cuda_reduce_multi.cu, src/components/mc/cuda/mc_cuda.c, src/components/mc/cuda/mc_cuda.h, src/core/ucc_progress_queue_mt.c, src/core/ucc_progress_queue_st.c, src/schedule/ucc_schedule.c, src/schedule/ucc_schedule.h
Fix for #234
1. Initialize cuda stream only when it's needed for the first time, that way we guarantee that we pick correct device for stream (fixing cuda error)
2. Introduce error event handler and UCC_EVENT_ERROR to propagate error from individual task to schedule (fixing infinity progress after error)
=> MC/CUDA: init stream on demand

src/components/mc/cuda/mc_cuda.h
Fixes build on CentOS 8 + GCC8.3.1
In file included from /global/home/users/valentinp/workspace/ucc/src/utils/ucc_compiler_def.h:15,
from /global/home/users/valentinp/workspace/ucc/src/utils/ucc_component.h:11,
from /global/home/users/valentinp/workspace/ucc/src/components/mc/base/ucc_mc_base.h:11,
from mc_cuda.h:10,
from mc_cuda.c:7:
mc_cuda.c: In function ‘ucc_mc_cuda_memcpy’:
/global/home/users/valentinp/workspace/ucx/build_rel/install/include/ucs/debug/log_def.h:34:13: error: ‘cuda_st’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
ucs_log_dispatch(__FILE__, __LINE__, __func__, \
^~~~~~~~~~~~~~~~
In file included from mc_cuda.c:7:
mc_cuda.h:141:21: note: ‘cuda_st’ was declared here
cudaError_t cuda_st;
=> MC/CUDA: uninit warn build fix

config/m4/cuda.m4, src/components/mc/base/ucc_mc_base.h, src/components/mc/cpu/mc_cpu.c, src/components/mc/cuda/kernel/Makefile.am, src/components/mc/cuda/kernel/mc_cuda_reduce.cu, src/components/mc/cuda/kernel/mc_cuda_reduce_multi.cu, src/components/mc/cuda/mc_cuda.c, src/core/ucc_mc.c, src/core/ucc_mc.h, test/gtest/core/test_mc.cc, test/gtest/core/test_mc_cuda.cc
Fixing multiple bugs in MC:
- checking provided thread mode in ucc_mc_init, print warning if requested thread_mode is not consistent with previously used
- disabled 2 test cases in gtest because they depend on the order in which memory components were initialized
- fix fp16 switch exit
- added debug flags for nvcc host code if --enable-debug is set
=> MC: check provided thread mode

test/mpi/main.cc, test/mpi/test_allgather.cc, test/mpi/test_allgatherv.cc, test/mpi/test_allreduce.cc, test/mpi/test_alltoall.cc, test/mpi/test_alltoallv.cc, test/mpi/test_bcast.cc, test/mpi/test_mpi.cc, test/mpi/test_mpi.h
Fixes ucc_test_mpi hangs observed in nightly MTT 
When UCP is used via TL/UCP and rndv zcopy get is triggered the receiver might complete before sending ATS ACK to sender. If ucp_worker_progress is not called it will cause a hang on the sender. @bureddy this is the example i ment during last talk.
1. When performing test::check() via MPI we have to progress UCC
context. This is because some other process might still be inside
UCC RNDV send in the UCP/TL
2. When creating ucc_team we need to progress runtime p2p that
implements OOB.
=> TEST/MPI: fixes hangs

src/components/tl/ucp/alltoallv/alltoallv_pairwise.c, src/components/tl/ucp/tl_ucp_sendrecv.h, test/gtest/core/test_alltoallv.cc
Don't start actual p2p operation in alltoallv if send/recv count is 0
Small perf optimization
=> TL/UCP: skip 0 count in alltoallv

src/components/tl/nccl/tl_nccl.c, src/components/tl/nccl/tl_nccl.h, src/components/tl/nccl/tl_nccl_coll.c, src/components/tl/nccl/tl_nccl_context.c, src/components/tl/nccl/tl_nccl_team.c
Use cudastreamwritevalue to signal completion of nccl collective. If it's enabled to progress is needed for TL NCCL
=> TL/NCCL: use memops to check completion

src/components/tl/nccl/tl_nccl_coll.c, src/components/tl/nccl/tl_nccl_context.c, src/components/tl/nccl/tl_nccl_team.c
* don't create mc cuda event if memops sync is used
* enqueue memops into progress queue
* support immediate completion
=> TL/NCCL: fix event leak with memops

tools/perf/ucc_pt_benchmark.cc, tools/perf/ucc_pt_benchmark.h, tools/perf/ucc_pt_coll.cc, tools/perf/ucc_pt_coll.h, tools/perf/ucc_pt_coll_allgather.cc, tools/perf/ucc_pt_coll_allgatherv.cc, tools/perf/ucc_pt_coll_allreduce.cc, tools/perf/ucc_pt_coll_alltoall.cc, tools/perf/ucc_pt_coll_alltoallv.cc, tools/perf/ucc_pt_coll_barrier.cc, tools/perf/ucc_pt_coll_bcast.cc, tools/perf/ucc_pt_config.cc, tools/perf/ucc_pt_config.h
Extending perftest performance results output with BW information. By default disabled and can be enabled using -F cmd line option.
Example output:
```bash
Collective:             Alltoall
Memory type:            cuda
Datatype:               float32
Reduction:              N/A
Inplace:                0
Warmup:
small                 10
large                 10
Iterations:
small                 1
large                 1
Count        Size                Time, us                           Bandwidth, GB/s
avg         min         max         avg         min         max
65536      262144       76.46       72.62       82.30       24.00       25.27       22.30
131072      524288      121.82      118.44      125.04       30.13       30.99       29.35
262144     1048576      211.42      203.83 …
```
=> TOOLS: added option to print bw in perftest

Makefile.am, cmake/Makefile.am, cmake/ucc-config-version.cmake.in, cmake/ucc-config.cmake.in, cmake/ucc-targets.cmake.in, configure.ac
This PR makes the installation script writes cmake config files to `${prefix}/lib/cmake/ucc` so that cmake projects can easily find UCC installed on the system. PyTorch uses cmake, so this will be helpful for PyTorch to integrate the ucc backend to upstream.
I will add the same thing for UCX later. This PR is tested by: https://github.com/zasdfgbnm/cmake-ucx-ucc, please let me know if you want cmake testes to be included in this repository as well.
=> Add config file for cmake to find UCC on system

src/components/tl/nccl/tl_nccl.h, src/components/tl/nccl/tl_nccl_coll.c, src/components/tl/nccl/tl_nccl_context.c
In case of  memops sync task status need to be changed only during collective progress. Otherwise task might never be dequeued from progress queue
=> TL/NCCL: change task status from progress only

.github/workflows/codestyle.yaml, src/components/tl/nccl/tl_nccl_coll.c, src/components/tl/ucp/allreduce/allreduce_sra_knomial.c, src/components/tl/ucp/tl_ucp_coll.c, src/core/ucc_progress_queue_mt.c, src/core/ucc_progress_queue_st.c, src/schedule/ucc_schedule.c, src/schedule/ucc_schedule.h, test/gtest/Makefile.am, test/gtest/core/test_schedule.cc
Change the implementation of event manager to support subscription on the same event with different handlers for different parent tasks
When we will build more complex algorithms (upcoming PRs in CL/HIER, 2 lvl allreduce alg) we will have e.g. schedule of schedules: e.g., 1 sra schedule launched after another task_T. The SRA schedule subscribes to its tasks on EVENT completed but also needs to subscribe with different handler to the task_T.
=> SCHEDULE: rework listeners

.github/workflows/main.yaml, cmake/ucc-config.cmake.in, cmake/ucc-targets.cmake.in, test/cmake/CMakeLists.txt, test/cmake/main.cpp
Make improvements based on reviews from https://github.com/openucx/ucx/pull/7096
- Use `@libdir@` and `@includedir@` instead of `@prefix@/lib` and `@prefix@/include`.
- Add tests.
=> BUILD: improve cmake support

src/components/mc/base/ucc_mc_base.h, src/components/mc/cpu/mc_cpu.c, src/components/mc/cpu/reduce/mc_cpu_reduce.h, src/components/mc/cpu/reduce/mc_cpu_reduce_double.c, src/components/mc/cpu/reduce/mc_cpu_reduce_float.c, src/components/mc/cpu/reduce/mc_cpu_reduce_int16.c, src/components/mc/cpu/reduce/mc_cpu_reduce_int32.c, src/components/mc/cpu/reduce/mc_cpu_reduce_int64.c, src/components/mc/cpu/reduce/mc_cpu_reduce_int8.c, src/components/mc/cpu/reduce/mc_cpu_reduce_uint16.c, src/components/mc/cpu/reduce/mc_cpu_reduce_uint32.c, src/components/mc/cpu/reduce/mc_cpu_reduce_uint64.c, src/components/mc/cpu/reduce/mc_cpu_reduce_uint8.c, src/components/mc/cuda/kernel/mc_cuda_reduce_multi.cu, src/components/mc/cuda/mc_cuda.h, src/core/ucc_mc.c, src/core/ucc_mc.h
Switch the order between size and count parameters in ucc_mc_reduce_multi function decleration in ucc_mc.h
To fit to the order in which the function is implemeted in ucc_mc.c and in which it is called from ucc_dt_reduce_multi. 
Switched size and count.
=> MC: fixed mc reduce multi parameters order

src/components/tl/nccl/tl_nccl.h, src/components/tl/nccl/tl_nccl_coll.c, src/components/tl/nccl/tl_nccl_team.c, src/components/tl/ucp/allgather/allgather.c, src/components/tl/ucp/allgather/allgather_knomial.c, src/components/tl/ucp/allgather/allgather_ring.c, src/components/tl/ucp/allgatherv/allgatherv.c, src/components/tl/ucp/allgatherv/allgatherv_ring.c, src/components/tl/ucp/allreduce/allreduce.c, src/components/tl/ucp/allreduce/allreduce_knomial.c, src/components/tl/ucp/alltoall/alltoall.c, src/components/tl/ucp/alltoall/alltoall_pairwise.c, src/components/tl/ucp/alltoallv/alltoallv.c, src/components/tl/ucp/alltoallv/alltoallv_pairwise.c, src/components/tl/ucp/barrier/barrier_knomial.c, src/components/tl/ucp/bcast/bcast_knomial.c, src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c, src/components/tl/ucp/tl_ucp_coll.c, src/components/tl/ucp/tl_ucp_coll.h, src/components/tl/ucp/tl_ucp_service_coll.c, src/schedule/ucc_schedule.c, src/schedule/ucc_schedule.h, test/gtest/core/test_schedule.cc
Adds ucc_coll_args_t to ucc_coll_task_t and save the args during ucc_coll_task_init. Base (cl/tl) team is also cached on task (schedule).
2 reasons: 1. this logic is duplicated in every TL currently - so it is moved to the common place; 2. access to arges will be used in pipelined schedules to restart the task with custom frag settings.
=> Cache args on coll_task

.ci/job_matrix.yaml
Re-enabled UCC unit tests after GDR is disabled inside the tests 
UCC unit tests breaks the CI cluster because of a bug in GDR.
=> Enabled UCC unit tests

config/m4/configure.m4, src/components/mc/cpu/mc_cpu.c, src/components/mc/cuda/mc_cuda.c, src/components/tl/ucp/tl_ucp_coll.c, src/core/ucc_coll.c, src/utils/ucc_coll_utils.c, src/utils/ucc_coll_utils.h
Adds better logging for collective flow at CORE. Enabled with UCC_LOG_LEVEL=debug.
1 Variable now clearly shows which collectives are being called. E.g:
```
[1626684901.014276] [hpchead:4878 :0]        ucc_coll.c:155  UCC  DEBUG coll_init: team id 4 size 2 rank 1 ctx_rank 2: Alltoallv Host inplace=0 sbytes=564 rbytes=744, req 0x1383f80
[1626684901.014281] [hpchead:4878 :0]        ucc_coll.c:165  UCC  DEBUG coll_post: req 0x1383f80
[1626684901.014297] [hpchead:4878 :0]        ucc_coll.c:183  UCC  DEBUG coll_finalize: req 0x1383f80
[1626684900.868189] [hpchead:4877 :0]        ucc_coll.c:155  UCC  DEBUG coll_init: team id 4 size 2 rank 0 ctx_rank 1: Bcast Host inplace=0 root=1 bytes=8, req 0x138ff80
[1626684900.868194] [hpchead:4877 :0]        ucc_coll.c:165  UCC  DEBUG coll_post: req …
```
=> CORE: coll_init log

src/components/tl/nccl/tl_nccl_coll.c, src/components/tl/ucp/allgather/allgather_ring.c, src/components/tl/ucp/alltoall/alltoall_pairwise.c, test/gtest/core/test_allgather.cc, test/gtest/core/test_alltoall.cc, test/mpi/test_allgather.cc, test/mpi/test_alltoall.cc, tools/perf/ucc_pt_coll_allgather.cc, tools/perf/ucc_pt_coll_alltoall.cc
Changes AllGather dst.count for the number of elements in the entire dst buffer, for all ranks combined.
Changes AlltoAll dst.count & src.count for the number of elements in the entire src & dst buffers, for all ranks combined.
API Change in PR #225 
Change implementation in TL and use cases in tests.
=> Adjust AllGather, AlltoAll count

config/m4/ucx.m4, src/utils/ucc_parser.c, src/utils/ucc_parser.h
Revert #300  and Re-implement internally to keep backward bin-compat.
=> UTIL: proper fix for config_names_search

src/coll_patterns/recursive_knomial.h, src/coll_patterns/sra_knomial.h, src/components/tl/ucp/Makefile.am, src/components/tl/ucp/allgather/allgather_knomial.c, src/components/tl/ucp/allreduce/allreduce_sra_knomial.c, src/components/tl/ucp/bcast/bcast.c, src/components/tl/ucp/bcast/bcast.h, src/components/tl/ucp/bcast/bcast_sag_knomial.c, src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c, src/components/tl/ucp/scatter/scatter.h, src/components/tl/ucp/scatter/scatter_knomial.c, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_coll.c, src/components/tl/ucp/tl_ucp_coll.h, src/components/tl/ucp/tl_ucp_lib.c
Implementing Bcast SAG (Scatter & Allgather) for large messages.
Current bcast implementation is latency optimized but performs poorly for large messages.
The implementation is split into two - first scatter_knomial, in which the order of stages and the communication pattern is somewhat similar to that of ucc_tl_ucp_reduce_scatter_knomial, and in which 1/N of the message is sent to each node (original message size = N). Second is an inplace Allgather which is already implemented as part of allreduce. 
Finally, an algorithm selection logic is added in TL/UCP (similar to what is done for allreduce), to choose which implementation of bcast to use.
Bcast,   nnodes=30, ppn=32
--
msgsize | UCC, KN tree | UCC, SAG | OMPI/tuned
--|--|--|--
16384 | 42 | 41.3 | 70.23
32768 | 107.2 | 50.37 | 36.57 …
=> UCP: Implementing Bcast SAG for large messages

src/core/ucc_coll.c, src/core/ucc_lib.h, src/utils/ucc_compiler_def.h
Fixes false timed out error in torch_ucc
```
ucc_schedule.h:127  UCC  WARN  timeout 4.94066e-324 sec has expired on task 0x55dfa4e26180, team id 1 size 4 rank 2 ctx_rank 2: Bcast Host inplace=1 root=0 bytes=32768
```
=> CORE: fix coll args copy

src/core/ucc_coll.c, src/core/ucc_team.c, src/core/ucc_team.h, src/schedule/ucc_schedule.h
Adds running sequence number per ucc team.
Current use case: this significantly simplifies debug of the hanging apps (because it is easy to find late process from the log).
=> CORE: coll seq_num

src/components/tl/ucp/tl_ucp_coll.h
Duplicated ucc_tl_ucp_coll_init function declaration
=> TL/UCP: remove duplicate init declaration

src/components/tl/sharp/tl_sharp_coll.c
If sharp call completed "immediately" then mem_deregister was not called.
=> TL/SHARP: fix mem dereg

config/m4/configure.m4, src/components/cl/hier/Makefile.am, src/components/cl/hier/allreduce/allreduce.h, src/components/cl/hier/allreduce/allreduce_rab.c, src/components/cl/hier/cl_hier.c, src/components/cl/hier/cl_hier.h, src/components/cl/hier/cl_hier_coll.c, src/components/cl/hier/cl_hier_coll.h, src/components/cl/hier/cl_hier_context.c, src/components/cl/hier/cl_hier_team.c, src/components/tl/ucp/allreduce/allreduce_knomial.c, src/components/tl/ucp/tl_ucp_context.c, src/components/tl/ucp/tl_ucp_ep.c, src/components/tl/ucp/tl_ucp_ep.h, src/core/ucc_sbgp.h, src/core/ucc_topo.c, src/core/ucc_topo.h, src/utils/ucc_mpool.c
Adds the hierarchical low-latency Allreduce implemented as a sequence of innode_reduce->internode_allreduce->innode_bcast. Supports TL/SHARP as well.
Some perf numbers:
Allreduce   Latency (us), host , n32ppn40
-
msgsize, B | CL/BASIC | HIER | HIER+SHARP
--|--|--|--
4 | 15.38 | 13.48 | 11.03
8 | 15.26 | 14.9 | 12.03
16 | 15.24 | 14.72 | 11.72
32 | 16.47 | 17.65 | 13.21
64 | 18.63 | 16.34 | 14.32
128 | 23.75 | 21.55 | 18.19
256 | 25.77 | 27.92 | 22.88
512 | 32.07 | 34.42 | 23.81
1024 | 60.35 | 33.06 | 28.49
2048 | 82.8 | 37.01 | 31.88
It is still uses TL/UCP for innode reduce and bcast.
Example cmd line to use SHARP:
`nnodes=32; ppn=40; mpirun -x UCC_CL_HIER_NODE_LEADERS_SBGP_TLS=ucp,sharp   -x UCC_CL_HIER_TLS=ucp,sharp -x UCC_CL_BASIC_TLS=ucp -x UCC_CLS=basic,hier -np $((nnodes*ppn)) …
=> CL/HIER: 2LvL RAB (reduce_allreduce_bcast) Allreduce algorithm

src/components/mc/cuda/mc_cuda.h, src/components/tl/nccl/tl_nccl.h, src/components/tl/nccl/tl_nccl_team.c
Change type of completed event
ucc_mc_ee_create_event returns ucc_mc_cuda_event_t, not cudaEvent_t
=> TL/NCCL: fix completed event

.github/workflows/clang-tidy.yaml, src/components/tl/ucp/tl_ucp_context.c, src/core/ucc_context.c, src/core/ucc_sbgp.c, src/utils/ucc_proc_info.c, test/gtest/core/test_service_coll.cc, test/gtest/utils/test_ep_map.cc
Add address sanitizer to github actions and fix found errors
==32393==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fffcb365bd0 at pc 0x7fbcf957bac4 bp 0x7fffcb365a30 sp 0x7fffcb365a28
WRITE of size 8 at 0x7fffcb365bd0 thread T0
SUMMARY: AddressSanitizer: stack-buffer-overflow cl_basic_lib.c:62 in ucc_cl_basic_get_lib_attr
==35806==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new [] vs free) on 0x6030000cb8f0
0x7f966b87b31c in ucc_ep_map_from_array ../../src/utils/ucc_coll_utils.c:221
Direct leak of 66913 byte(s) in 77 object(s) allocated from:
0x7f29f3848508 in ucc_tl_ucp_get_context_attr ../../../../../src/components/tl/ucp/tl_ucp_context.c:236
0x7f29fb6e76f5 in ucc_context_pack_addr ../../src/core/ucc_context.c:817
0x7f29fb6e7b7a in ucc_context_get_attr …
=> BUILD: run gtest with asan

src/coll_score/ucc_coll_score.c, src/components/cl/hier/allreduce/allreduce_rab.c, src/components/tl/ucp/scatter/scatter_knomial.c, src/core/ucc_coll.c, src/core/ucc_context.c
Fixing following clang-tidy warnings
-  allreduce/allreduce_rab.c: 100:5: warning: 3rd function call argument is an uninitialized value [clang-analyzer-core.CallAndMessage]
- scatter/scatter_knomial.c:61:28:  warning: Value stored to 'sbuf' during its initialization is never read [clang-analyzer-deadcode.DeadStores]
- core/ucc_coll.c:314:56: warning: parameter 'ev' is unused [misc-unused-parameters]
- coll_score/ucc_coll_score.c:123:9: warning: Potential memory leak [clang-analyzer-unix.Malloc]
=> BUILD: fix clang tidy warnings

src/ucc/api/ucc.h
Update the ucc_mem_map_params structure to hold an array of addresses, lengths, hints, and constraints in order to support multiple buffers being associated with a team for collective operations. In addition, adds a n_param integer to hold the number of addresses passed in. 
Currently, the ucc_mem_map_params structure will hold a single buffer that may be attached to a team for use with collectives. It may be the case that more than one buffer may be used over a series of collectives issued by a team.
=> API: Update mem_map_params to hold multiple buffers

src/utils/ucc_coll_utils.c, test/gtest/Makefile.am, test/gtest/core/test_utils.cc
- REDUCE_SCATTERV/ALLGATHERV used incorrect dst.info.datatype
instead of info_v
- GATHER on non-root ranks: need multiply by team->size now (after
we switched to latest coll_args definition where on root the size
of dst is buffer is "total" size)
- SCATTER same as for GATHER but for root rank
- Adds gtest for all this
=> UTIL: fix coll_args_msgsize compute

src/components/tl/nccl/Makefile.am, src/components/tl/nccl/allgatherv/allgatherv.c, src/components/tl/nccl/allgatherv/allgatherv.h, src/components/tl/nccl/tl_nccl.c, src/components/tl/nccl/tl_nccl.h, src/components/tl/nccl/tl_nccl_coll.c, src/components/tl/nccl/tl_nccl_coll.h, src/components/tl/nccl/tl_nccl_team.c, test/mpi/test_allgatherv.cc
Add 2 new allgatherv algorithms in TL NCCL
* bcast based: allgatherv is split into series of broadcasts
* bcopy: run allgather with msg size equal to max size in dst.info_v.count to local scratch space and then do local copy to dst buffer
* p2p: original allgatherv in TL NCCL
Performance on 1 Node 8PPN
|allgather size, bytes                | time, us |         |         |
|----------------|:--------:|:-------:|:-------:|
|  | p2p      | bcopy   | bcast   |
| 8192           | 138.7    | 133     | 110.8   |
| 16384          | 131      | 140.5   | 104.8   |
| 32768          | 135.5    | 134.8   | 107.6   |
| 65536          | 138.1    | 141.6   | 109.7   |
| 131072         | 127.3    | 140.2   | 113.3   |
| 262144         | 133.1    | 146.8   | 124.9   |
| 524288         | 141.3    | 150 …
=> TL/NCCL: allgatherv algs bcopy and bcast

src/components/topo/ucc_topo.c
fixes 
```
libucc_cl_hier.so: undefined symbol: ucc_topo_is_single_node
```
=> TOPO: fix is single node

src/core/ucc_mc.h
Fixes
```
/src/core/ucc_mc.h:122:5: sorry, unimplemented: non-trivial designated initializers not supported
```
=> MC/CPU: init mask for cb_params

src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_context.c, src/components/tl/ucp/tl_ucp_ep_hash.h, src/components/tl/ucp/tl_ucp_sendrecv.h, src/components/tl/ucp/tl_ucp_team.c, src/core/ucc_context.c
This PR will provide the necessary communication support for one-sided collectives in the TL/UCP component.
Currently, there is support for two-sided collectives. This provides support for one-sided collectives that will map to PGAS programming models including OpenSHMEM.
=> TL/UCP: add one-sided collective support

tools/perf/ucc_pt_comm.cc
Uninit mask results in random crashes (timeout, callback, etc)
=> UTIL: fix perftest comm allreduce

autogen.sh, config/m4/tl_coll_plugins.m4, configure.ac, src/coll_score/ucc_coll_score.c, src/coll_score/ucc_coll_score.h, src/components/base/ucc_base_iface.h, src/components/tl/ucc_tl.h, src/components/tl/ucp/Makefile.am, src/components/tl/ucp/coll_plugins/example/Makefile.am, src/components/tl/ucp/coll_plugins/example/configure.m4, src/components/tl/ucp/coll_plugins/example/example.c, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_coll.h, src/components/tl/ucp/tl_ucp_lib.c, src/components/tl/ucp/tl_ucp_team.c, src/core/ucc_lib.c
PR adds the interface for the custom/closed/vendor plugins inside TL, i.e. plugin at the collective algorithm implementation level
The use case is: given the existing open source TL (TL/UCP is the most obvious example) provide a way for 3rd party implement an algorithm re-using TL/UCP resources and functionality and distribute this algorithm as a closed plug-in.
The tl level iface is provided. Added a necessary logic to the build process that searches for the plugins. The build of plugins can be enabled with "--with-tlcp", where tlcp stands for "tl collective plugin".
Example reference implementation of a TL/UCP plugin is added in components/tl/ucp/coll_plugins/example.
The development flow for the 3rd party: fork UCC repo, add a "git submodule" with the code of the plugin. The code base …
=> TL collective plugin interface

src/components/tl/ucp/alltoallv/alltoallv_pairwise.c
Fix type to get send and receive types in the context of alltoallv operations that lead to bug when the two types are not the same.
A typo led to a mix up while referring to send and receive types.
N/A
=> TL/UCP: Fix typo to get send and receive types

src/utils/ucc_mpool.c
Otherwise segv happens on uninit obj_str if some reqs are not returned to mpool
=> UTIL: fix ucs mpool v1.13.x

.gitignore, autogen.sh, config/m4/check_tls.m4, config/m4/nccl.m4, config/m4/sharp.m4, configure.ac, src/Makefile.am, src/components/tl/nccl/Makefile.am, src/components/tl/nccl/configure.m4, src/components/tl/sharp/Makefile.am, src/components/tl/sharp/configure.m4, src/components/tl/ucp/Makefile.am, src/components/tl/ucp/configure.m4
Automatic TLs discovery during build process.
new (optional) configure parameter --with-tls= to specify list of tls to build.
When 3rd party implements custom TL integration should be entirely independent from open-source upstream UCC cude, including build.
=> CORE: automatic TLs build discovery

autogen.sh
Fixes "./autogen.sh: 5: Bad substitution"
For non bash shell use $0 instead of ${BASH_SOURCE}
=> BUILD: fix autogen for non bash shell

config/m4/mpi.m4, src/components/tl/sharp/tl_sharp_coll.c, src/components/tl/ucp/tl_ucp_team.c, test/mpi/test_mpi.cc, tools/perf/ucc_pt_bootstrap_mpi.cc
IMPI/ICC may be used for perf comparison/evaluation
- When detecting MPICC/MPICXX check for mpiicc mpicpc first (mpicxx wrapper of impi uses gcc by default)
- fix compile errors thrown by ICC
=> BUILD: fixes build with intel mpi

test/mpi/test_allgather.cc, test/mpi/test_allgatherv.cc, test/mpi/test_allreduce.cc, test/mpi/test_alltoall.cc, test/mpi/test_alltoallv.cc, test/mpi/test_barrier.cc, test/mpi/test_bcast.cc, test/mpi/test_case.cc, test/mpi/test_mpi.h, test/mpi/test_reduce.cc, test/mpi/test_reduce_scatter.cc
- Always init args.coll_type of a test_case (force that by moving to constructor). Otherwise segv may happen during TestCase::str  (ucc_coll_type_str(args.coll_type)) if test_case was skipped w/o setting coll_type.
- Make MPI_Reduce_scatter_block in TestReduceScatter non-blocking to avoid potential dead-lock
- Remove check_sbuf (3 reasons: 1st it is unnecessary, 2nd it always takes 1 entry from mc mpool away, 3rd it complicates test_cases init/set/check logic).
=> TEST: mpi test fixes

NEWS
Porting PR 379 to release branch
=> DOCS: Updating NEWS (#379)

config/m4/cuda.m4, src/components/tl/cuda/Makefile.am, src/components/tl/cuda/alltoall/alltoall_ce.c, src/components/tl/cuda/tl_cuda.h, src/components/tl/cuda/tl_cuda_common.h, src/components/tl/cuda/tl_cuda_context.c, src/components/tl/cuda/tl_cuda_team.c, src/components/tl/cuda/tl_cuda_team_topo.c, src/components/tl/cuda/tl_cuda_team_topo.h, src/components/tl/cuda/tl_cuda_topo.c, src/components/tl/cuda/tl_cuda_topo.h, test/gtest/common/test_ucc.cc
Use NVIDIA Management Library (NVML) to detect GPU topology
NVML allows to understand the underlying GPU topology more precisely compared to current solution.
Check each NVLink connection to know what devices are connected. Additionally store number of links for each pair.
=> TL/CUDA: use nvml to detect topology

test/mpi/main.cc, test/mpi/test_alltoall.cc, test/mpi/test_case.cc, test/mpi/test_mpi.cc, test/mpi/test_mpi.h
Adds onesided alltoall MPI tests 
This adds the missing MPI tests that should have been included in PR #309  and #323
=> TEST/MPI: adds onesided alltoall test

src/components/tl/ucp/tl_ucp_context.c
Enable UCX active messages.
A plugin is using UCX active messages which can only be enabled if the feature is activated when calling `ucp_init()`.
N/A
=> TL/UCP: enable UCX active messages

src/ucc/api/ucc.h
Correctly specifies behavior of ucc_context_config_modify : allow modifying tl config
=> CORE: clarify ctx_cfg_modify semantics

src/ucc/api/ucc.h
=> CORE: clarify ctx_cfg_modify semantics (#403)

src/components/base/ucc_base_iface.c, src/components/base/ucc_base_iface.h, src/components/cl/basic/cl_basic_context.c, src/components/cl/basic/cl_basic_team.c, src/components/cl/hier/cl_hier_context.c, src/components/cl/hier/cl_hier_team.c, src/components/cl/ucc_cl.c, src/components/cl/ucc_cl.h, src/components/tl/cuda/tl_cuda_context.c, src/components/tl/cuda/tl_cuda_team.c, src/components/tl/nccl/tl_nccl_context.c, src/components/tl/nccl/tl_nccl_team.c, src/components/tl/sharp/tl_sharp_context.c, src/components/tl/sharp/tl_sharp_team.c, src/components/tl/ucc_tl.c, src/components/tl/ucc_tl.h, src/components/tl/ucp/tl_ucp_context.c, src/components/tl/ucp/tl_ucp_team.c, src/core/ucc_context.c, src/core/ucc_context.h, src/core/ucc_lib.c, test/gtest/core/test_context_config.cc
Our previous implementation of ucc_context_config_modify only supported modification of CL context which is very limited.
- API/ABI is kept ucc_context_config_modify is kept the same only the name of the variable is changed: used to be "const char *cls", not it is "const char *component".
- The content of it changed though: before user should have passed cl names (e.g. "basic") now it is a CL/<name> or TL/<name>, e.g. ucc_context_config_modify(cfg, "tl/ucp", "TUNE", "alltoall:@onesided"); Passing NULL to modify CORE context is still supported of course (this is used in pytorch/OMPI).
- Moves "TUNE" family of parameters from lib to context. This way it will be available for modification via ctx cfg modify.
We already have seen use case when user wants to modify UCC context programmatically …
=> Implement TL context config modify

src/components/tl/cuda/tl_cuda_topo.c, src/components/tl/cuda/tl_cuda_topo.h
Add device type field to TL CUDA topology graph.
Extend ucc_tl_cuda_topo_num_links function to support NVSwtich connected devices
=> TL/CUDA: store device type in topo graph

src/components/tl/ucp/tl_ucp_context.c, src/components/tl/ucp/tl_ucp_lib.c, src/core/ucc_lib.c, test/gtest/core/test_alltoall.cc
Fixes following warnings and leak
```
tl_ucp_lib.c:57:13: warning: Value stored to 'status' is never read [clang-analyzer-deadcode.DeadStores]
status = ucc_config_parser_fill_opts(self->tlcp_configs[i], tlcp->config.table,
```
```
core/ucc_lib.c:465:5: warning: Value stored to 'status' is never read [clang-analyzer-deadcode.DeadStores]
status = ucc_mc_finalize();
```
```
Direct leak of 4320 byte(s) in 48 object(s) allocated from:
#0 0x7f3045247c6f in __interceptor_malloc ../../../../source/gcc-10.1.0/libsanitizer/asan/asan_malloc_linux.cpp:145
#1 0x7f3045e66a9e in ucs_malloc debug/memtrack.c:313
#2 0x7f304035e794 in ucp_rkey_pack core/ucp_rkey.c:211
#3 0x7f303f955978 in ucc_tl_ucp_ctx_remote_populate ../../../../../src/components/tl/ucp/tl_ucp_context.c:430
#4 0x7f303f952f05 in …
```
=> TEST: fixes clang tidy and asan

src/components/cl/hier/Makefile.am, src/components/cl/hier/alltoall/alltoall.c, src/components/cl/hier/alltoall/alltoall.h, src/components/cl/hier/alltoallv/alltoallv.c, src/components/cl/hier/alltoallv/alltoallv.h, src/components/cl/hier/cl_hier.c, src/components/cl/hier/cl_hier.h, src/components/cl/hier/cl_hier_coll.h, src/components/cl/hier/cl_hier_team.c, src/components/topo/ucc_sbgp.c, src/components/topo/ucc_sbgp.h, src/components/topo/ucc_topo.h, src/utils/ucc_coll_utils.h, test/mpi/test_alltoall.cc
Adds implementation of 2lvl alltoallv in the CL/HIER. 
Allows splitting a2av among TLs (e.g., TL/CUDA for intranode + TL/UCP for internode)
CL/HIER allocates 2 sbgps: NODE and FULL, allocates a storage for counts/displs for 2 tasks and initializes it. Then the 2 tasks are launched concurrently.
=> CL/HIER: 2lvl alltoallv

.ci/scripts/run_tests_ucc_mpi.sh, src/components/cl/hier/Makefile.am, src/components/cl/hier/allreduce/allreduce_rab.c, src/components/cl/hier/barrier/barrier.c, src/components/cl/hier/barrier/barrier.h, src/components/cl/hier/cl_hier_team.c, src/components/tl/ucp/Makefile.am, src/components/tl/ucp/bcast/bcast.c, src/components/tl/ucp/bcast/bcast.h, src/components/tl/ucp/bcast/bcast_knomial.c, src/components/tl/ucp/fanin/fanin.c, src/components/tl/ucp/fanin/fanin.h, src/components/tl/ucp/fanout/fanout.c, src/components/tl/ucp/fanout/fanout.h, src/components/tl/ucp/reduce/reduce.c, src/components/tl/ucp/reduce/reduce.h, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_coll.c, src/components/tl/ucp/tl_ucp_reduce.h
- Adds 2lvl fanin-barrier-fanout Barrier algorithm in CL/HIER
- Adds implementations of knomial fanin and fanout in TL/UCP
- Adds CL/HIER to .CI
Enabling hierarchical barrier
TL/UCP Fanin and Fanout are implemented as calls to the knomial reduce and bcast respectively with count = 0, buffer = NULL
=> Cl/HIER: 2lvl barrier

src/components/tl/ucp/Makefile.am, src/components/tl/ucp/allreduce/allreduce_sra_knomial.c, src/components/tl/ucp/bcast/bcast_sag_knomial.c, src/components/tl/ucp/reduce_scatter/reduce_scatter.c, src/components/tl/ucp/reduce_scatter/reduce_scatter.h, src/components/tl/ucp/reduce_scatter/reduce_scatter_ring.c, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_coll.c, src/components/tl/ucp/tl_ucp_coll.h, src/components/tl/ucp/tl_ucp_context.c, src/components/tl/ucp/tl_ucp_sendrecv.h, src/utils/ucc_coll_utils.c, src/utils/ucc_coll_utils.h, test/gtest/Makefile.am, test/gtest/common/test_ucc.cc, test/gtest/core/test_reduce_scatter.cc, test/gtest/utils/test_ep_map.cc, test/mpi/test_reduce_scatter.cc
Adds implementation of bi- uni- directional ring reduce_scatterin TL/UCP
Core API. Also used as part of 3-stage allreduce.
=> TL/UCP: reduce_scatter_ring

test/mpi/test_mpi.h, test/mpi/test_reduce.cc
Adding op and dt to output string of mpi reduce test
To be able to differentiate between tests in case of failure/skipping.
=> TEST: adding op and dt to mpi_reduce_test output str

config/m4/configure.m4, src/components/tl/cuda/configure.m4, src/components/tl/nccl/configure.m4, src/components/tl/sharp/configure.m4, src/components/tl/ucp/configure.m4
TLs are autodetected, so they should add their profiling macros
automatically as well.
=> BUILD: tl profiling fix

src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_context.c, src/components/tl/ucp/tl_ucp_sendrecv.h, src/components/tl/ucp/tl_ucp_team.c
Removes the two extra data exchanges performed during one-sided context creation.  
There can be a performance improvement for context create when reducing the number of data exchanges. 
Performance difference using up to 32 nodes with 40 PPN between current master version and this PR. Times are in milliseconds:
| Number of Nodes | Master | This PR|
|-------------------------|-----------|------------|
|2|335.443|328.389|
|4|355.145|324.561|
|8|384.267|350.165|
|16|441.401|416.414|
|32|548.325|465.787|
_NOTE: one-sided memory buffers were allocated to 128 MB in order to highlight communication time._
=> TL/UCP: piggy-back data exchange for one-sided

src/components/ec/base/ucc_ec_base.h, src/components/ec/cuda/ec_cuda.c, src/components/ec/cuda/ec_cuda.h, src/components/ec/cuda/kernel/Makefile.am, src/components/ec/cuda/kernel/ec_cuda_executor.cu, src/components/ec/ucc_ec.c, src/components/ec/ucc_ec.h
Add executor interface and implement executor for CUDA EE.
Executor allows to run/offload different operations on/to execution engine 
CUDA executor is needed to correctly handle triggered operations with CUDA execution context
Add new interface to EE (required #397 ) with executor operation.
=> EE/CUDA: executor kernel

config/m4/cuda.m4, src/components/tl/cuda/tl_cuda_topo.c, src/components/tl/cuda/tl_cuda_topo.h
Support for device type detection in TL CUDA topo for older CUDA versions
Allows to use TL CUDA with CUDA 11.0 and above, currently it requires CUDA 11.4
If nvmlDeviceGetNvLinkRemoteDeviceType function is not available do the following:
If remote device doesn't have PCI id it is not supported by CUDA TL return UCC_TL_CUDA_TOPO_DEV_TYPE_LAST, otherwise it's either NVSwitch or GPU
If can get remote device handle it's GPU otherwise it's NVSwtich
=> TL/CUDA: query nvml dev type in cuda11.0

src/components/tl/ucp/tl_ucp_sendrecv.h
Fixes the ucc_tl_ucp_get_nb() to use the correct callbacks as specified by the UCP API.
Current implementation will result in incorrect execution if used for future algorithms.
=> TL/UCP: fix onesided get

config/m4/cuda.m4
Check nvmlDeviceGetNvLinkRemoteDeviceType exists in nvml.h
Fixes build with CUDA 11.3
=> BUILD: check NvLinkRemoteDeviceType is declared

src/components/tl/cuda/tl_cuda_cache.c
Fix uninitialized return status in TL CUDA cache (issue #438)
Thanks to @kingchc for finding the issue
=> TL/CUDA: fix cuda cache return status

src/components/tl/ucp/allgather/allgather_ring.c, src/components/tl/ucp/allgatherv/allgatherv_ring.c, src/components/tl/ucp/allreduce/allreduce_knomial.c, src/components/tl/ucp/alltoall/alltoall_onesided.c, src/components/tl/ucp/alltoall/alltoall_pairwise.c, src/components/tl/ucp/alltoallv/alltoallv_pairwise.c, src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c, src/components/tl/ucp/reduce_scatter/reduce_scatter_ring.c, src/components/tl/ucp/reduce_scatterv/reduce_scatterv_ring.c, src/components/tl/ucp/scatter/scatter_knomial.c, src/components/tl/ucp/tl_ucp_coll.c, src/components/tl/ucp/tl_ucp_coll.h, src/components/tl/ucp/tl_ucp_sendrecv.h, src/components/tl/ucp/tl_ucp_service_coll.c, src/components/tl/ucp/tl_ucp_team.c
Adds a set of posted/complete counters for a task using onesided collectives. 
This should make code cleaner with respect to send/recv and put/get operations.
=> TL/UCP: add union for ptp/onesided posts/completion

src/components/tl/ucp/coll_plugins/example/example.c
fix compilation error
as data structure of `ucc_tl_ucp_task_t ` changed in #429, `task->tag` is no longer valid.
`task->tag` -> `task->tagged.tag` to avoid build-time error
=> TL/UCP: bug fix

src/components/tl/cuda/tl_cuda_team.c, src/core/ucc_team.h
Proper fix for multinode team in TL/CUDA
TL/CUDA team can be created from CL/HIER over a subset of a core team. Core team can span multiple nodes but subset is on a single node.
User ucc_subset_t for single node check
=> TL/CUDA: check single node for subset

src/components/ec/cuda/ec_cuda_executor.c, src/components/tl/cuda/allgatherv/allgatherv_ring.c, src/components/tl/cuda/alltoall/alltoall_ce.c, src/components/tl/cuda/reduce_scatterv/reduce_scatterv_ring.c, src/components/tl/cuda/tl_cuda_coll.c, src/components/tl/cuda/tl_cuda_team.c, src/utils/arch/aarch64/cpu.h, src/utils/arch/x86_64/cpu.h
Removal of ucc_memory_bus_fence() in x86 and aarch64
Keeping alinged with UCS, in continuation with PR #8023
=> UTIL: removing memory_bus_fence

.ci/job_matrix.yaml
always remove docker image
after test fail docker image hold in system
cidemo have always key for it
=> TEST: always remove docker image after test

src/components/tl/cuda/allgatherv/allgatherv_ring.c, src/components/tl/cuda/reduce_scatterv/reduce_scatterv_ring.c
Fixes tl/cuda reduce_scatterv and allgatherv ring algs when they are used as part of pipeline.    
In the case of pipeline sbuf/count will be different for each frag. The same "task" object can be used for different tasks, hence need to update buf/counts on start.
Move buf/counts initializations to "start" instead of init.
=> TL/CUDA: rsv/agv restart

src/components/tl/ucp/reduce/reduce.c, src/components/tl/ucp/reduce/reduce_knomial.c
Fixing reduce knomial avg pre op.
Correctness.
Adding pre op avg division, in the case where single process doesnt take part in first iteration reduction.
=> TL/UCP: reduce_kn avg pre op fix

src/components/tl/ucp/allreduce/allreduce_knomial.c
Fix - Adding return in case of reduction error in allreduce knomial
=> TL/UCP: add error return in allreduce kn

.ci/scripts/run_tests_ucc_mpi.sh, src/coll_score/ucc_coll_score.c, src/components/cl/hier/Makefile.am, src/components/cl/hier/allreduce/allreduce.c, src/components/cl/hier/allreduce/allreduce.h, src/components/cl/hier/allreduce/allreduce_rab.c, src/components/cl/hier/allreduce/allreduce_split_rail.c, src/components/cl/hier/alltoallv/alltoallv.c, src/components/cl/hier/barrier/barrier.c, src/components/cl/hier/cl_hier.c, src/components/cl/hier/cl_hier.h, src/components/cl/hier/cl_hier_coll.c, src/components/cl/hier/cl_hier_coll.h, src/components/cl/hier/cl_hier_team.c, src/components/tl/nccl/allgatherv/allgatherv.h, src/components/tl/ucp/allreduce/allreduce_sra_knomial.c, src/components/tl/ucp/bcast/bcast_sag_knomial.c, src/components/tl/ucp/reduce_scatter/reduce_scatter_ring.c, src/components/tl/ucp/reduce_scatterv/reduce_scatterv_ring.c, src/components/topo/ucc_sbgp.c, src/components/topo/ucc_topo.h, src/core/ucc_team.h, src/schedule/ucc_schedule.c, src/schedule/ucc_schedule.h, src/schedule/ucc_schedule_pipelined.c
Adds 2 lvl hierarchical "split_rail" allreduce. The algorithm is 3 stages: reduce_scatterV within the NODE_SBGP, followed by PPN concurrent allreduces within the NET_SBGP (ak "rail", hence the name), followed by allgatherV within the NODE_SBGP. The algorithm is only enabled for teams with uniform PPN across the nodes. 
If allreduce is INPLACE, then the first RSV is performed from user buffer -> into scratch (allocated by CL/HIER); AR is performed from scratch -> to user dest buffer; AGV is INPLACE.
If allreduce is NOT INPLACE, then the first RST is performed from user src buffer -> into user dst buffer; AR is performed inplace in user dst buffer; AGV is INPLACE in user dst buffer as well.
Algorithm supports pipelining/fragmentation with same set of controls as SRA allreduce in TL/UCP …
=> CL/HIER: split rail allreduce

src/components/tl/sharp/tl_sharp_context.c, src/core/ucc_context.c, src/core/ucc_lib.c, src/core/ucc_lib.h
Changes the way CORE UCC processes failures of tl_context_create. Before the change CORE would always print warning cluttering the output. Now, we check if TL is explicitly requested by user. In that case the error is printed otherwise the error is under "Debug" log level.
TODO: we can't suppress errors coming from libsharp_coll.so @bureddy we might want to fix that in libsharp. at least allow setting log level to 0 from tl/sharp. We want to be able to test sharp availability silently.
=> CORE: suppress warn from tl ctx fail

test/mpi/test_barrier.cc
Need to call mpi_progress otherwise a hang is possible in MPI_Ssend when root will be stuck in ucc collective.
=> TEST: mpi barrier progress

src/components/tl/ucp/tl_ucp_context.c, src/components/tl/ucp/tl_ucp_ep.c, src/components/tl/ucp/tl_ucp_ep.h, src/components/tl/ucp/tl_ucp_sendrecv.h
UCP worker address can be different on each process in  runtime. Hence we can not use local worker address when getting onesided segment info -> this can lead to a memory corruption. Size of the worker address must be packed as part of TL/UCP ep address.
=> TL/UCP: correct address parsing

config/m4/cuda.m4
Adding build flag to set CUDA virtual arch and PTX generation
- compile for GPU arch not enabled by default
- reduce binary size
- reduce compilation time
Example cmd line
```
../configure --with-cuda --with-nvcc-gencode="-gencode=arch=compute_35,code=sm_35"
```
=> BUILD: add cuda arch flag

src/components/tl/cuda/Makefile.am, src/components/tl/cuda/alltoall/alltoall.c, src/components/tl/cuda/alltoall/alltoall.h, src/components/tl/cuda/alltoall/alltoall_ce.c, src/components/tl/cuda/alltoallv/alltoallv.c, src/components/tl/cuda/alltoallv/alltoallv.h, src/components/tl/cuda/alltoallv/alltoallv_ce.c, src/components/tl/cuda/tl_cuda.h, src/components/tl/cuda/tl_cuda_coll.c, src/utils/ucc_coll_utils.h
Implement TL CUDA alltoallv
Missing feature
This PR is based on existing the TL CUDA Alltoall implementation and has the following differences to support Alltoallv.
- use info_v to get correct buffer ptr, counts, displacements, etc...
- extend shared memory region to store additional info for Alltoallv, e.g., counts, displacements, for proxies to access if applicable
=> TL/CUDA: Alltoallv implementation

src/schedule/ucc_schedule.c, src/schedule/ucc_schedule.h, src/schedule/ucc_schedule_pipelined.c, src/schedule/ucc_schedule_pipelined.h
Fixes a set of bugs in the multithreaded test cases
1. Atomically increment n_completed_tasks in schedule_completed_handler since it can be called from multiple threads if the schedule consists of at least 2 independent tasks (both can be placed into the progress queue and then processed concurrently by different threads)
2. Protect pipelined_schedule_finalize handler with recursive lock. The lock is required since multiple threads can process multiple outstanding fragments of pipeline and thus update the same pipelined_schedule object. The lock must be recursive since a thread may restart fragment from the handler and re-enter it again in case of immediate completion
3. Fixes race in the ucc_task_complete when a task is part of a schedule (detailed description comment is in the code).
=> Multithreading fixes

src/utils/ucc_coll_utils.c, src/utils/ucc_coll_utils.h, test/gtest/utils/test_ep_map.cc
Adds utility to build "nested" ep_maps 
TL team can be a subset of CORE team, CORE team can be a subset of context. Core team has team->ctx_map that maps core team rank to ctx rank. TL team also has map (passed by CL via params) which maps TL team rank to CORE team rank. Nested ep_map is used to create ctx_map for TL team, to map TL team rank directly to context rank. It is used in TL/SHM.
=> UTIL: ep_map_nested

test/mpi/test_alltoallv.cc, tools/perf/ucc_pt_coll_alltoallv.cc
Set UCC_COLL_ARGS_FLAG_CONTIG_SRC_BUFFER  and UCC_COLL_ARGS_FLAG_CONTIG_DST_BUFFER for alltoallv tests
Enables TL CUDA alltoallv in ucc_test_mpi and ucc_perftest
=> TEST: enable tl cuda alltoallv tests

tools/perf/ucc_pt_benchmark.cc, tools/perf/ucc_pt_benchmark.h, tools/perf/ucc_pt_comm.cc, tools/perf/ucc_pt_comm.h
std::chrono adds ~0.5 usec of overhead which is a lot for low latency benchmarks and makes numbers inconsistent with other benchmarks (e.g. MPI osu ). Use gettimeofday based timer instead.
Same run with to timers:
1. Chrono:
```
1           4        0.94        0.80        1.26
2           8        1.04        0.86        1.44
4          16        0.96        0.82        1.27
8          32        1.03        0.86        1.40
16          64        1.28        1.10        1.70
32         128        1.52        1.30        2.04
64         256        1.25        1.03        1.38
128         512        1.36        1.09        1.48
256        1024        1.52        1.13        1.66
512        2048        2.01        1.33        2.19
1024        4096        2.87        1.64        3.23
```
2. …
=> TOOLS: fix peftest timer

src/components/cl/hier/alltoall/alltoall.c, src/components/cl/hier/alltoallv/alltoallv.c
current alltoall(v) algorithms in CL/HIER do not support INPLACE alltoall (neither do algs in TLs). Fallback.
Fixes: https://redmine.mellanox.com/issues/3046532
=> CL/HIER: inplace alltoall fallback

config/m4/cuda.m4, configure.ac
* Print nvcc gencodes in summary table after configure.
* Fix git sha print
User can tell what GPUs are supported by UCC build
=> BUILD: print cuda archs after config

src/components/tl/nccl/tl_nccl.h, src/components/tl/nccl/tl_nccl_coll.c, src/components/tl/nccl/tl_nccl_coll.h, src/components/tl/nccl/tl_nccl_team.c, test/mpi/Makefile.am, test/mpi/main.cc, test/mpi/test_case.cc, test/mpi/test_mpi.h, test/mpi/test_scatterv.cc
Adding support for UCC_COLL_TYPE_SCATTERV to TL NCCL and adding scatterv test to ucc_test_mpi
NCCL doesn't have native support for scatterv operation, implementation in TL NCCL is base on ncclSend/ncclRecv
=> TL/NCCL: add scatterv

tools/perf/ucc_pt_config.cc
Support for setting min count and max count using abbreviated form
```
ucc_perftest -c allreduce -b 1K -e 2M
```
instead of
```
ucc_perftest -c allreduce -b 1024 -e 2097152
```
=> TOOLS: use memunits in perftest

config/m4/ucx.m4, test/gtest/Makefile.am, test/mpi/Makefile.am, tools/info/Makefile.am, tools/perf/Makefile.am
Since UCS depends on UCM and UCS/UCM compatibility reasons we need to take libucm from the same place where we find libucs.
Fixes #476
=> BUILD: take libucm from user defined dir

test/mpi/main.cc
Fix parsing long option "--verbose" in ucc_test_mpi
=> TEST: fix verbose option

src/components/tl/cuda/allgatherv/allgatherv_ring.c, src/components/tl/cuda/reduce_scatterv/reduce_scatterv_ring.c
Fixes integer divide by zero exception in TL CUDA reduce scatter and allgather when count is 0
=> TL/CUDA: fix zero size rs and ag

src/components/cl/hier/alltoallv/alltoallv.c, src/components/cl/hier/cl_hier.h
Fully enable CL HIER Alltoall and Alltoallv
Enable HIER Alltoall(v) such as TL/UCP and TL/CUDA
Enabled in the code and added triggered_post_setup function in CL/HIER
=> CL/HIER: enable alltoall(v)

src/components/ec/cuda/Makefile.am, src/components/ec/cuda/ec_cuda.c, src/components/ec/cuda/ec_cuda.h, src/components/ec/cuda/ec_cuda_executor.c, src/components/ec/cuda/ec_cuda_executor_interruptible.c, src/components/ec/cuda/ec_cuda_executor_persistent.c, src/components/mc/cuda/mc_cuda.h
Use multiple streams in EC CUDA executor.
Algorithms in TL CUDA use executor for communication. While executor api supports nonblocking operations executor tasks are synchronized because interruptible executor submits them to the same stream. This PR adds multiple streams to EC CUDA and executor assigns tasks to different streams in round robin manner.
=> EC/CUDA: use multiple streams

src/components/tl/cuda/alltoallv/alltoallv_ce.c
Fix CUDA stream sync in TL/CUDA Alltoall
Application might allocate their CUDA streams for communication, UCC should honor that if provided. Similar to TL/NCCL. 
check if there is a stream/ee_context assigned in the task and use it for `cudaEventRecord ` and `cudaStreamWaitEvent `. Otherwise, use the team's internal stream.
Also move `cudaStreamWaitEvent ` before we launch executor and after SHM barrier within the team to ensure we start the A2a(v) when all remote devices are ready.
=> TL/CUDA: fix CUDA stream sync in A2a(v)

src/components/cl/basic/cl_basic.h, src/components/cl/basic/cl_basic_context.c, src/components/cl/basic/cl_basic_lib.c, src/components/cl/hier/cl_hier.c, src/components/cl/hier/cl_hier.h, src/components/cl/hier/cl_hier_context.c, src/components/cl/hier/cl_hier_lib.c, src/components/cl/hier/cl_hier_team.c, src/components/cl/ucc_cl.c, src/components/cl/ucc_cl.h, src/core/ucc_context.c, src/core/ucc_lib.c, src/core/ucc_lib.h, src/utils/ucc_component.c, src/utils/ucc_component.h, src/utils/ucc_parser.c, src/utils/ucc_parser.h, test/gtest/common/test_obj_size.cc
Changes the way UCC_TLS (and UCC_CL_BASIC/HIER_TLS and UCC_CL_HIER_<SBGP_TYPE>_TLS) is handled. It used to be ucc_config_names_array_t. Now it will be ucc_config_allow_list_t. The difference is that the new type supports NEGATE option. Ie, now user can set UCC_TLS=^sharp, which means use everything except for specified value. This is not only convenience. 
Before we had to specify the full list, e.g. UCC_TLS=cuda,ucp. However, this would be considered a list of TLs explicitly requested by user; if some TL fails to init it will cause an error output from UCC. New way allows disabling TL w/o forcing others.
PR also fixes config_names_array_merge implementation and clarifies TLs specification in CL/HIER.
=> Use UCS_ALLOW_LIST for TLS parameter

configure.ac, src/Makefile.am, src/coll_patterns/recursive_knomial.h, src/components/ec/base/ucc_ec_base.h, src/components/ec/cpu/Makefile.am, src/components/ec/cpu/ec_cpu.c, src/components/ec/cpu/ec_cpu.h, src/components/ec/cuda/ec_cuda_executor_interruptible.c, src/components/ec/cuda/kernel/ec_cuda_executor.cu, src/components/mc/ucc_mc.h, src/components/tl/ucp/allgather/allgather_knomial.c, src/components/tl/ucp/allreduce/allreduce_knomial.c, src/components/tl/ucp/reduce/reduce_knomial.c, src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c, src/components/tl/ucp/tl_ucp_coll.h, src/components/tl/ucp/tl_ucp_reduce.h, src/components/tl/ucp/tl_ucp_service_coll.c, src/utils/ucc_coll_utils.h, src/utils/ucc_dt_reduce.h
Use executor in TL UCP allreduce
Required by CL HIER split rail allreduce in order to share the same executor between multiple TLs
=> TL/UCP: use executor

tools/perf/Makefile.am, tools/perf/ucc_perftest.cc, tools/perf/ucc_perftest.h, tools/perf/ucc_pt_comm.cc, tools/perf/ucc_pt_cuda.cc, tools/perf/ucc_pt_cuda.h
Removes explicit link dependency of ucc_perftest on libcudart. Required cuda functions are loaded in runtime via dlopen.
ucc_perftest binary will be distributed as part of binary package and should work on systems with and w/o cuda.
=> TOOLS: perftest: remove cuda dep

tools/perf/Makefile.am
Fixes build of ucc_perftest due to "/usr/bin/ld: ucc_perftest-ucc_pt_cuda.o: undefined reference to symbol 'dlsym@@GLIBC_2.2.5'"
=> TOOLS: perf: fix build

src/components/base/ucc_base_iface.c, src/core/ucc_constructor.c, src/core/ucc_global_opts.c, src/core/ucc_global_opts.h, src/core/ucc_lib.c, src/utils/ucc_parser.c, src/utils/ucc_parser.h, src/utils/ucc_string.c, src/utils/ucc_string.h, test/gtest/Makefile.am, test/gtest/utils/test_cfg_file.cc, test/gtest/utils/test_string.cc, test/gtest/utils/ucc_test.conf
Adds support for configuration files with UCC parameters
Allows distribution of UCC with pre-built configuration
configuration file can contain any UCC variables in the format var = value (";" symbol in the begging of the file comments out the setting). Configuration file is searched by the library once during ucc_constructor call: firstly the env variable UCC_CONFIG_FILE is checked (it has highest precedence); if not found the default file "ucc.conf" is checked in the $HOME; if not found the default file "ucc.conf" is checked in the <ucc_install_dir>/share/ucc.conf.
Example config file:
UCC_TL_UCP_LOG_LEVEL=info
UCC_TLS=ucp
MPI_UCC_TL_UCP_KN_RADIX=3 ;; MPI_ prefix means that the var only affects UCC lib objects with "MPI" env prefix
NOTES:
why "filename" arguments from ucc_lib_confi_read …
=> CORE: config file support

tools/perf/ucc_pt_config.cc
Assign comm.mt default value
Beforehand, was throwing error unless user specified mt
=> TOOLS: assign comm.mt default value

src/utils/ucc_mpool.c
Fixes data corruption with the new mpool interface.
For small elem_sizes (e.g. in mc/cuda elem size is sizeof(ucc_mc_cuda_mpool_header_t) = 16b) setting max_chunk_size = elems_per_chunk * elem_size just seems correct. But elem_size is aligned up internally in UCS. this makes elem_size  > max_chunk_size which is not correctly handled in UCS. Setting grow_factor = 1 and max_chunk_size = SIZE_MAX fixes it and makes behaviour similar to legacy api.
=> UTIL: mpool init fix

src/core/ucc_constructor.c, src/utils/ucc_parser.c
Fixes typo memleak (strdup(name))
=> UTIL: cfg parser leak fix

src/components/topo/ucc_sbgp.c, src/components/topo/ucc_sbgp.h, src/components/topo/ucc_topo.c, src/components/topo/ucc_topo.h, src/utils/ucc_proc_info.c, src/utils/ucc_proc_info.h
Adds support for SBGP_TYPE_NUMA - the type of subgrouping that selects processes bound to the same numa domain on a node.
On some systems there can be multiple numa nodes per socket. Some collectives (e.g. in TL/SHM) will give better performance when mapped to numa subgroups.
=> UTIL: numa subgrouping

test/mpi/test_mpi.h
Initialize cuda_ec to nullptr, otherwise incorrect destroy happens
=> TEST: fixes segv in test_mpi

src/components/ec/cuda/ec_cuda_executor_interruptible.c
On some systems 
```
root@hpc-kernel-03:/tmp/val/ucc/src/components/ec/cuda# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
root@hpc-kernel-03:/tmp/val/ucc/src/components/ec/cuda# gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
the build of ec/cuda fails with the output
```
libtool: link: ar cru .libs/libucc_ec_cuda_kernels.a '.libs/ec_cuda_wait_kernel.o' '.libs/ec_cuda_executor.o'
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: ranlib .libs/libucc_ec_cuda_kernels.a
libtool: …
```
=> EC/CUDA: fixes uninit build fix

config/m4/rccl.m4, src/components/tl/rccl/allgatherv/allgatherv.h, src/components/tl/rccl/tl_rccl.h
Two minor fixes to the TL/RCCL component
- update the RCCL configure logic to recognize also old header file location
used before ROCm 5.0
- Previous version incorrectly specified score for all mem types with
allgatherv in TL/RCCL. It breaks host memory allgatherv because it was directed to
RCCL TL which does not handle such pattern. This patch fixes it by adding
the rocm mem type in UCC_TL_RCCL_ALLGATHERV_DEFAULT_ALG_SELECT_STR
bug fixes
=> TL/RCCL: fix configure logic and allgatherv score

src/utils/ucc_proc_info.c
Decreases log level of messages during ucc_proc_info. 
E.g,. when libnuma is not available we don't want to print error message, since UCC can still proceed w/o it.
```
[1,2359]<stdout>:[1655259590.588912] [a04n10:2079770:0]   ucc_proc_info.c:214  UCC  ERROR libnuma.so: cannot open shared object file: No such file or director
```
=> UTIL: decrease debug level for proc_info

src/components/tl/sharp/tl_sharp_coll.c, src/utils/ucc_rcache.h
Extended version of ucc_rcache_get that supports in/out "args" parameter. 
Used in tl/mlx5 to indicate if rache entry was modified (i.e., if actual memory dereg/reg happened). In this case tl/mlx5 needs to update umr mkeys.
=> (tl_mlx5_4) UTIL: rcache_get_arg

config/m4/ibverbs.m4, configure.ac
Adds configure steps to detect ibverbs/mlx5dv availability.
Used to build tl/mlx5
=> (tl_mlx5_3) BUILD: verbs/dv detection

config/m4/rocm.m4, configure.ac, src/components/ec/rocm/Makefile.am, src/components/ec/rocm/ec_rocm.c, src/components/ec/rocm/ec_rocm.h, src/components/ec/rocm/ec_rocm_executor.c, src/components/ec/rocm/ec_rocm_executor.h, src/components/ec/rocm/ec_rocm_executor_interruptible.c, src/components/ec/rocm/ec_rocm_executor_persistent.c, src/components/ec/rocm/kernel/Makefile.am, src/components/ec/rocm/kernel/ec_rocm_executor_kernel.cu, src/components/ec/rocm/kernel/ec_rocm_wait_kernel.cu, src/components/mc/rocm/Makefile.am, src/components/mc/rocm/kernel/Makefile.am, src/components/mc/rocm/kernel/mc_rocm_reduce.cu, src/components/mc/rocm/kernel/mc_rocm_reduce_multi.cu, src/components/mc/rocm/kernel/mc_rocm_reduce_multi_alpha.cu, src/components/mc/rocm/kernel/mc_rocm_reduce_ops.h, src/components/mc/rocm/mc_rocm.c, src/components/mc/rocm/mc_rocm.h, src/core/ucc_coll.c
Add support for using TL/UCP for ROCm memory
This commit allows among other things to use the Open MPI /ucc component for buffer located on ROCm devices.
=> EC/ROCM: add support for using rocm memory from tl/upc

src/components/cl/basic/cl_basic_team.c
Fixes potential segv in cl/basic team destroy when score_map_free is called on non-init value.
If CL/BASIC fails to init any team (e.g. when team_size == 1 and TL/SELF is not available, maybe UCC_TLS=ucp is set), then segv happens in cl_basic_team_destroy.
=> CL/BASIC: fix score_map cleanup

src/components/base/ucc_base_iface.h, src/core/ucc_context.c
Adds UCC_BASE_LIB_FLAG_CTX_SERVICE_TEAM_REQUIRED to the tl_context attribute flags. This flag allows a TL to indicate that it requires a service_team during tl context creation.
TL/MLX5 needs to establish shared_pd during tl context creation. For that it requires OOB exchange over "node" subgroup. It is done using service team that needs to be available at ctx creation. If it is not available tl/mlx5 context should be skipped.
=> (tl_mlx5_5) CORE: ctx service team flag

cuda_lt.sh
stop compilation on nvcc build error
cuda_lt.sh is used to build device code, however any returned nvcc error (e.g. due to syntax error in code) ignored. In that case UCC build always finishes successfully although EC and MC CUDA were not built. 
exit and return error if any cmd in cuda_lt.sh fails
=> BUILD: exit on cuda compile error

config/m4/rccl.m4
allow to explicitly disable tl/rccl 
If rccl is installed as part of the rocm software package, the configure script picks it up (correctly) even if the user did not explicitly request it. However, if not desired, the  ```--with-rccl=no``` option did not work correctly due to a minor mistake in the configure script.
=> TL/RCCL: fix configure logic

src/components/tl/cuda/alltoall/alltoall_ce.c, src/components/tl/cuda/alltoallv/alltoallv_ce.c
alltoall stage is not initialized for non-triggered post
=> TL/CUDA: fix uninit alltoall stage

src/components/tl/ucp/tl_ucp_coll.h
bug fix of TL/UCP when using executor for GPU collectives
`ucc_ee_executor_task_test` may return `UCC_INPROGRESS ` or `UCC_OPERATION_INITIALIZED` when it is not ready. TL/UCP only checks `UCC_INPROGRESS` may cause false results. 
Let it return with task status of `UCC_INPROGRESS` as long as it's not `UCC_OK` or failures (i.e., `status > 0`)
=> TL/UCP: fix executor status check

src/components/tl/nccl/tl_nccl_coll.c, src/components/tl/rccl/tl_rccl_coll.c
move the invocation of event_destroy() from the coll_finalize() function to the free_task() function .
Running ucc_test_mpi generated warning about event objects not being returned to the mpool. This commit fixes the problem by making sure that the events are correctly managed even if a test is skipped due to an unsupported datatype.
=> TL/RCCL and TL/NCCL: move event_destroy call

src/components/tl/cuda/tl_cuda_coll.c, test/mpi/main.cc, test/mpi/test_mpi.cc
Check GPU in collective_init matches device used to initialize team. Set GPU device in multithread test
Fixes segfault in multithread tests with TL CUDA
=> TL/CUDA: check cuda device in coll init

src/core/ucc_coll.c, src/core/ucc_team.c, src/ucc/api/ucc.h
Print error if not implemented UCC API function is called.
Following functions are not currently implemented. Linker will throw undefined reference error if somebody tries to use them.
ucc_team_get_attr
ucc_team_get_size
ucc_team_get_my_ep
ucc_team_get_all_eps
ucc_collective_init_and_post
For discussion: can we remove ucc_team_get_size and ucc_team_get_my_ep? Maybe it's better to return team size and ep using  ucc_team_get_attr?
=> BUILD: return error for not implemented functions

src/components/mc/cuda/kernel/mc_cuda_reduce.cu, src/components/mc/cuda/kernel/mc_cuda_reduce_multi.cu, test/gtest/core/test_mc_reduce.h, test/mpi/main.cc, test/mpi/test_mpi.cc
add support for unsigned integers datatypes uint16(32,64) in MC/CUDA reduce colls. Update gtest and mpitest with those new dt.
=> MC/CUDA: add uint16(32,64) support in reduce

src/core/ucc_constructor.c, src/core/ucc_global_opts.c
Adds option to disable config files usage
If config file is installed into default path (HOME/ucc.conf) or ucc_install/share/ucc.conf then it will be used and user has no option to not use it (only put another empty file and point UCC_CONFIG_FILE to it, which is not convenient).
Now, default value for UCC_CONFIG_FILE is "auto" which means search in default paths. "n", "no", "0", "" means - don't use cfg file.
=> CORE: option to disable cfg file

test/mpi/mpi_util.cc, test/mpi/test_mpi.cc
Create separate MPI comm for each UCC team created in test/mpi.
MPI comms are used concurrently during ucc_test_mpi if '-T' (multithreaded) is provided. MPI_COMM_WORLD is used for oob progress as well. This causes a race and results in "truncated message" error that has been observed lately in Jenkins.
=> TEST/MPI: use dedicated comm per ucc team

test/mpi/main.cc, test/mpi/test_mpi.cc, test/mpi/test_mpi.h
Fixes hangs in multi-threaded test run 
Each thread calls set_gpu_device which used to call MPI_Comm_split to figure out local node rank. This comm split is not allowed to be called concurrently by multiple threads (by MPI spec). 
Pre-compute node_local_rank once
=> TEST/MPI: don't call comm_split from set_gpu_dev

src/components/tl/nccl/tl_nccl_coll.c, src/components/tl/nccl/tl_nccl_team.c
Fixes src dtype check in TL/NCCL: should be taken from src.info instead of info_v.
Also decreases log level of "unsupported coll" message to debug. This case is not fatal error: we can still fallback to other TLs. If no other TLs avail the error will be thrown by the CORE.
=> TL/NCCL: allgatherv send dtype check fix

src/core/ucc_team.c, test/gtest/core/test_team.cc
Add implementation for `ucc_team_get_attr()`
`ucc_team_get_size` and `ucc_team_get_my_ep` were removed in #555 
Currently only `UCC_TEAM_ATTR_FIELD_SIZE` and `UCC_TEAM_ATTR_FIELD_EP` are supported.
=> CORE: add implementation for ucc_team_get_attr

src/components/tl/rccl/tl_rccl.h, src/components/tl/rccl/tl_rccl_coll.c, src/components/tl/rccl/tl_rccl_coll.h, src/components/tl/rccl/tl_rccl_team.c
Add support gather, gatherv, scatter, and scatterv operations.
functionality was missing in tl/rccl.
For Gather and Scatter operations we invoke the corresponding rccl operations. For Gatherv/Scatterv the code uses simple loop of Send/Recv operations
=> TL/RCCL: add support for gather and scatter

src/coll_score/ucc_coll_score_map.c, src/core/ucc_coll.c, src/utils/ucc_coll_utils.c, src/utils/ucc_coll_utils.h, test/gtest/core/test_utils.cc
ucc_coll_args_msgsize is used to  compute msgsize of collective operation which is defined by the ucc_coll_args_t. However args is not enough. For some collectives the msgsize depends on team_size and team_rank (to detect root). At the same time this fn can be called for a collective defined on a TL team which is a subset of CORE ucc_team. In this case we need to use proper  rank/size info to compute total coll size, i.e. using core team->rank/size is incorrect.
Current implementation leads to crash with CL/HIER (when ucc_coll_init is called for a subgroup).
Pass rank/size explicitly to ucc_coll_args_msgsize. For ucc_coll_init we will store rank/size on the score_map.
=> UTIL: fix coll_args_msgsize routine

src/components/cl/basic/cl_basic_lib.c, src/components/tl/sharp/tl_sharp.c, src/components/tl/sharp/tl_sharp.h, src/components/tl/sharp/tl_sharp_context.c, src/components/tl/sharp/tl_sharp_lib.c, src/components/tl/sharp/tl_sharp_team.c, src/core/ucc_context.c, src/core/ucc_context.h, src/core/ucc_team.c
Add support for internal OOB in TL SHARP
Replacement for PR #568 
Internal OOB has native support for broadcast, no need to allocate temp buffer and use allgather to emulate broadcast as it's done for SHARP OOB now.
Need to set UCC_TL_SHARP_USE_INTERNAL_OOB=1 to enable internal OOB in TL SHARP.
=> TL/SHARP: use internal oob

src/components/mc/rocm/kernel/mc_rocm_reduce.cu, src/components/mc/rocm/kernel/mc_rocm_reduce_multi.cu
add support for unsigned integers for rocm reduction operations.
This is a v1.1 patch only, master already supports the operations,
which were added with the reduce-to-ec patch in that case.
to support unsigned ints in v1.1. for rocm buffers with tl/ucp
=> MC/ROCM: add support for unsigned dts

src/components/tl/cuda/alltoall/alltoall_ce.c, src/components/tl/cuda/alltoallv/alltoallv_ce.c, src/components/tl/cuda/tl_cuda_team.c, src/components/tl/cuda/tl_cuda_team_topo.c, src/components/tl/cuda/tl_cuda_team_topo.h
Reworked TL/CUDA proxy storage. Each rank keeps list of ranks where this rank is proxy.
In TL/CUDA alltoall/alltoallv:
* No need to go over list of proxy ranks to post copy
* Destination buffer registered only if required
=> TL/CUDA: alltoall dst buf registration

tools/perf/Makefile.am, tools/perf/ucc_pt_benchmark.cc, tools/perf/ucc_pt_benchmark.h, tools/perf/ucc_pt_coll.h, tools/perf/ucc_pt_coll_allgather.cc, tools/perf/ucc_pt_coll_allgatherv.cc, tools/perf/ucc_pt_coll_allreduce.cc, tools/perf/ucc_pt_coll_alltoall.cc, tools/perf/ucc_pt_coll_alltoallv.cc, tools/perf/ucc_pt_coll_barrier.cc, tools/perf/ucc_pt_coll_bcast.cc, tools/perf/ucc_pt_coll_gather.cc, tools/perf/ucc_pt_coll_gatherv.cc, tools/perf/ucc_pt_coll_reduce.cc, tools/perf/ucc_pt_coll_reduce_scatter.cc, tools/perf/ucc_pt_coll_scatter.cc, tools/perf/ucc_pt_coll_scatterv.cc, tools/perf/ucc_pt_comm.cc, tools/perf/ucc_pt_comm.h, tools/perf/ucc_pt_config.cc, tools/perf/ucc_pt_config.h, tools/perf/ucc_pt_op_memcpy.cc, tools/perf/ucc_pt_op_reduce.cc, tools/perf/ucc_pt_op_reduce_strided.cc
Benchmark operation in EC components with perftest
Following operations are supported
* reducedt - strided reduce multi with different number of vectors
* memcpy - memory copy
* triggered and non-triggered modes
=> TOOLS: add ec ops to perftest

src/components/cl/hier/allreduce/allreduce_rab.c, src/components/tl/ucp/scatter/scatter_knomial.c
Fixes:
[1660824500.613377] [swx-clx02:46991:0] bcast_sag_knomial.c:90   TL_UCP ERROR failed to init scatter_knomial task
observed in ucc_test_mpi with CL/HIER
Don't check for INPLACE flag in tl_ucp_scatter_knomial. Currently it is not generic scatter - it is special implementation for bcast_sag.
=> CL/HIER: allreduce rab fix

config/m4/cuda.m4, src/components/ec/cuda/kernel/ec_cuda_half_sm52.h, src/components/ec/cuda/kernel/ec_cuda_reduce.cu
This PR add builds for GPU architecture 50, 52 and 86
I am enabling PyTorch's distributed unit tests on the ProcessGroupUCC in https://github.com/pytorch/pytorch/pull/83285, but I am seeing lots of errors like:
```C++
2022-08-18T20:47:14.5411762Z [1660855634.540897] [0e25f152ba11:26395:0] ec_cuda_executor.cu:319  UCC  ERROR cudaGetLastError()() failed: 209(no kernel image is available for execution on the device)
2022-08-18T20:47:14.5412299Z [1660855634.540920] [0e25f152ba11:26395:0] ec_cuda_executor_persistent.c:78   cuda ec ERROR failed to launch executor kernel
2022-08-18T20:47:14.5412771Z [1660855634.540926] [0e25f152ba11:26395:0]        ucc_coll.c:424  UCC  ERROR error in ee executor start, Unhandled error
2022-08-18T20:47:14.5413218Z [1660855634.540942] [0e25f152ba11:26395:0] …
```
=> BUILD: Build for GPU architecture 52 and 86

src/components/base/ucc_base_iface.h, src/components/cl/hier/allreduce/allreduce_split_rail.c, src/components/tl/ucp/allreduce/allreduce_sra_knomial.c, src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c, src/components/tl/ucp/reduce_scatterv/reduce_scatterv_ring.c, test/gtest/common/test_obj_size.cc
Improves scratch buffer usage in pipelined algs
Currently, the scratch buffer allocation for the allreduce (CL/HIER split rail, or TL/UCP SRA) is of the same size as the user buffer. For example, 128Mb allreduce will result in 128Mb scratch requirement. However, in the pipelined algorithm we only need the scratch as big as 1 frag.
Extends base_args with the "max_frag_size" optional field. This way the collectives that support fragmentation can optimize their scratch allocation since they know the maximum size of fragment. (sra in tl/ucp has such support). 
CL/HIER split rail allreduce inplace case no longer needs to allocate scratch. It used to go:
RSV into scratch => Allreduce scratch->rbuf => Allgather inplace
now it is:
RSV inplace => Allreduce inplace => Allgather inplace
=> Optimize scratch buffer allocation for pipelined algorithms

src/coll_patterns/recursive_knomial.h, src/coll_patterns/sra_knomial.h, src/components/tl/ucp/allgather/allgather_knomial.c
Fixes "ucc_kn_pattern_pattern_loop_last_iteration". It used to return incorrect value in the case of extra ranks. This causes failure in allreduce after PR #602 . It also fixes #585 
Compute n_iters for direct and backward KN pattern. Also change the way step_radix/block_count are computed, based n_full_subtrees.
=> UTIL: fix sra iters computation

src/schedule/ucc_schedule_pipelined.c
Removing frag status assert in pipilene schedule
Assert is incorrect. Frag status might be changed by another thread when it restarts it.
=> SCHEDULE: remove status assert

src/components/cl/hier/allreduce/allreduce_rab.c, src/components/cl/hier/allreduce/allreduce_split_rail.c, src/components/cl/hier/alltoallv/alltoallv.c, src/components/cl/hier/barrier/barrier.c, src/components/cl/hier/cl_hier_context.c, src/components/tl/cuda/tl_cuda_context.c, src/components/tl/nccl/tl_nccl_context.c, src/components/tl/rccl/tl_rccl_context.c, src/components/tl/self/tl_self_context.c, src/components/tl/sharp/tl_sharp_context.c, src/components/tl/ucp/allreduce/allreduce_sra_knomial.c, src/components/tl/ucp/bcast/bcast_sag_knomial.c, src/components/tl/ucp/reduce_scatter/reduce_scatter_ring.c, src/components/tl/ucp/reduce_scatterv/reduce_scatterv_ring.c, src/components/tl/ucp/tl_ucp_context.c, src/core/ucc_coll.c, src/schedule/ucc_schedule.c, src/schedule/ucc_schedule.h, src/schedule/ucc_schedule_pipelined.c, src/utils/ucc_compiler_def.h, src/utils/ucc_list.h, test/gtest/core/test_schedule.cc
Modifies event_manager implementation to support arbitrary number of subscribers
In master any task can only have up to 4 subscribers otherwise code crashes. However, we already have use case for more: cl/hier split_rail allreduce would hit that case if the 1st reduce_scatterv is a schedule as well (and cl/hier schedule is ordered)
coll_task now contains list of event_manager structs each containing up to MAX_LISTENERS objects. event_manager entries are allocated on demand (on the first event_manager subscribe call). coll_task now has 2 more apis: coll_task_construct and destruct that must be called once (or via obj_init callback of an mpool).
I did a smoke perf test on most latency sensitive colls (1 node tl/shm allreduce/bcast) and did not measure any degradation.
=> SCHEDULE: support arbitrary number of subscribers

src/schedule/ucc_schedule_pipelined.c, src/utils/ucc_atomic.h
Fixes hang reproduced with "Serialized" pipeline type
A task can depend on 2 other tasks (e.g. from another frag of of schedule and prev task in a given frag). In that case when those 2 frags a progressed by multiple threads ucc_dependency_handler may be called concurrently which results in a race on n_deps_satisfied.
=> SCHEDULE: fixes race on n_deps_satisfied

src/components/cl/hier/allreduce/allreduce_split_rail.c, src/components/cl/hier/cl_hier.c, src/components/cl/hier/cl_hier.h, src/components/tl/ucp/allreduce/allreduce_sra_knomial.c, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/schedule/ucc_schedule_pipelined.c, src/schedule/ucc_schedule_pipelined.h
Adds 3rd type of pipeline (sequential): a task in a fragment only starts when the previous task has completed. Parallel - all start the same time. Ordered - a task in a fragment starts when the previous task has started. We used to have only "parallel" and "ordered" in master.
Sequential - may potentially be useful when we don't want to oversubscribe a TL (can be useful for TL/SHM, TL/CUDA?).
PR also adds a better cfg parsing with explicit naming of pipeline types.
=> SCHEDULE: 3 types of pipelines

src/schedule/ucc_schedule_pipelined.c, src/utils/ucc_atomic.h
=> V1.1.x SCHEDULE: fixes race on n_deps_satisfied

src/components/tl/cuda/tl_cuda_coll.h
Fixes #622  
The hang is caused by the function ucc_tl_cuda_get_sync. It checks the value state which is located in shared memory. For ranks != 0 compiler optimizes it out: it loads the value once and stores into register. If *state != seq_num it is never checked (re-loaded) again, because compiler thinks that it is never updated (only rank 0 will update it). And the ucc_tl_cuda_get_sync fn is inlined, so register value of *state is never reloaded.
The test would work if rank 0 is fast enough and the *state contains updated seq_num when rank 1 enters.
Declare variable as "volatile" to avoid compiler optimization.
=> TL/CUDA: fixes hang on sync_state

src/utils/ucc_compiler_def.h
Fixes ec/cuda kernels build on rhel 7.2
```
[root@sharp-ci-01 kernel]# /hpc/local/oss/cuda11.7/bin/nvcc  -c /workspace/ucc_private/src/components/ec/cuda/kernel/ec_cuda_wait_kernel.cu -I/tmp/ucx_build/install/include/ -O3 -g -DNDEBUG -I/tmp/ucc_build -I/workspace/ucc_private/src
-I/tmp/ucc_build/src --compiler-options -fno-rtti,-fno-exceptions -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compu
te_70,code=sm_70 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_86,code=sm_86 -gencode=arch=compute_86,cod
e=compute_86 -Xcompiler -fPIC -o …
```
=> BUILD: fixes ec/cuda build on rhel7.2

.github/workflows/codestyle.yaml, .github/workflows/main.yaml
Fixes failures observed in CI
build of ompi v5 without oshmem (autogen --no-oshmem) results in segfault in mpirun
=> CI: fixes ompi build

src/components/ec/cuda/ec_cuda.c, src/components/ec/ucc_ec.c, src/ucc/api/ucc.h
Fixes EC CUDA finalize
* EC CUDA destructor is not called
* interruptible executor tasks mpool is not freed
=> EC/CUDA: fix finalize

config/m4/cuda.m4
fix build error for CUDA 11.x and earlier versions
the nvcc arch flags (e.g., compute_86, sm_86) recently added (#601) are not supported before CUDA 11.1 and may result in compilation error.
only add `ARCH12` nvcc flags (sm_86, etc) for CUDA 11.1+
=> BUILD: fix nvcc arch flag fo CUDA 11.0

config/m4/cuda.m4, src/components/ec/cuda/ec_cuda.c, src/components/ec/cuda/ec_cuda.h, src/components/ec/cuda/kernel/ec_cuda_executor.cu
Use one cooperative kernel for the persistent kernel in EC/CUDA. Tests show that this has little/negligible effects on the performances (cf spreadsheet [PR coop group.xlsx](https://github.com/openucx/ucc/files/9487807/PR.coop.group.xlsx)).
In the present implementation, we have to launch three kernels, `executor_start`, `executor_kernel`, `executor_shutdown_ack`. Only `executor_kernel` actually performs computation, whereas the two other kernels are only used to synchronize the grid, which is a primitive function in cooperative launches.
The cooperative group primitives offer more flexibility that could also result in further improvements in EC/CUDA.
The feature is enabled by default but can be controlled by the env variable `UCC_EC_CUDA_USE_COOPERATIVE_LAUNCH`.
At initialization, a we …
=> EC/CUDA: use one kernel with cooperative launch

src/core/ucc_context.c, src/core/ucc_context.h, test/gtest/common/test_ucc.cc, test/gtest/common/test_ucc.h
Adds topo information for each process in gtest. All "virtual processes" (created by gtest) get their own "local_proc_info" to generate topology
This enables bigger coverage: CL/HIER and TL/SHM
=> TEST: support topo/hierarchy in gtest

src/components/cl/basic/cl_basic.h, src/components/cl/basic/cl_basic_context.c, src/components/cl/basic/cl_basic_team.c, src/components/cl/hier/cl_hier.h, src/components/cl/hier/cl_hier_context.c, src/components/cl/ucc_cl.h, src/core/ucc_context.c
Properly handle potential failures that happen during TL context_create_epilog call.  
Current behavior: if context_create_epilog fails -> ucc context creation fails -> job fails.
Expected behavior: if TL that failed to perform context_create_epilog is not explicitly required job must proceed w/o it. Example: TL/SHARP not enabled explicitly (in a "try" mode), it might fail to initialize but we should proceed.
* Check if the TL is explicitly requested
* The order of steps during ucc_context create is: 1) create all TL contexts, 2) create all CL contexts, 3) perform global address exchange (if required via params) - all TLs/CLs ctx objects are required for that, 4) allocate topo object if required; 5) allocate ctx service team (if required); 5) call epilog
* When CL contexts are created at …
=> CORE: correctly handle failure in ctx_create epilog

src/coll_score/ucc_coll_score.c, src/coll_score/ucc_coll_score.h, src/components/cl/basic/cl_basic_team.c, src/components/cl/hier/cl_hier_team.c, src/components/tl/cuda/tl_cuda_team.c, src/components/tl/nccl/tl_nccl_team.c, src/components/tl/rccl/tl_rccl_team.c, src/components/tl/self/tl_self_team.c, src/components/tl/sharp/tl_sharp_team.c, src/components/tl/ucp/tl_ucp_team.c, test/gtest/coll_score/test_score_update.cc
Fixes extra memory typed added when tl score is updated from str.
TL UCP running on DGX shows following memory types supported
```
ucc_coll_score_map.c:200  UCC  INFO  Alltoallv:
ucc_coll_score_map.c:200  UCC  INFO     Host: {0..inf}:TL_UCP:10
ucc_coll_score_map.c:200  UCC  INFO     Cuda: {0..inf}:TL_CUDA:10
ucc_coll_score_map.c:200  UCC  INFO     CudaManaged: {0..inf}:TL_UCP:10
ucc_coll_score_map.c:200  UCC  INFO  Barrier:
ucc_coll_score_map.c:200  UCC  INFO     Host: {0..inf}:TL_SHM:10
ucc_coll_score_map.c:200  UCC  INFO     Cuda: {0..inf}:TL_UCP:10
ucc_coll_score_map.c:200  UCC  INFO     CudaManaged: {0..inf}:TL_UCP:10
ucc_coll_score_map.c:200  UCC  INFO  Bcast:
ucc_coll_score_map.c:200  UCC  INFO     Host: {0..8K}:TL_SHM:10 {8193..32767}:TL_UCP:10 {32K..inf}:TL_UCP:10 …
```
=> CORE: fix memory type score update

src/components/ec/rocm/ec_rocm.c, src/components/ec/rocm/ec_rocm.h, src/components/ec/rocm/ec_rocm_executor.c, src/components/ec/rocm/ec_rocm_executor_interruptible.c, src/components/ec/rocm/kernel/ec_rocm_executor_kernel.cu, src/components/ec/rocm/kernel/ec_rocm_wait_kernel.cu
Introduce the ability to use host based reduction and copy operations
This avoids the cost of a kernel launch., which can be beneficial for short messages and when trying to overlap communication and computation occurring on the GPU.
=> EC/ROCM: add host execution capability

src/components/ec/base/ucc_ec_base.h, src/components/ec/cuda/ec_cuda.c, src/components/ec/cuda/ec_cuda.h, src/components/ec/cuda/ec_cuda_executor_interruptible.c, src/components/ec/cuda/ec_cuda_executor_persistent.c, src/components/ec/cuda/kernel/ec_cuda_executor.cu
Optimize copy_multi and reduce_multi_dst operations for persistent executor in TL CUDA
Multi operations are split into smaller subtasks to utilize multiple workers (blcoks) in persistent kernel
=> EC/CUDA: opt persistent multi ops

src/components/cl/hier/alltoall/alltoall.c, src/components/cl/hier/alltoallv/alltoallv.c
Bug fix [#3213667](https://redmine.mellanox.com/issues/3213667).
CL/HIER alltoall and alltoallv was hanging due to single process on node case being disabled.
Enabling single process on node, in which case only "full_task" (aka intra node) sends original args data without overwriting counts and displacements. In this case "node_task" (inter node) will not be initiated nor added to schedule.
=> CL/HIER: alltoall single proc on node fix

src/components/tl/sharp/tl_sharp_coll.c
Fixes memory type check in TL SHARP for inplace allreduce
=> TL/SHARP: fix memory type check in allreduce

config/m4/ucx.m4, src/components/base/ucc_base_iface.c, src/components/ec/ucc_ec.c, src/components/mc/ucc_mc.c, src/components/tl/ucp/tl_ucp_lib.c, src/core/ucc_constructor.c, src/core/ucc_context.c, src/core/ucc_global_opts.c, src/core/ucc_lib.c, src/utils/ucc_parser.c, src/utils/ucc_parser.h, test/gtest/utils/test_cfg_file.cc
Align ucc_config_parser_fill_opts with changes in UCS 
https://github.com/openucx/ucx/pull/8557
Fixes UCC build with latest UCX
=> CORE: fix ucc parser build

cmake/ucc-targets.cmake.in
_Describe what this PR is doing._ 
Set `prefix` to a relative path with `CMAKE_CURRENT_LIST_DIR` so that users can move the UCX library to a path different from prefix.
_Justification for the PR. If there is existing issue/bug please reference. For
bug fixes why and what can be merged in a single item._
It's possible that `prefix` and installation path are different. For example, in multi-stage docker builds,
we can build and install UCC in a different stage with `prefix` of "/build/ucc" and copy the artifacts to "/usr/local"  of the main container.
In this case, `ucc-targets.cmake`'s prefix would be "/build/ucc" but it won't work in the container.
You can check this kind of discrepancy in `nvcr.io/nvidia/pytorch:22.08-py3` container.
_It is optional but for complex PRs please provide …
=> BUILD: Change `prefix` to a relative path with `CMAKE_CURRENT_LIST_DIR`

config/m4/ucx.m4
Fixes build time UCX version detection
Need to always check UCX version during build time, before this PR it was only checking if user explicitly sets --with-ucx=ucxdir
=> BUILD: fix UCX version detection

src/components/ec/cuda/ec_cuda_executor_persistent.c, src/components/ec/cuda/kernel/ec_cuda_executor.cu, src/components/ec/cuda/kernel/ec_cuda_reduce.cu, src/components/ec/cuda/kernel/ec_cuda_reduce_ops.h
Adds all the ops and dts in EC/CUDA for triggered and non-triggered executions.
Replace [PR610](https://github.com/openucx/ucc/pull/610) and [PR#596](https://github.com/openucx/ucc/pull/596)
No perf degradation, see graph below.
Done by making "device template" functions (common both for persistent and interruptible) + some macro magic + switch/case in the executor kernel.
=> EC/CUDA: add all ops and dts

src/core/ucc_context.c
Change log level of ucc_context_config_modify to INFO when CL or TL is not found
User might not know in advance what TL or CL are loaded in runtime. Instead of printing just return UCC_ERR_NOT_FOUND
=> CORE: change log level of config_modify

.ci/scripts/run_dlrm.sh, Makefile.am, contrib/ucc.conf, src/Makefile.am, src/components/base/ucc_base_iface.c, src/components/base/ucc_base_iface.h, src/components/cl/ucc_cl.c, src/components/tl/ucc_tl.c, src/components/tl/ucp/allreduce/allreduce_knomial.c, src/components/tl/ucp/allreduce/allreduce_sra_knomial.c, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_context.c, src/components/tl/ucp/tl_ucp_team.c, src/utils/arch/cpu.h, src/utils/ini.c, src/utils/ini.h, src/utils/ucc_parser.c, src/utils/ucc_parser.h
Adding support to parse and apply tuning parameters for best perf result in ucc.conf config file.
Note - this PR creates the section based parsing infrastructure, and implements it usage in TL/UCP Allreduce as prototype. In future PR usage should be extended to all colls in TL/UCP. Later on to each TL in which is found relevant.
To create an extendable way for both core developers and users to add case specific perf params. 
Extending parse handler to read "sections" from ucc.conf and saving each section in a two level hash table, where top level is a a hash table per section and second level is key-value pairs of params per section.
In cl/tl team creation, if section is applicable (running on corresponding vendore, model, etc) the values will be copied from current section hash table to …
=> Ucc tuning file

src/components/tl/nccl/tl_nccl.h, src/components/tl/nccl/tl_nccl_coll.c, src/components/tl/nccl/tl_nccl_team.c, src/core/ucc_coll.c, src/schedule/ucc_schedule.c, src/schedule/ucc_schedule.h
Correctly handle time out error for triggered task
* For TL NCCL need to use commAbort, otherwise commDestroy could hang
* For other TLs need to destroy executor during finalize
=> CORE: fix timeout handle for triggered post

src/components/ec/cuda/kernel/ec_cuda_executor.cu, src/components/ec/cuda/kernel/ec_cuda_reduce.cu, src/components/ec/cuda/kernel/ec_cuda_wait_kernel.cu
Fixes
```
[2022-12-08T22:13:16.385Z] /build-result/src/hpcx-v2.14-gcc-MLNX_OFED_LINUX-5-redhat7-cuda11-gdrcopy2-nccl2.12-x86_64/ucc-master/src/utils/ucc_coll_utils.h(183): error: identifier "UINT32_MAX" is undefined
```
=> EC/CUDA: fix build with gcc 4.8.5

src/Makefile.am, src/coll_score/ucc_coll_score.c, src/components/cl/hier/allreduce/allreduce_split_rail.c, src/components/tl/ucp/allreduce/allreduce_knomial.c, src/components/tl/ucp/allreduce/allreduce_sra_knomial.c, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_coll.h, src/components/tl/ucp/tl_ucp_lib.c, src/utils/ucc_coll_utils.h, src/utils/ucc_datastruct.c, src/utils/ucc_datastruct.h, src/utils/ucc_parser.c, src/utils/ucc_parser.h, src/utils/ucc_string.c, src/utils/ucc_string.h, test/gtest/Makefile.am, test/gtest/utils/test_parser.cc
Based on PR #631 
Adds new type of env_var parameter: a value with msg range qualifiers. This represents a parameter that holds different values for different msg sizes/mtypes. For example, in this PR knomia radix of TL/UCP allreduce algorithm is modified to be mragned unsigned parameter. This allows specifying different radix values for different msg ranges/mem_types. E.g.:
UCC_TL_UCP_ALLREDUCE_SRA_KN_RADIX=0-4K:cuda:8,16k-inf:host:4,auto
Parameter can also store a number (single default value applied to the entire msg range 0-inf and for all mtypes). It can be just "auto" as well.
Flexible configuration. Convenient way to specify the value in TUNING section of the config file
Internally the parameter is stored as a linked list of ranges with mtype maps.
=> Mranged params

src/utils/arch/x86_64/cpu.c
Adding cpu detection of AMD Milan 
To be used in TL/SHM perf tuning
added correct family
=> UTIL: add amd milan to cpu family

src/components/tl/ucp/reduce_scatter/reduce_scatter_ring.c, src/components/tl/ucp/reduce_scatterv/reduce_scatterv_ring.c, src/components/tl/ucp/tl_ucp_coll.h, src/components/tl/ucp/tl_ucp_team.c
Fixes hangs in following cases when npolls is 0
1. team create with preconnect task
2. reduce scatter ring
3. reduce scatterv ring
=> TL/UCP: fix running with npolls 0

src/components/ec/cuda/ec_cuda.c, src/components/ec/cuda/ec_cuda.h, src/components/ec/cuda/kernel/ec_cuda_executor.cu, src/components/ec/cuda/kernel/ec_cuda_reduce.cu, src/components/ec/cuda/kernel/ec_cuda_reduce_ops.h
Various optimizations in reduce ad reduce_strided kernels. We get the following improvements on the BW (see also graphs below):
- triggered mode (aka persistent mode): BW improved by a factor of ~2
- interruptible mode, reduce collective: BW improved by a factor of ~10
- interruptible mode, reduce_strided collective: BW roughly unchanged
- To optimize the triggered mode, we split and unroll the loops in the kernel. The Unroll factor has been hand-tuned to 7. Higher value could potentially lead to better performances but with the current default number of threads (=512), the kernel does not fit into the GPU (tested on Tesla V100 32GB)
-  We have to set `UCC_EC_CUDA_USE_COOPERATIVE_LAUNCH` to 0 otherwise the persistent kernel with the unrolled loop with unroll factor 7 is too large to fit …
=> EC/CUDA: optimize reduce with unrolling

config/m4/cuda.m4, src/components/ec/cuda/ec_cuda.c, src/components/tl/nccl/tl_nccl_context.c
CU_DEVICE_ATTRIBUTE_CAN_USE_STREAM_MEM_OPS removed in cuda-12.0 and memops supported by default.
=> EC/CUDA: memops supported by default in cuda 12.0

.ci/scripts/run_docker.sh
Fix CI failure when more than one stale container is found. 
Failed Jenkins job (NVIDIA internal link)
http://hpc-master.lab.mtl.com:8080/job/ucc/1995/
Provide a list of container IDs to stop, rather than a single container name.
=> CI: fix failure when more than one container stale

src/components/tl/ucp/tl_ucp_lib.c, src/components/tl/ucp/tl_ucp_team.c, src/core/ucc_lib.c, src/utils/ucc_datastruct.c
Fixing config clone and destroy in TL/UCP after adding mrange config field
team config should be cloned instead of copied since it now includes list field
team config and lib config should be proper destroyed with ucc_config_parser_release_opts
=> TL/UCP: fix config clone and destroy

src/components/tl/ucp/allreduce/allreduce_knomial.c, src/components/tl/ucp/allreduce/allreduce_sra_knomial.c
Get allreduce radix range from team cfg instead of lib cfg
lib cfg will have either default value or user value from cmd. Team cfg handles config file values to be applied as well.
In team creation if config file is available and tuning turned on, team cfg will be updated with config file values.
=> TL/UCP: get range from team cfg instead of lib

.github/workflows/clang-tidy-rocm.yaml, src/components/ec/rocm/ec_rocm.c, src/components/ec/rocm/ec_rocm_executor_interruptible.c, src/components/ec/rocm/ec_rocm_executor_persistent.c, src/components/mc/rocm/mc_rocm.c, src/components/tl/rccl/tl_rccl_coll.c, src/components/tl/rccl/tl_rccl_context.c
add github actions to compile UCC with ROCm and RCCL support and run clang-tidy linter on those components.
=> TEST: add linter for ROCm/RCCL

src/components/cl/basic/cl_basic_context.c, src/components/cl/hier/cl_hier.h, src/components/cl/hier/cl_hier_context.c, src/components/cl/hier/cl_hier_team.c, src/components/ec/rocm/ec_rocm.c, src/components/tl/ucc_tl.c, src/core/ucc_coll.c, src/core/ucc_context.c, src/core/ucc_context.h, src/core/ucc_team.c, src/core/ucc_team.h
Check if TL context exists in every rank before creating tl team.
Because TL contexts list might not be the same for every rank it's possible to have allgather collision when different ranks trying to create different teams e.g.
```
tl_ucp_coll.c:79   TL_UCP ERROR failure in send completion Message truncated
```
During address exchange stage in team create or context create collect list of TLs available for each team rank.
=> CORE: check tl is reachable

src/components/tl/cuda/tl_cuda.h, src/components/tl/cuda/tl_cuda_team.c, src/components/tl/cuda/tl_cuda_team_topo.c, src/components/tl/cuda/tl_cuda_topo.c, src/components/tl/cuda/tl_cuda_topo.h
Use GPU PCI address instead of GPU ID to collect topology information in TL/CUDA
GPU ID (from cudaGetDevice() )  is not guaranteed to be unique within single node, for instance if user sets CUDA_VISIBLE_DEVICES=$OMPI_COMM_WORLD_LOCAL_RANK every rank will see one GPU with ID 0.
=> TL/CUDA: use pci bdf to build topo

config/m4/rccl.m4
Return flags to previous state after exit from RCCL.m4 
Currently flag __HIP_PLATFORM_AMD__ is propagated to almost every component compile command even if component is not related to HIP.
=> BUILD: remove unnecessary flag

src/components/tl/ucp/reduce_scatter/reduce_scatter_ring.c, src/components/tl/ucp/reduce_scatterv/reduce_scatterv_ring.c
Fixing race condition in reduce scatter and reduce scatterv ring algorithms.
In multithreaded environment send completion callback might be called from one thread and reduce scatter progress function from another. In that case busy flags value potentially cached so second thread doesn't see update from first thread.
Internal issue: https://redmine.mellanox.com/issues/3330642
=> TL/UCP: mt reduce scatter fix

src/components/ec/cuda/kernel/ec_cuda_executor.cu, src/components/ec/cuda/kernel/ec_cuda_reduce_ops.h
Simplify and unifies the implementation of the reduce kernels in EC/CUDA.
- reduce and reduce_strided kernels are unified into one, at the cost of an extra template parameter
- the part with the unrolled loop and the remainder are unified into one macro `CUDA_REDUCE_WITH_OP_CHUNK` that we call twice
- No perf degradation, cf graphs
=> EC/CUDA: unify reduce and reduce_strided kernels

src/components/ec/cuda/kernel/ec_cuda_reduce_ops.h
remove "if constexpr" statements
No perf degradation, see graphs below
causes a linter warning
```
warning #2912-D: constexpr if statements are a C++17 feature
```
=> EC/CUDA: remove if constexpr

.github/workflows/clang-tidy.yaml, src/components/cl/hier/Makefile.am, src/components/cl/hier/bcast/bcast.c, src/components/cl/hier/bcast/bcast.h, src/components/cl/hier/bcast/bcast_2step.c, src/components/cl/hier/cl_hier.c, src/components/cl/hier/cl_hier.h, src/components/cl/hier/cl_hier_coll.c, src/components/cl/hier/cl_hier_coll.h, src/components/cl/hier/cl_hier_team.c, src/core/ucc_team.h, test/gtest/coll/test_allreduce.cc, test/gtest/coll/test_bcast.cc
Adds 2 lvl pipelined broadcast algorithm to CL/HIER
Perf improvement. Example on 32nodes,  ppn=56.
UCC master   (tl/ucp) | UCC new (cl/hier, shm+ucp) | UCC new (cl/hier, shm+ucp) +   BCAST_KN_RADIX=6
-- | -- | --
6.46 | 5.27 | 4.38
6.49 | 5.32 | 4.47
6.51 | 5.32 | 4.39
6.46 | 5.33 | 4.44
6.45 | 5.29 | 4.39
7.21 | 5.54 | 4.59
8.19 | 6.3 | 5.21
8.76 | 7.2 | 6.42
10.95 | 7.6 | 6.15
11.72 | 8.25 | 6.55
14.06 | 9.15 | 7.44
16.86 | 11.78 | 9.72
24.28 | 17.73 | 14.92
=> CL/HIER: bcast 2step algorithm

src/components/tl/nccl/tl_nccl_coll.c, src/components/tl/nccl/tl_nccl_coll.h
Add in TL/NCCL support for datatypes that are not natively supported by nccl. This PR implement support for the following collectives:
- Non-reduction collectives now support all the datatypes
- Reduction collectives now support the complex datatypes `float32_complex` and `float64_complex` for the reduction operation `sum`.
Requested by cuSolver team
During collective initialization, we check if the datatype is not natively supported by nccl. If possible, we convert the buffer's datatype and count in order to set up an equivalent collective that is supported by nccl.
- for non-reduction collectives: the datatype is converted to `int8` and the count is rescaled accordingly
- for sum reduction collectives: `float32_complex` (resp. `float64_complex`) is converted to `float32` (resp. …
=> TL/NCCL: add support for more datatypes

src/components/ec/cuda/kernel/ec_cuda_executor.cu, src/components/ec/cuda/kernel/ec_cuda_reduce_ops.h
remove any c++11 feature
No perf degradation, see graphs below
errors in mtt
=> BUILD: fix gcc 4.0 compilation error in EC/CUDA 

src/components/tl/ucp/Makefile.am, src/components/tl/ucp/alltoallv/alltoallv.c, src/components/tl/ucp/alltoallv/alltoallv.h, src/components/tl/ucp/alltoallv/alltoallv_hybrid.c, src/components/tl/ucp/alltoallv/alltoallv_pairwise.c, src/components/tl/ucp/reduce_scatter/reduce_scatter_ring.c, src/components/tl/ucp/reduce_scatterv/reduce_scatterv_ring.c, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_coll.c, src/components/tl/ucp/tl_ucp_coll.h, src/components/tl/ucp/tl_ucp_lib.c, src/components/tl/ucp/tl_ucp_sendrecv.h, src/utils/ucc_math.h, test/gtest/coll/test_alltoallv.cc
Adds new alltoallv algorithms to TL/UCP. It's modified version of SLOAV alltoallv algorithm
C. Xu, M. G. Venkata, R. L. Graham, Y. Wang, Z. Liu and W. Yu, "SLOAVx: Scalable LOgarithmic AlltoallV Algorithm for Hierarchical Multicore Systems," 2013 13th IEEE/ACM International Symposium on Cluster, Cloud, and Grid Computing, 2013, pp. 369-376
Algorithms targes small message alltoallv and outperforms existing algorithm in UCC
Perf data collected on 192 ranks (4 nodes 48 PPN, AMD Milan CPU)
=> TL/UCP: hybrid alltoallv

tools/perf/ucc_pt_config.cc
add uint32, float64, and float(32|64|128)_complex dt to the perftests
=> TOOLS: add missing dts to perftest

cuda_lt.sh
The upcoming rocm release switched from clang-15 to clang-16, and we observer a compilation failure of the ec/rocm/kernel code. 
This commit fixes the compilation problem by omitting the `-Xcompile` flag in cuda_lt.sh if the compiler is hipcc. 
(Previously, the flag generated a warning, now its an error).
=> BUILD: fix compilation on clang-16 with hip

src/components/base/ucc_base_iface.c, src/components/base/ucc_base_iface.h, src/components/cl/basic/cl_basic.c, src/components/cl/basic/cl_basic_lib.c, src/components/cl/hier/cl_hier.c, src/components/cl/hier/cl_hier_lib.c, src/components/tl/cuda/tl_cuda.c, src/components/tl/cuda/tl_cuda.h, src/components/tl/cuda/tl_cuda_lib.c, src/components/tl/cuda/tl_cuda_team.c, src/components/tl/mlx5/tl_mlx5.c, src/components/tl/mlx5/tl_mlx5_lib.c, src/components/tl/nccl/tl_nccl.c, src/components/tl/nccl/tl_nccl_lib.c, src/components/tl/nccl/tl_nccl_team.c, src/components/tl/rccl/tl_rccl.c, src/components/tl/rccl/tl_rccl_lib.c, src/components/tl/self/tl_self.c, src/components/tl/self/tl_self_lib.c, src/components/tl/self/tl_self_team.c, src/components/tl/sharp/tl_sharp.c, src/components/tl/sharp/tl_sharp_lib.c, src/components/tl/ucc_tl.c, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp_lib.c, src/components/tl/ucp/tl_ucp_team.c, src/utils/ucc_component.h
Add config option to disable TL for team sizes below certain threshold, Adds check for min team and max team sizes in super class init.
Some TLs are known to be used starting from particular communicator size, for example it doesn't make sense to use SHARP for comm size 2. This PR sets following limits for TLs
| TL    | min supported team size | max supported team size | default comm size threshold |
|-------|-------------------------|-------------------------|-----------------------------|
| SELF  | 1                       | 1                       | 1                           |
| UCP   | 2                       | INF                     | 2                           |
| SHARP | 2                       | INF                     | 4                           |
| NCCL  | 2 …
=> CORE: add min team size option

src/utils/arch/cpu.h, src/utils/arch/x86_64/cpu.c
Detect AMD Genoa CPUs.
Required for TL SHM tuning.
=> UTIL: detect AMD Genoa CPU

test/mpi/test_allgather.cc, test/mpi/test_allgatherv.cc, test/mpi/test_alltoall.cc, test/mpi/test_alltoallv.cc, test/mpi/test_bcast.cc, test/mpi/test_case.cc, test/mpi/test_gather.cc, test/mpi/test_gatherv.cc, test/mpi/test_mpi.cc, test/mpi/test_mpi.h, test/mpi/test_scatter.cc, test/mpi/test_scatterv.cc
Add datatypes for non-reduction collectives in mpi_test
This patch is necessary for testing different datatype as the user would do, even if the collectives do not involve reduction
=> TEST: add configurable dt for non-reduction colls

test/gtest/Makefile.am, test/gtest/coll/test_scatter.cc, test/gtest/common/test_ucc.h
Adding gtest for scatter
Currently in this implementation all gtests for scatter will be skipped as there is no relevant TL that has a stand alone scatter that can be run. Once stand alone scatter will be implemented in TL/UCP the skip in this test will be removed.
=> TEST: adding gtest for scatter

src/components/tl/ucp/allreduce/allreduce_knomial.c
Getting radix from config file (if applicable) instead of from lib in knomial_allreduce_start.
1. bug fix for https://redmine.mellanox.com/issues/3362220#change-25139289
2. aligning with previous fix in knomial_allreduce_init from PR #702
=> TL/UCP: fixing allreduce cfg radix

src/components/tl/rccl/tl_rccl_lib.c
rename the get_lib_properties function in the tl/rccl component.
the get_lib_properties function had accidentally a wrong name, preventing dl_open of the the libucc_tl_rccl.so file.
=> TL/RCCL: fix function name to avoid dlopen error

src/components/ec/cuda/kernel/ec_cuda_executor.cu, test/gtest/core/test_mc_reduce.cc
- Fixes a bug that interverts `reduce_default` and `reduce_strided`  triggered operations in ec/cuda
- add in gtest the tests for triggered reduction operations
=> Fix bug in EC/CUDA and update Gtest

src/coll_patterns/recursive_knomial.h, src/coll_patterns/sra_knomial.h, src/components/tl/ucp/allgather/allgather.c, src/components/tl/ucp/allgather/allgather.h, src/components/tl/ucp/allgather/allgather_knomial.c, src/components/tl/ucp/allgather/allgather_ring.c, src/components/tl/ucp/allreduce/allreduce_knomial.c, src/components/tl/ucp/barrier/barrier_knomial.c, src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c, src/components/tl/ucp/scatter/scatter_knomial.c, src/components/tl/ucp/tl_ucp_coll.c, src/components/tl/ucp/tl_ucp_coll.h, test/gtest/coll/test_allgather.cc
Add knomial allgather algorithm to TL/UCP
Gives better performance for small message  comparing to existing ring algorithm in TL UCP
Porting changes from old PR https://github.com/openucx/ucc/pull/361, initially implemented by @vspetrov
=> TL/UCP: add knomial allgather

configure.ac, tools/info/build_info.c
Add information about configure options used to build ucc to ucc_info
example output:
```console
sergeyle@ubuntu:~/ucc/build-debug/install/bin$ ./ucc_info -b | grep UCC_CONFIGURE_FLAGS
#define UCC_CONFIGURE_FLAGS       "--prefix=/home/sergeyle/ucc/build-debug/install --with-ucx=/home/sergeyle/ucx//build-debug/install --with-mpi --without-cuda --without-sharp --enable-debug"
```
and
```console
sergeyle@ubuntu:~/ucc/build-debug/install/bin$ ./ucc_info -v
```
=> BUILD: add configure line to ucc info

test/mpi/main.cc
return an error if all tests have been skipped, this is most likely not the expected behavior and indicates a problem.
This issue came up when analyzing how the dlopen error with rccl tl has been missed by our CI. The reason turned out to be that the CI still returned SUCCESS despite of the rccl tl not being able to dlopen and execute correctly, but since no test formally 'failed' but all were skipped, no error code was returned.
=> TEST: return error if all tests skipped

src/core/ucc_lib.h, src/ucc/api/ucc.h
Revealing UCC version get function as part of UCC API
Moving ucc_get_version from ucc_lib.h to ucc.h
=> API: moving get version to ucc.h

docs/user_guide.md
Proposal for a UCC End User, e.g. developers of MPI applications, Guide.
Currently information about basic concepts like Team Layer, Collective Layer is scattered (FAQ, API Docs) and target for developers contributing to UCC or using UCC directly. Documentation for developers using UCC via e.g. an UCC enabled MPI stack is missing.
=> DOCS: added UCC User User Guide

.azure/azure-pipelines-pr.yml, src/coll_patterns/recursive_knomial.h, src/coll_patterns/sra_knomial.h, src/components/tl/ucp/allgather/allgather_knomial.c, src/components/tl/ucp/bcast/bcast.h, src/components/tl/ucp/bcast/bcast_knomial.c, src/components/tl/ucp/scatter/scatter_knomial.c, src/components/tl/ucp/tl_ucp_coll.h
Pull request contains multiple optimizations for TL/UCP broadcast
- Use knomial bcast for team size 2 for all message sizes. It doesn't make sense to use SAG bcast for 2 ranks since we can directly send whole message to single rank
- Knomial bcast
1. Wait for recv completion only to continue to the next iteration
- SAG bcast
1. Don’t send message to base root rank on each iteration in knomial allgather
2.Wait for recv completion only to continue to the next iteration
=> TL/UCP: bcast opt

config/m4/sharp.m4, src/components/tl/sharp/tl_sharp.c, src/components/tl/sharp/tl_sharp.h, src/components/tl/sharp/tl_sharp_context.c
- hide sharp lib errors
- disable lazy init by default
- removed hard coded sharp IB device.
- users are seeing sharp lib errors related to the application trying to contact sharp_am service but sharp is not enabled in the setup.
- sharp groups are limited resources and sharp team creation needs to know resource availability to avoid failure during the collective post.
=> TL/SHARP: SHARP OOB fixes

.azure/azure-pipelines-pr.yml, src/components/mc/base/ucc_mc_base.h, src/components/mc/cpu/mc_cpu.c, src/components/mc/cuda/mc_cuda.c, src/components/mc/rocm/mc_rocm.c, src/components/mc/ucc_mc.c, src/components/mc/ucc_mc.h, tools/perf/ucc_pt_coll.cc, tools/perf/ucc_pt_coll.h, tools/perf/ucc_pt_coll_allgather.cc, tools/perf/ucc_pt_coll_allgatherv.cc, tools/perf/ucc_pt_coll_allreduce.cc, tools/perf/ucc_pt_coll_alltoall.cc, tools/perf/ucc_pt_coll_alltoallv.cc, tools/perf/ucc_pt_coll_bcast.cc, tools/perf/ucc_pt_coll_gather.cc, tools/perf/ucc_pt_coll_gatherv.cc, tools/perf/ucc_pt_coll_reduce.cc, tools/perf/ucc_pt_coll_reduce_scatter.cc, tools/perf/ucc_pt_coll_reduce_scatterv.cc, tools/perf/ucc_pt_coll_scatter.cc, tools/perf/ucc_pt_coll_scatterv.cc, tools/perf/ucc_pt_op_memcpy.cc, tools/perf/ucc_pt_op_reduce.cc, tools/perf/ucc_pt_op_reduce_strided.cc
Add memset function to MC components and use it in ucc perftest to set initial value for src and dst buffers
Currently perftest doesn't initialize source and destination assuming we don't need to check correctness but performance only. Howerver OS might use some optimizations in this case, in particular it might map host buffer to zero page so performance results will be skewed.
=> MC: add memset function

src/components/tl/ucp/allgather/allgather.c, src/components/tl/ucp/allgather/allgather.h, src/components/tl/ucp/allgather/allgather_ring.c, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_coll.h, src/components/tl/ucp/tl_ucp_service_coll.c, src/components/tl/ucp/tl_ucp_team.c, src/components/topo/ucc_sbgp.c, src/components/topo/ucc_sbgp.h, src/core/ucc_context.c
Use topology information in TL UCP to reorder ranks so that ranks first grouped by node, by socket within node, by numa within socket. 
Permutation is used in TL UCP allgather to form better ring algorithm.
Performance data collected on N2 PPN48 (AMD EPYC 7443: 24 cores, 2 sockets, 8 NUMAs)
=> TL/UCP: ranks reordering

src/components/cl/hier/allreduce/allreduce_rab.c, src/components/cl/hier/allreduce/allreduce_split_rail.c, src/components/cl/hier/alltoallv/alltoallv.c, src/components/cl/hier/bcast/bcast_2step.c, src/components/tl/cuda/allgather/allgather_linear.c, src/components/tl/cuda/allgather/allgather_ring.c, src/components/tl/cuda/allgatherv/allgatherv_linear.c, src/components/tl/cuda/allgatherv/allgatherv_ring.c, src/components/tl/cuda/alltoall/alltoall_ce.c, src/components/tl/cuda/alltoallv/alltoallv_ce.c, src/components/tl/cuda/reduce_scatter/reduce_scatter_linear.c, src/components/tl/cuda/reduce_scatter/reduce_scatter_ring.c, src/components/tl/cuda/reduce_scatterv/reduce_scatterv_linear.c, src/components/tl/cuda/reduce_scatterv/reduce_scatterv_ring.c, src/components/tl/self/tl_self_coll.c, src/components/tl/sharp/tl_sharp_team.c, src/components/tl/ucp/allreduce/allreduce_sra_knomial.c, src/components/tl/ucp/bcast/bcast_sag_knomial.c, src/components/tl/ucp/tl_ucp_coll.h, src/schedule/ucc_schedule.c
A bug was reported by QA ([#3338436](https://redmine.mellanox.com/issues/3338436#change-25630566))
TL/UCP reduce_scatter and reduce_scatterv on CUDA using triggered mode cause a segfault. 
This is because `schedule->super.triggered_post` is not set on the schedule.
Since all the tasks must set `task.triggered_post=ucc_triggered_post`, this is done in `ucc_coll_task_init`.
Only TL/NCCL and TL/RCCL will overwrite this field.
=> CORE: fix bug for triggered colls in tl/ucp

tools/perf/ucc_pt_benchmark.cc, tools/perf/ucc_pt_coll.cc, tools/perf/ucc_pt_coll.h, tools/perf/ucc_pt_coll_allgather.cc, tools/perf/ucc_pt_coll_allgatherv.cc, tools/perf/ucc_pt_coll_allreduce.cc, tools/perf/ucc_pt_coll_alltoall.cc, tools/perf/ucc_pt_coll_alltoallv.cc, tools/perf/ucc_pt_coll_barrier.cc, tools/perf/ucc_pt_coll_bcast.cc, tools/perf/ucc_pt_coll_gather.cc, tools/perf/ucc_pt_coll_gatherv.cc, tools/perf/ucc_pt_coll_reduce.cc, tools/perf/ucc_pt_coll_reduce_scatter.cc, tools/perf/ucc_pt_coll_reduce_scatterv.cc, tools/perf/ucc_pt_coll_scatter.cc, tools/perf/ucc_pt_coll_scatterv.cc
Allows non zero root and root shift in perftest of rooted collectives
There was a segfault whenever root != 0 (or root shift) since buffers were being allocated only based on root == 0.
1. receives root from config instead of predefining as 0.
2. Allocation both src and dst buffers whenever there is a a root shift.
=> TOOLS: root and rootshift fix in perftest

src/utils/ucc_parser.c, src/utils/ucc_string.c, src/utils/ucc_string.h
ucs_string_find_in_list is not part of UCX 1.11 which breaks UCC build. Declare UCC native function ucc_string_find_in_list
=> BUILD: fix build with UCX 1.11

src/components/cl/hier/allreduce/allreduce_rab.c, src/components/cl/hier/bcast/bcast_2step.c, src/schedule/ucc_schedule.h, src/schedule/ucc_schedule_pipelined.c, src/schedule/ucc_schedule_pipelined.h, src/utils/ucc_coll_utils.c, test/gtest/coll/test_allreduce.cc
Fixes segfault in reduce allreduce broadcast hierarchical allreduce algorithm when pipelining is used
Also fixes coll trace print for pipelined schedules 
Pipeline fragment start dependency for sequential and ordered pipelines was set to previous fragment only hence completion of one fragment immediately triggers start of another fragment even if schedule is completed. This PR adds dependency on schedule start to prevent this.
=> CL/HIER: fix allreduce rab pipeline

src/core/ucc_coll.c, src/schedule/ucc_schedule.h
Fixes incorrect status for triggered tasks when using persistent mode
Running triggered tasks multiple times might result in incorrect status if trigger event is not immediately satisfied for second run and task keeps UCC_OK status from previous run. 
Set triggered tasks status to operation initialized in collective post function
=> CORE: fix triggered persistent coll status

src/components/cl/hier/allreduce/allreduce_split_rail.c, src/components/tl/cuda/reduce_scatter/reduce_scatter_linear.c, src/components/tl/cuda/reduce_scatterv/reduce_scatterv_linear.c
Fix CL HIER Split Rail Allreduce with TL CUDA
Fixes several bugs
1. CL HIER split rail algorithm doesn't provide correct buffer for inplace reduce scatter, it passes original rbuf with stairway patter rank offset
2. TL CUDA linear reduce scatter doesn't update rbuf pointer after fragment setup of pipelined schedule
=> TL/CUDA: fix pipelining in linear rs

src/components/tl/ucp/allgather/allgather_knomial.c, src/components/tl/ucp/allreduce/allreduce_knomial.c, src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
Iterate over peers in knomial groups with pairwise style loop
Better matching of send/recv pairs inside knomial group
=> TL/UCP: use pairwise pattern in knomial step

src/components/tl/sharp/tl_sharp_coll.c
TL SHARP checks that data type is supported before doing collective operation. This is not required for bcast since any ucc predefined datatype is contig.
=> TL/SHARP: enable bcast for any predefined dt

src/components/tl/mlx5/Makefile.am, src/components/tl/mlx5/tl_mlx5.h, src/components/tl/mlx5/tl_mlx5_context.c, src/components/tl/mlx5/tl_mlx5_pd.c, src/components/tl/mlx5/tl_mlx5_pd.h
[Replaces https://github.com/openucx/ucc/pull/523]
This PR implements 
1. `ib_ctx` and `pd` creation by each rank, during tl/mlx5 context init.
2. One rank per node shares its created `pd` and `ib_ctx` to the other ranks in the node. This is done during `ucc_tl_mlx5_context_create_epilog` (because we need the topo to access the node group `UCC_SBGP_NODE`).
Sharing the `ib_ctx` needs to share a file handle (`cmd_fd`) among the processes. This is done using `SCM_RIGHTS` through a Linux socket. The implementation (technical but standalone and standard) is done in a separate file `tl_mlx5_pd.c`.
=> TL/MLX5: share ib_ctx and pd

src/components/ec/rocm/kernel/ec_rocm_reduce.cu
resolving the compilation issue for overloading the multiplication operator for double and float hip complex type.
This PR resolves the compilation error for the ec_rocm_reduce.cu file. 
The compilation error is due to the use of hip complex/vector types with operators. This change in the hip compiler results in the "overloaded operator '*' is ambiguous" error at compilation time. 
The PR manually calls the appropriate operators for hip complex types and hence resolves the ambiguity of the overloaded multiplication operator.
=> EC/ROCM: PROD overload issue for HIP complex

src/components/ec/rocm/kernel/ec_rocm_reduce.cu
resolving the compilation issue for overloading the multiplication operator for double and float hip complex type.
(cherry picked from commit c2a50622bc822df48a9178b09fab2eec0d88d31a)
=> EC/ROCM: Prod overload issue for HIP complex -v1.2.x

src/components/tl/sharp/tl_sharp_team.c
Don't print error if sharp group create failed, decrease log level to debug.
It's happening when there are no available OSTs
=> TL/SHARP: dont print team create error

src/components/tl/ucp/scatter/scatter_knomial.c, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_coll.h, src/utils/ucc_parser.h
Adding configuration parameter for knomial scatter algorithm (part of scatter allgather broadcast) to receive data directly into destination buffer and avoid memory copy as a last step of the algorithm
Improves performance of large message broadcast. By default enabled only for GPU collective
=> TL/UCP: avoid copy in knomial scatter

src/components/tl/mlx5/Makefile.am, src/components/tl/mlx5/tl_mlx5.h, src/components/tl/mlx5/tl_mlx5_dm.c, src/components/tl/mlx5/tl_mlx5_dm.h, src/components/tl/mlx5/tl_mlx5_team.c, src/components/tl/mlx5/tl_mlx5_wqe.c, test/gtest/tl/mlx5/test_tl_mlx5.h, test/gtest/tl/mlx5/test_tl_mlx5_wqe.cc, test/gtest/tl/mlx5/test_tl_mlx5_wqe.h
Implements device memory allocation and update the gtests
Also add topo init at team creation
=> TL/MLX5: device memory and topo init

src/coll_score/ucc_coll_score.c, src/coll_score/ucc_coll_score.h, src/components/cl/basic/cl_basic_team.c, src/components/cl/hier/cl_hier_team.c, src/components/tl/cuda/tl_cuda_team.c, src/components/tl/mlx5/tl_mlx5_team.c, src/components/tl/nccl/tl_nccl_team.c, src/components/tl/rccl/tl_rccl_team.c, src/components/tl/self/tl_self_team.c, src/components/tl/sharp/tl_sharp_team.c, src/components/tl/ucp/tl_ucp_team.c, test/gtest/coll_score/test_score_update.cc
Fixes ucc score table when user provides score for TL/CL and only total score is given
e.g. UCC_TL_SHARP_TUNE=inf results in scatter, allgather, alltoall collectives (not supported by sharp) in UCC score table
<details>
<summary>with fix</summary>
```bash
ucc_team.c:471  UCC  INFO  ===== COLL_SCORE_MAP (team_id 32768, size 2) =====
ucc_coll_score_map.c:201  UCC  INFO  Allgather:
ucc_coll_score_map.c:201  UCC  INFO        Host: {0..4095}:TL_UCP:10 {4K..inf}:TL_UCP:10
ucc_coll_score_map.c:201  UCC  INFO  Allgatherv:
ucc_coll_score_map.c:201  UCC  INFO        Host: {0..inf}:TL_UCP:10
ucc_coll_score_map.c:201  UCC  INFO  Allreduce:
ucc_coll_score_map.c:201  UCC  INFO        Host: {0..4095}:TL_SHARP:10 {4K..inf}:TL_SHARP:10
ucc_coll_score_map.c:201  UCC  INFO        Cuda: {0..inf}:TL_SHARP:10 …
```
=> CORE: fix score update when only score given

src/components/tl/nccl/tl_nccl.h, src/components/tl/nccl/tl_nccl_team.c, test/mpi/test_mpi.cc
Make nccl team create non blocking
All UCC TL's team create are supposed to be non blocking, but TL/NCCL was using old NCCL API which was blocking.
Updated blocking ncclCommInitRank() to non blocking ncclCommInitRankConfig()
=> TL/NCCL: make team init non blocking

src/components/tl/nccl/tl_nccl_team.c
Add support for UCC_MEMORY_TYPE_CUDA_MANAGED in tl/nccl.
Add to list of supported memory types in tl/nccl team score.
=> TL/NCCL: add cuda managed to score

src/coll_patterns/recursive_knomial.h, src/components/tl/ucp/allreduce/allreduce_knomial.c, src/components/tl/ucp/allreduce/allreduce_sra_knomial.c, src/components/tl/ucp/bcast/bcast_sag_knomial.c, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_coll.h, src/components/tl/ucp/tl_ucp_lib.c, src/components/tl/ucp/tl_ucp_team.c, src/components/topo/ucc_sbgp.c, src/components/topo/ucc_sbgp.h, src/components/topo/ucc_topo.c, src/components/topo/ucc_topo.h
Adding auto (sub) optimal radix calculation to be used for Allreduce SRA and Bcast SAG inside TL/UCP.
To improve performance when degredation caused by extra ranks.
Calculates the radix which minimizes extra ranks per team size.
Additionally makes sure that radix wont be larger then socket size (across all nodes), to also minimize cross socket communication.
=> TL/UCP: opt radix alg

src/utils/ucc_coll_utils.c, src/utils/ucc_coll_utils.h, test/mpi/test_mpi.cc
Don't check reduction datatype support if collective is not reduction
Barrier tests are skip due to incorrect reduction check
=> TEST: fix barrier test

src/components/tl/mlx5/Makefile.am, src/components/tl/mlx5/mcast/tl_mlx5_mcast.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_coll.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_coll.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_context.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c, src/components/tl/mlx5/tl_mlx5.h, src/components/tl/mlx5/tl_mlx5_coll.c, src/components/tl/mlx5/tl_mlx5_coll.h, src/components/tl/mlx5/tl_mlx5_context.c, src/components/tl/mlx5/tl_mlx5_team.c
TL/MLX5/MCAST: multicast-related changes to mlx5 files WIP
Implementing HW MCAST in UCC
FYI @janjust @Sergei-Lebedev
=> TL/MLX5: adding mcast interface 

test/gtest/Makefile.am, test/gtest/core/test_mc_rocm.cc, test/mpi/Makefile.am
propagate the HIP_CXXFLAGS correctly to gtest and test_ucc_mpi compilation. In addition, compiling with the gnu++17 flag revealed some errors due to unhandled return values. This commit fixes this issue as well (without introducing the gnu++17 flag at this point).
=> TEST: propagate HIP_CXXFLAGS to gtest and mpi

src/components/tl/mlx5/Makefile.am, src/components/tl/mlx5/alltoall/alltoall.c, src/components/tl/mlx5/alltoall/alltoall.h, src/components/tl/mlx5/alltoall/alltoall_mkeys.c, src/components/tl/mlx5/alltoall/alltoall_mkeys.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_context.c, src/components/tl/mlx5/tl_mlx5.c, src/components/tl/mlx5/tl_mlx5.h, src/components/tl/mlx5/tl_mlx5_coll.h, src/components/tl/mlx5/tl_mlx5_ib.c, src/components/tl/mlx5/tl_mlx5_team.c, src/core/ucc_service_coll.h
=> TL/MLX5: a2a part 1 -- coll init

.ci/scripts/run_tests_ucc_mpi.sh
Disable UCX cuda_ipc transport for some tests.
There is known issue when TL CUDA and cuda_ipc transport used together. They might try to register same memory twice and as a result either UCX or UCC aborts.
see for more details https://github.com/openucx/ucx/issues/3192
=> TEST: disable cuda_ipc in ucx

test/gtest/coll/test_alltoall.cc
In gtest alltoall onesided test when running with memory type cuda, sbuf and rbuf memory types are set to cuda but in practice use team->procs[i].p->onesided_buf which are allocated as host memory buffers during create_ context().
Bug fix
In this onesided case using  onesided buffers from context, set sbuf and rbuf mem type to be host.
=> TEST: fix alltoall onesided buf mt

src/components/tl/sharp/tl_sharp_context.c, src/core/ucc_coll.c, src/core/ucc_context.c, src/core/ucc_lib.c, src/utils/ucc_coll_utils.c
Coverity high level error fixes
=> CORE: coverity fixes

src/components/tl/nccl/allgatherv/allgatherv.c, src/components/tl/nccl/tl_nccl.c, src/components/tl/nccl/tl_nccl.h, src/components/tl/nccl/tl_nccl_coll.c, src/components/tl/nccl/tl_nccl_context.c, src/components/tl/nccl/tl_nccl_team.c
check nccl status after using ncclGroupEnd , as well as for ncclSend/ncclRecv if they are called outside of ncclGroupStart/End.
To fit nb change from using ncclCommInitRankConfig from PR #772
=> TL/NCCL make ncclGroupEnd nb

src/components/tl/mlx5/Makefile.am, src/components/tl/mlx5/alltoall/alltoall.c, src/components/tl/mlx5/alltoall/alltoall.h, src/components/tl/mlx5/alltoall/alltoall_coll.c, src/components/tl/mlx5/alltoall/alltoall_inline.h, src/components/tl/mlx5/tl_mlx5_coll.c, src/components/tl/mlx5/tl_mlx5_coll.h, src/components/tl/mlx5/tl_mlx5_context.c, src/components/tl/mlx5/tl_mlx5_dm.c, src/components/tl/mlx5/tl_mlx5_pd.c, src/components/tl/mlx5/tl_mlx5_team.c, test/gtest/tl/mlx5/test_tl_mlx5_wqe.h
alltoall full implementation
On top of #790
=> TL/MLX5: a2a part2 -- full collective

src/coll_patterns/recursive_knomial.h
Coverity "medium" issue - infinite loop fix.
fs can exceed type ucc_kn_radix_t since it is continuously multiplied by radix r.
make fs of type ucc_rank_t similar to team_size which while loop is blocked by.
=> CORE: fix kn loop coverity

src/components/mc/cuda/mc_cuda.c, src/components/tl/cuda/allgatherv/allgatherv_linear.c, src/components/tl/cuda/alltoallv/alltoallv_ce.c, src/components/tl/cuda/tl_cuda_cache.c, src/components/tl/mlx5/alltoall/alltoall.c, src/components/tl/mlx5/alltoall/alltoall_mkeys.c, src/components/tl/mlx5/tl_mlx5_context.c, src/components/tl/self/tl_self_coll.c, src/components/tl/ucp/allgather/allgather_knomial.c, src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
Additional coverity "high" issue fixes
Found once cuda/mlx5/nccl/sharp were added to coverity checks.
=> CORE: additional coverty fixes

src/coll_patterns/recursive_knomial.h, src/coll_patterns/sra_knomial.h, src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c, src/utils/ucc_dt_reduce.h, test/mpi/test_case.cc
Avoid memory copy in last step of reduce scatter.
In last step of reduce scatter local reduce operation is split into strided reduce of received data and reduce of result of that operation and local data.
=> TL/UCP: remove memcpy in last SRA step

test/mpi/main.cc
Fixes summary calc for ucc_test_mpi
Different ranks might execute different number of tests, e.g. if odd_even team split is used and initial world size is odd number.
internal issue https://redmine.mellanox.com/issues/3477397
=> TEST: fix summary calculation in test_mpi

src/components/tl/ucp/allgatherv/allgatherv.c, src/components/tl/ucp/allgatherv/allgatherv.h, src/components/tl/ucp/allgatherv/allgatherv_ring.c
Add ranks reordering to allgatherv ring
Improves performence
Sets rank in contiguous manner to exchange as much data as possible between ranks within the same node, minimizing cross node data exchange.
=> TL/UCP: add ranks reordering to allgatherv

src/components/cl/hier/cl_hier_team.c, src/components/mc/base/ucc_mc_base.h, src/components/mc/cpu/mc_cpu.c, src/components/mc/cuda/mc_cuda.c, src/components/mc/cuda/mc_cuda.h, src/components/mc/rocm/mc_rocm.c, src/components/mc/ucc_mc.c, src/components/tl/nccl/allgatherv/allgatherv.h, src/core/ucc_coll.c, test/gtest/coll/test_allgather.cc, test/gtest/coll/test_allgatherv.cc, test/gtest/coll/test_allreduce.cc, test/gtest/coll/test_alltoall.cc, test/gtest/coll/test_alltoallv.cc, test/gtest/coll/test_bcast.cc, test/gtest/coll/test_gather.cc, test/gtest/coll/test_gatherv.cc, test/gtest/coll/test_reduce.cc, test/gtest/coll/test_reduce_scatter.cc, test/gtest/coll/test_reduce_scatterv.cc, test/gtest/coll/test_scatter.cc, test/gtest/coll/test_scatterv.cc, test/gtest/core/test_mc_reduce.cc, test/gtest/utils/test_parser.cc, test/mpi/buffer.cc, test/mpi/main.cc
Adding support for memory type cudaManaged across UCC.
=> MC/CUDA: add mc managed and tests

src/components/tl/mlx5/alltoall/alltoall.c, src/components/tl/mlx5/alltoall/alltoall.h, src/components/tl/mlx5/tl_mlx5.h, src/components/tl/mlx5/tl_mlx5_coll.c, src/components/tl/mlx5/tl_mlx5_context.c, src/components/tl/mlx5/tl_mlx5_dm.c, src/components/tl/mlx5/tl_mlx5_ib.c, src/components/tl/mlx5/tl_mlx5_pd.c, src/components/tl/mlx5/tl_mlx5_team.c
Revise TL/MLX5 context and team init.
- Allow other collective to run if a2a setup fails
- Handling device memory allocation error, and other errors happening during team alltoall init
- allocate device memory atomics before device memory pool
- change setup/cleanup error log to debug log
Along the way, we fix two important bugs
- fix pd deallocation https://redmine.mellanox.com/issues/3558239
- fix socket closing https://redmine.mellanox.com/issues/3564403
=> TL/MLX5: revise team and ctx init

src/components/tl/ucp/alltoallv/alltoallv_hybrid.c
Fix check for sparse format in hybrid alltoallv
internal issue https://redmine.mellanox.com/issues/3492139
=> TL/UCP: fix sparse pack in hybrid a2av

src/components/tl/mlx5/tl_mlx5_context.c, src/components/tl/mlx5/tl_mlx5_pd.c
fix memory leak [Coverity® :: ucc :: Outstanding Issues :: Issue 628230 (mellanox.com)](https://coverity.mellanox.com/reports.htm#v20248/p10129/fileInstanceId=222742904&defectInstanceId=95022912&mergedDefectId=628230)
The socket handle used for pd sharing was not saved on the client side, and so could not be closed.
=> TL/MLX5: fix client's socket closing

src/components/tl/ucp/Makefile.am, src/components/tl/ucp/allgather/allgather.c, src/components/tl/ucp/allgather/allgather.h, src/components/tl/ucp/allgather/allgather_neighbor.c, src/components/tl/ucp/tl_ucp_coll.c, src/components/tl/ucp/tl_ucp_coll.h, test/gtest/coll/test_allgather.cc
Implementation of Neighbor Exchange Allgather algorithm described in this paper: https://ieeexplore.ieee.org/document/1592302
Based on original implementation from OpenMPI: https://github.com/open-mpi/ompi/blob/8514e717215a42ddb6db065c3baae3a2779a072a/ompi/mca/coll/base/coll_base_allgather.c#L624
According to mentioned paper: ` For the TCP/IP protocol, an algorithm that incorporates pair-wise exchange is the best for minimizing TCP/IP traffic ` and this algorithm require **N / 2** steps instead of **N - 1** like in ring.
=> The Neighbor Exchange Algorithm for Allgather

src/components/tl/sharp/tl_sharp_context.c, src/core/ucc_context.c
Fix some bugs in the core dealing with context create epilog error handling
=> CORE: fix error handling for ctx create epilog

src/components/tl/ucp/allgather/allgather_ring.c
fix a memory corruption in the error path
=> TL/UCP: fix in allgather ring

src/Makefile.am, src/utils/arch/cpu.h, src/utils/arch/riscv64/cpu.h
Enables support for RISC-V (64-bit)
UCX has recently gained support for this architecture so it would be nice to add UCC support
The changes needed to support just consist of implementing the fence functions using the fence instructions - the ones used here match added to UCX.
=> UTIL: Add riscv64 support

src/components/tl/ucp/reduce_scatter/reduce_scatter_ring.c, src/components/tl/ucp/reduce_scatterv/reduce_scatterv_ring.c, src/utils/ucc_coll_utils.c, src/utils/ucc_coll_utils.h, test/gtest/utils/test_ep_map.cc
Add reordering ranks to reduce_scatter ring and reduce_scatterv ring 
Better performance
Mapping ranks to first send messages within the same node
**Note:** in case of bidirectional, we need 2 use both mappings of reverse and reorder consecutively.
=> TL/UCP: add reorder ranks to reduce_scatter

src/components/tl/mlx5/Makefile.am, src/components/tl/mlx5/mcast/p2p/ucc_tl_mlx5_mcast_p2p.c, src/components/tl/mlx5/mcast/p2p/ucc_tl_mlx5_mcast_p2p.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_coll.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_rcache.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_rcache.h
TL/MLX5: adding rcache and a p2p library for mcast
@janjust
=> TL/MLX5: rcache and p2p lib for mcast

src/components/tl/sharp/tl_sharp_context.c
avoid calling sharp_context cleanup with context:NULL, when context creat is a failed
regression from https://github.com/openucx/ucc/pull/818
=> TL/SHARP: Fix sharp context cleanup

src/components/ec/cuda/kernel/ec_cuda_half_sm52.h
half datatype binary operators are not supported by cuda arch below 5.3 hence UCC does it in 3 steps: convert half to float, do float operation, convert float back to half. Since CUDA 12.2 this was added as part of standard distribution which breaks compilation. This PR adds relevant fix for it
=> EC/CUDA: fix build with 12.2 and older arch

.github/workflows/clang-tidy-rocm.yaml
The hip header file generates a warning when compiled with clang, which in itself is harmless, but because all warnings are treated as errors, the compilation fails in the UCX step. Compile UCX with gcc instead of clang (since we are not truly interested in running clang-tidy on ucx in this CI, but just on UCC)
Furthermore, force using rocm 5.6.1 for now instead of the most recent rocm release, since rocm-5.7 would require clang-14
=> TEST: use gcc to compile UCX in clang-tidy-rocm

src/components/ec/cpu/ec_cpu_reduce.c
=> EC/CPU: fix error message

src/components/tl/ucp/allgather/allgather_knomial.c, src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c
Add reorder ranks in for Allreduce SRA
Performance benfit, especialy when n_extra ranks > 0, in which case we do a complete allreduce between "proxy" and "extra" ranks and if they are on the same node this significantly improves perf.
By reordring ranks in each step:  reduce_scatter_knomial, allgather_knomial.
**Note:** allgather_knomial is used also for small message allgather and large message bcast (bcast SAG). In these cases reorder ranks will not be used, it is currently only implemented for the usage within allreduce SRA.
=> TL/UCP: reorder ranks for SRA

config/m4/rccl.m4
Re-ordering CPPFLAGS and LDFLAGS to prioritize RCCL installation path over ROCM/HIP installation path for ncclCommInitRank check.
Pre-installed RCCL libraries and header files can exist in the ROCm installation path, with features (like BFD) that are not supported by all platforms. When checking for ncclCommInitRank during UCC configure, the current order chooses these pre-installed RCCL files in the ROCm installation path (if found in the path by `--with-rocm`) over custom-built files in the RCCL installation path (as pointed by `--with-rccl`). This fix prioritizes files in the RCCL installation path over ROCm installation path.
@edgargabriel
=> BUILD: re-order m4 flags for RCCL

src/components/tl/nccl/tl_nccl_coll.c, src/core/ucc_coll.c, src/core/ucc_lib.c, src/core/ucc_lib.h, src/schedule/ucc_schedule.c, src/utils/ucc_coll_utils.c, tools/perf/ucc_pt_benchmark.cc
Skip collective if size is zero
=> CORE: skip zero size collectives

test/mpi/main.cc
Currently, when running mpi test, onesided tests will be performed regardless of the user specifically setting a non-onesided test to perform. For example,
`mpirun -np 2 ucc_test_mpi -c allreduce`
Will perform both allreduce tests and onesided alltoall tests, which is not correct.
=> TEST: fix one-sided tests always running

src/components/mc/rocm/mc_rocm.c
- Adds condition based on HIP_VERSION for using `type` instead of `memoryType` in `hipPointerAttribute_t`.
- Adds switch case for `hipMemoryTypeManaged`
- From ROCm 5.5 onwards, `memoryType` is deprecated and `type` is used instead in `hipPointerAttribute_t`.
- From ROCm 5.7.1 onwards, `hipMallocManaged` pointers return `hipMemoryTypeManaged` instead of `hipMemoryTypeHost`.
=> MC/ROCM: ROCm compatibility fixes

src/components/tl/mlx5/Makefile.am, src/components/tl/mlx5/mcast/tl_mlx5_mcast.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_coll.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_progress.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c, src/components/tl/mlx5/tl_mlx5.h
TL/MLX5: multicast design: adding helper.h, progress.h, and mcast.h
=> TL/MLX5: multicast design: adding helper.h, progress.h, and mcast.h

src/components/tl/ucp/tl_ucp_context.c
Name UCP context for debug purposes 
While debugging UCX configs, we might have additional UCP context, from MPI for example. Naming our UCP context will aid in identifying the UCC context.
UCP has built-in mechanism ready for that purpose.
=> TL/UCP: Name UCP Context for Debug

src/utils/ucc_parser.h
Fix UCC parser documentation
In src/schedule/ucc_schedule_pipelined.c, ucc_pipeline_order_names - correct command is sequential
Fix UCC parser documentation
=> UTIL: Fix in parser serial to sequential

src/components/tl/mlx5/tl_mlx5_team.c
fixes issue [#3607520](https://redmine.mellanox.com/issues/3607520#change-28612134)
=> TL/MLX5: fix subset for service coll

src/utils/ucc_coll_utils.c, tools/perf/ucc_pt_benchmark.cc, tools/perf/ucc_pt_coll.h, tools/perf/ucc_pt_coll_allgather.cc, tools/perf/ucc_pt_coll_allgatherv.cc, tools/perf/ucc_pt_coll_allreduce.cc, tools/perf/ucc_pt_coll_alltoall.cc, tools/perf/ucc_pt_coll_alltoallv.cc, tools/perf/ucc_pt_coll_bcast.cc, tools/perf/ucc_pt_coll_gather.cc, tools/perf/ucc_pt_coll_gatherv.cc, tools/perf/ucc_pt_coll_reduce.cc, tools/perf/ucc_pt_coll_reduce_scatter.cc, tools/perf/ucc_pt_coll_reduce_scatterv.cc, tools/perf/ucc_pt_coll_scatter.cc, tools/perf/ucc_pt_coll_scatterv.cc, tools/perf/ucc_pt_config.cc, tools/perf/ucc_pt_config.h
Add support for testing persistent collective in ucc_perftest
=> TOOLS: add persistent colls to perftest

test/mpi/test_mpi.h
Add onesided context progress in ucc_test_mpi
Onesided alltoall uses atomic operations for which completion is not known at sender side so ucc_context_progress is required even if alltoall completed locally.
Fixes issue [internal link](https://redmine.mellanox.com/issues/3656866)
=> TEST: fix onesided test progress

src/components/cl/hier/alltoallv/alltoallv.c
Disable onesided alltoallv in CL HIER.
Fixes CI failure after https://github.com/openucx/ucc/pull/832 was merged
=> CL/HIER: disable onesided alltoallv

src/components/tl/mlx5/Makefile.am, src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.h, src/components/tl/mlx5/tl_mlx5.c, src/utils/ucc_compiler_def.h
TL/MLX5: adding ip over ib mcast helper functions as well as some of the environment variables
=> TL/MLX5/MCAST: adding ip over ib mcast helper functions as well as some of the environment variables

src/components/tl/ucp/alltoall/alltoall.c, src/components/tl/ucp/alltoall/alltoall_bruck.c, src/components/tl/ucp/tl_ucp_coll.h
Adding support for non-host buffers in TL/UCP alltoall bruck algorithm
Improves performance for small msg alltoall
=> TL/UCP: add support for non host buffers in bruck alltoall

test/gtest/core/test_mc_reduce.cc
Fixes gtest hangs in Jenkins. Memory copy might hang if persistent kernel is running
=> TEST: fix memcopy after kernel launch

.github/workflows/clang-tidy-nvidia.yaml, src/components/tl/mlx5/tl_mlx5_context.c, src/components/tl/mlx5/tl_mlx5_pd.c, src/components/tl/mlx5/tl_mlx5_team.c
Fix hanging in TL MLX5 context create.
PD_OWNER_RANK doesn't start service bcast If no IB devices found, other ranks hang in sbcast waiting for PD_OWNER_RANK
=> TL/MLX5: fix context create hang

src/coll_patterns/double_binary_tree.h, src/components/tl/ucp/bcast/bcast_dbt.c
Fix compile warnings when building dbt broadcast with nvc compiler in HPC SDK
=> TL/UCP: fix dbt to build with hpcsdk

src/components/tl/sharp/tl_sharp_context.c, src/components/tl/ucp/allgather/allgather.c, src/components/tl/ucp/allgather/allgather_ring.c, src/ucc/api/ucc.h, src/utils/ucc_coll_utils.c, src/utils/ucc_coll_utils.h
Use allgather ring algorithm instead of neighbor exchange if ranks reordering is needed
=> TL/UCP: use ring allgather when reordering needed

test/mpi/test_case.cc
Progress UCC context while doing skip reduce test
Avoid potential lock due to blocking allreduce
=> TEST: progress ucc context during skip reduce

src/components/mc/cuda/mc_cuda.c, src/components/mc/cuda/mc_cuda.h, src/components/mc/ucc_mc.c
Add prealocated cuda managed memory to MC CUDA
Speeds up managed memory allocation when it's required as scratch space for some collectives
=> MC/CUDA: add mpool for managed memory

src/utils/ucc_coll_utils.h, src/utils/ucc_log.h, test/mpi/main.cc, test/mpi/test_mpi.cc, test/mpi/test_mpi.h
Add more information to ucc_test_mpi output
UCC master:
This PR:
=> TEST: improve test output

tools/perf/ucc_pt_coll.cc, tools/perf/ucc_pt_cuda.cc, tools/perf/ucc_pt_cuda.h
Add CUDA memory allocation function to ucc_perftest
Result of perftest might be biased due to use of internal memory pool in UCC.
=> TOOLS: use separate cuda alloc in perftest

src/components/tl/mlx5/mcast/tl_mlx5_mcast_context.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c
TL/MLX5: adding mcast helper functions
=> TL/MLX5: adding mcast helper functions

src/coll_patterns/double_binary_tree.h, src/components/tl/ucp/Makefile.am, src/components/tl/ucp/allreduce/allreduce.c, src/components/tl/ucp/allreduce/allreduce.h, src/components/tl/ucp/allreduce/allreduce_dbt.c, src/components/tl/ucp/bcast/bcast_sag_knomial.c, src/components/tl/ucp/reduce/reduce.c, src/components/tl/ucp/reduce/reduce.h, src/components/tl/ucp/reduce/reduce_dbt.c, src/components/tl/ucp/tl_ucp_coll.c, src/components/tl/ucp/tl_ucp_coll.h, test/gtest/coll/test_allreduce.cc, test/gtest/coll/test_reduce.cc
Rework of https://github.com/openucx/ucc/pull/850
=> TL/UCP: reduce dbt

config/m4/ucx.m4, src/components/ec/cuda/Makefile.am, src/components/ec/cuda/ec_cuda.c, src/components/ec/cuda/ec_cuda.h, src/components/ec/cuda/ec_cuda_executor.c, src/components/ec/cuda/ec_cuda_executor_interruptible.c, src/components/ec/cuda/ec_cuda_executor_persistent.c, src/components/ec/cuda/ec_cuda_resources.c, src/components/ec/cuda/ec_cuda_resources.h, src/components/ec/ucc_ec.c, src/components/mc/cuda/Makefile.am, src/components/mc/cuda/mc_cuda.c, src/components/mc/cuda/mc_cuda.h, src/components/mc/cuda/mc_cuda_resources.c, src/components/mc/cuda/mc_cuda_resources.h, src/components/tl/ucp/reduce/reduce_dbt.c, src/core/ucc_constructor.c, src/core/ucc_global_opts.h, src/utils/arch/cuda_def.h, src/utils/ucc_parser.h
Change EC/CUDA and MC/CUDA resource allocation logic to support multiple CUDA contexts. CUDA components keep tack of resources used by TLs or CLs and allocate memory, stream, events etc using appropriate CUDA context.
Adds support for multithreaded CUDA application. Each thread represent UCC endpoint and manages dedicated GPU
=> EC/CUDA: enable support for multiple contexts

src/components/tl/mlx5/mcast/tl_mlx5_mcast_rcache.c, src/components/tl/mlx5/tl_mlx5_rcache.c, src/components/tl/sharp/tl_sharp_context.c, src/utils/ucc_rcache.h
Use ucs_rcache_set_default_params to preinit rcache params.
Some fields of rcache params left uninitialized.
=> UTIL: properly init rcache params

config/m4/rocm.m4, cuda_lt.sh
Adding support for clang-based build with ROCm 6.0 and above
AMD plans to switch from `hipcc` to `clang` as its default compiler for ROCm 6.0 and above.
=> BUILD: added support for amdclang-based build

src/components/tl/mlx5/Makefile.am
Fix Makefile.am add librdmacm dependencies
Fixes several discovered bugs and showstoppers:
https://redmine.mellanox.com/issues/3752155
http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/qa_sharp/scratch/ucc/20240123_172600_774704_13631_r-hpc-gpu03/
https://redmine.mellanox.com/issues/3403021
=> TL/MLX5: add librdmacm linkage

src/components/topo/ucc_sbgp.c
Add check if reordering is required before computing it.
Previous version of rank reordering algorithm is based on host hash, socket id and numa id. This algorithm can't detect if reordering is required and sometimes might generate permutation that mixes nodes but not ranks within node. Even though such permutation is equivalent to "no ordering" it still disables some algorithms (e.g. neighbor exchange allgather).
=> TOPO: fix rank reordering for host ordered sbgp

src/components/tl/ucp/allreduce/allreduce.c
This PR updates the ID field of `ucc_tl_ucp_allreduce_algs` in `src/components/tl/ucp/allreduce/allreduce.c`. The incorrect ID `UCC_TL_UCP_ALLREDUCE_ALG_SRA_KNOMIAL` has been replaced with the correct `UCC_TL_UCP_ALLREDUCE_ALG_DBT`.
The change addresses a bug where the ID field of `UCC_TL_UCP_ALLREDUCE_ALG_DBT` was mistakenly set to `UCC_TL_UCP_ALLREDUCE_ALG_SRA_KNOMIAL`. This fix ensures that the ID accurately reflects the corresponding algorithm, aligning with the intended design and improving the functionality of the component.
The fix was straightforward - the incorrect ID in the specified file was simply replaced with the correct ID. This ensures that the `UCC_TL_UCP_ALLREDUCE_ALG_DBT` is now accurately represented in the system.
=> TL/UCP: bugfix in allreduce dbt

src/components/tl/cuda/tl_cuda_team.c
Fix seg fault in cuda team cleanup because of garbage pointer in cuda scratch rem buffer.
=> TL/CUDA: initialize remote cuda scratch to NULL

config/m4/rocm.m4, cuda_lt.sh
Signed-off-by: nileshnegi <Nilesh.Negi@amd.com>
(cherry picked from commit 1bfa3f3ff9c504a434643ca9df4f615dda8b42dd)
Adding support for clang-based build with ROCm 6.0 and above
AMD plans to switch from hipcc to clang as its default compiler for ROCm 6.0 and above.
=> BUILD: added support for amdclang-based build (#899) (v1.3.x) 

config/m4/ucx.m4, src/utils/ucc_parser.h
Porting https://github.com/openucx/ucc/pull/895https://github.com/openucx/ucc/pull/895 to v1.3
=> BUILD: fix ucs parser set value (#895)

src/components/tl/mlx5/Makefile.am
(cherry picked from commit c8385d176037ef0f9e9f381102adcc5b1857d8a9)
Signed-off-by: Tomislav Janjusic <tomislavj@nvidia.com>
=> TL/MLX5: ad librdmacm linkage (#905)

cuda_lt.sh
- Modified GPU architecture flags for compatibility with AMD GPUs.
- Add `-O3` for improving performance.
Incompatibility between explicitly specified GPU arch flags (like `--target-offload=gfx90a:xnack+`) and `--target-offload=native` led to build errors on some AMD GPUs.
=> BUILD: fix GPU arch flags in amdclang build

src/components/tl/ucp/tl_ucp.c
Change default radix for TL/UCP barrier to 8
Better perf for OOB
=> TL/UCP: adjust barrier radix

src/components/cl/hier/cl_hier_team.c, src/components/ec/cuda/ec_cuda.c, src/components/mc/cuda/mc_cuda.c, test/mpi/main.cc
Add check to CL/HIER to prevent SBGP TL list overflow.
For some systems CL/HIER might try to use more than 4 TLs per SBGP. 4 is compile time constant. Fixes bug https://redmine.mellanox.com/issues/3767158
Ignore TLs if the list already full. Filter out TLs if we know in advance that SBGP size is not supported.
=> CL/HIER: check number of TLs per SBGP

src/ucc/api/ucc.h
Remove duplicate ucc_get_version_string from ucc.h. Fixes https://github.com/openucx/ucc/issues/913
=> API: remove duplicate get_version_string

src/components/tl/mlx5/mcast/tl_mlx5_mcast.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_context.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c, src/components/tl/mlx5/tl_mlx5.c, src/components/tl/mlx5/tl_mlx5.h, src/components/tl/mlx5/tl_mlx5_context.c, src/components/tl/mlx5/tl_mlx5_team.c
adding the states regarding the team creation and mcast group join
=> TL/MLX5: complete the mcast init

cuda_lt.sh
Signed-off-by: nileshnegi <Nilesh.Negi@amd.com>
(cherry picked from commit c1734db1b2bc9ffeba5d17b3e81e1a9425dee100)
- Modified GPU architecture flags for compatibility with AMD GPUs.
- Add `-O3` to improve performance.
Incompatibility between explicitly specified GPU arch flags (like `--target-offload=gfx90a:xnack+`) and `--target-offload=native` led to build errors on some AMD GPUs.
=> BUILD: fix GPU arch flags in amdclang build (#914) (v1.3.x)

src/coll_score/ucc_coll_score.c, src/coll_score/ucc_coll_score.h, src/coll_score/ucc_coll_score_map.c, src/components/cl/hier/cl_hier.h, src/components/cl/hier/cl_hier_team.c
Update score of CL HIER collectives only if collective is supported. list 
If CL HIER score provided doesn't set collective we shouldn't set score for unsupported collectives. Fixes https://redmine.mellanox.com/issues/3710358
=> CL/HIER: change score only for supported colls

src/components/tl/ucp/bcast/bcast_dbt.c, src/components/tl/ucp/reduce/reduce_dbt.c, src/core/ucc_context.c, src/core/ucc_context.h, src/core/ucc_progress_queue.h, src/core/ucc_progress_queue_mt.c, src/core/ucc_progress_queue_st.c
Add progress throttle to ucc_context_progress()
Point to point benchmarks might be affected by ucc_context_progress() even though collectives are not used there. Progress throttle helps to save cycles and not calling ucp_worker_progress (in TL UCP) if there are no active collective requests.
=> CORE: add progress throttle

src/components/tl/ucp/Makefile.am, src/components/tl/ucp/allgather/allgather.c, src/components/tl/ucp/allgather/allgather.h, src/components/tl/ucp/allgather/allgather_bruck.c, src/components/tl/ucp/tl_ucp_coll.c, src/components/tl/ucp/tl_ucp_coll.h, test/gtest/coll/test_allgather.cc
Implementation of Bruck algorith for allgather collective.
This algorith has O(long(N)) complexity and shows great performance on small (1-2Kb) messages (according to research: https://arxiv.org/pdf/2109.08751.pdf)
=> TL/UCP: Allgather Bruck algorithm 

src/components/ec/cpu/ec_cpu.c, src/components/ec/cpu/ec_cpu.h, src/components/ec/cpu/ec_cpu_reduce.c
This PR is an extension to https://github.com/openucx/ucc/pull/918.
Sergey had found through testing that while the previous patch worked for newer versions of gcc, the gcc version we use for testing HPCX (gcc 4.8.2) still wasn't auto-vectorizing int8 reductions. The problem was that the last patch did not also move the destination vector into the `ucc_ec_cpu_reduce` function's arguments as a `restrict` pointer. This patch fixes that.
In short, char/int8 datatypes are special to the compiler in that they can be used to modify other datatype's memory, so an int8 pointer needs to be marked as `restrict` in order for the compiler to be confident enough to auto-vectorize. We were doing that previously, but only by making a new local variable. For some reason, GCC will ignore the `restrict` …
=> EC/CPU: Fix int8 auto-vectorization with gcc 4.8.2

src/ucc/api/ucc.h
Backport of https://github.com/openucx/ucc/pull/920
=> API: remove duplicate get_version_string V1.3.x

src/core/ucc_context.c
Don't print warning when some TL team were not destroyed before context destroy
Not a critical issue for UCC to continue working
=> CORE: decrease log level for cts is still in use

src/components/tl/ucp/alltoallv/alltoallv_hybrid.c, src/components/tl/ucp/bcast/bcast_dbt.c, src/components/tl/ucp/reduce/reduce_dbt.c, src/components/tl/ucp/reduce_scatter/reduce_scatter_ring.c, src/components/tl/ucp/reduce_scatterv/reduce_scatterv_ring.c, src/components/tl/ucp/tl_ucp_coll.c, src/components/tl/ucp/tl_ucp_sendrecv.h
task->tagged.send.completed and task->tagged.recv.completed can be incremented concurrently from the ucp callback and task progress. 
Fixes internal bug 3793477
=> TL/UCP: fix completed counter race

src/utils/arch/aarch64/cpu.h
Fixes memory barrier in TL SHM. 
dmb guarantees only ordering, with dsb we correctly wait for store to finish before signaling
=> UTIL: fix memory barrier for aarch64

src/components/topo/ucc_topo.c
Fixes memory leak when all NUMAs sbgps are requested.
=> TOPO: fix all numas sbgp cleanup

src/coll_patterns/recursive_knomial.h, src/components/ec/cpu/ec_cpu.c, src/components/tl/ucp/tl_ucp_team.c
Use min raidx=3 for ppn1 teams. Such radix improves performance providing more network parallelism.
```
1                       5.97              3.14              8.17        1000
2                       5.89              3.13              8.05        1000
4                       5.93              3.26              8.07        1000
8                       5.88              3.18              8.00        1000
16                      5.89              3.19              7.97        1000
32                      6.00              3.30              8.09        1000
64                      6.62              3.83              8.76        1000
128                     6.67              3.69              8.84        1000
256                     6.34              3.88              8.28        1000 …
```
=> TL/UCP: select bigger knomial radix for ppn1

tools/perf/ucc_pt_benchmark.cc, tools/perf/ucc_pt_config.cc, tools/perf/ucc_pt_config.h
Adding option to control ucc perftest multiplication factor size for msg size ranges
Adding option to use "report BW" mode by putting -f 1
=> TOOLS: Add perftest msg size multiplication factor flag

config/m4/ucx.m4, src/components/tl/ucp/Makefile.am, src/components/tl/ucp/allreduce/allreduce.c, src/components/tl/ucp/allreduce/allreduce.h, src/components/tl/ucp/allreduce/allreduce_sliding_window.c, src/components/tl/ucp/allreduce/allreduce_sliding_window.h, src/components/tl/ucp/allreduce/allreduce_sliding_window_setup.c, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_coll.c, src/components/tl/ucp/tl_ucp_coll.h, test/gtest/Makefile.am, test/gtest/coll/test_allreduce.cc, test/gtest/coll/test_allreduce_sliding_window.cc, test/gtest/coll/test_allreduce_sliding_window.h
This PR (1 out of 2 PRs) defines the structs and function stubs for sliding window allreduce. It also adds a gtest for the algorithm. The next PR will have the function implementations.
@janjust @manjugv @samnordmann @Sergei-Lebedev
=> Sliding Window Allreduce Stubs

src/components/tl/ucp/tl_ucp_context.c
Don't call ucp_config_release twice in case of error
Fixes internal bug https://redmine.mellanox.com/issues/3837556
=> TL/UCP: fix error flow for ucp_worker

src/components/ec/cuda/ec_cuda_resources.c, src/components/ec/ucc_ec.c, src/components/mc/cuda/mc_cuda_resources.c, src/components/mc/ucc_mc.c
During EC CUDA resource cleanup original CUDA context can be already destroyed. In such case calls to cudaStreamDestroy, cudaEventDestroy etc. might result in segfault. This PR adds check that CUDA context is valid before doing cleanup.
=> EC/CUDA: check ctx valid before resource cleanup

src/components/tl/mlx5/tl_mlx5_team.c
Fix the error handling to avoid segfault when tl/mlx5/a2a team creation fails
=> TL/MLX5: fix team init error handling flow

src/components/tl/mlx5/mcast/tl_mlx5_mcast.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c, src/components/tl/mlx5/tl_mlx5.h, src/components/tl/mlx5/tl_mlx5_context.c, src/components/tl/mlx5/tl_mlx5_team.c
TL/MLX5: fix warning and var names
checking if the mcast ctx is created, then we attempt to create the mcast team to avoid warning + some of the variable names got enhanced
=> TL/MLX5: fix warning and var names

.ci/scripts/build_ucc.sh, .ci/scripts/run_tests_ucc_mpi.sh, src/components/tl/mlx5/alltoall/alltoall.c, src/components/tl/mlx5/tl_mlx5_team.c
=> TL/MLX5: ci

test/gtest/common/main.cc
set cuda device in gtest to create cuda context 
fixes 
```
mc_cuda.c:369  UCC  ERROR cuCtxGetId(cu_ctx, &cu_ctx_id)() failed: 201(invalid device context)
```
=> TEST: set cuda device in gtest

test/gtest/tl/mlx5/test_tl_mlx5_wqe.cc, test/gtest/tl/mlx5/test_tl_mlx5_wqe.h
Skip the tl/mlx5's gtest when dm allocation fails to avoid segfault
=> TEST: fix mlx5 device memory allocation test

src/ucc/api/ucc.h
Fix typo in thread mode description
thanks to @hoopoepg for finding
=> DOCS: fix thread mode description

src/components/tl/nccl/tl_nccl_coll.c
Disable active set bcast in TL NCCL when lazy communicator init is used
With lazy init we cannot create communicator on first collective since not all ranks participate in init
=> TL/NCCL: disable active set colls for lazyinit

src/components/tl/mlx5/tl_mlx5_context.c, src/components/tl/ucp/bcast/bcast_dbt.c, src/components/tl/ucp/bcast/bcast_knomial.c, src/components/tl/ucp/tl_ucp_coll.h, src/core/ucc_coll.c, src/utils/ucc_coll_utils.h, test/gtest/active_set/test_active_set.cc
Active set is a sort of lightweight subcommunicator for TL/UCP and TL/NCCL. It was originally used as a hack that enables point to point communication. This PR:
- Removes the restriction that the active set comm size is 2
- Fixes a bug that the user tag was not being properly read
- Adds support for active set double binary tree broadcast in TL/UCP
- Updates the active set gtest to more thoroughly test all of the above
=> TL/UCP: Add support for active_set broadcast with knomial and dbt for size greater than 2

src/coll_patterns/sra_knomial.h, src/components/tl/ucp/allgather/allgather.c, src/components/tl/ucp/reduce_scatter/reduce_scatter.c, src/components/tl/ucp/reduce_scatter/reduce_scatter.h, src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c, src/components/tl/ucp/tl_ucp_coll.c, src/components/tl/ucp/tl_ucp_coll.h, test/gtest/coll/test_reduce_scatter.cc
Add reduce scatter knomial algorithm in TL/UCP
Performance:
8 nodes 64 ppn
msgsize: | knomia us. | ring us.
-- | -- | --
4 | 29.45 | 271.84
8 | 43.29 | 792.63
16 | 53.09 | 950.44
32 | 60.85 | 763.14
64 | 123.39 | 883.84
128 | 531.5 | 974.35
256 | 1026.58 | 1075.77
512 | 1028.21 | 1042.87
1024 | 1942.62 | 1331.72
2048 | 2149.71 | 1287.28
4096 | 4126.88 | 2087.69
8192 | 8338.22 | 3880.91
8 nodes 1 ppn
msgsize: | knomial us.| ring us.
-- | -- | --
4 | 5.47 | 11.59
8 | 5.56 | 14.15
16 | 4.69 | 13.96
32 | 4.83 | 13.92
64 | 5.34 | 14.36
128 | 5.52 | 15.37
256 | 6.16 | 15.88
512 | 7.43 | 19.06
1024 | 8.14 | 19.8
2048 | 9.48 | 21.71
4096 | 11.8 | 25.79
8192 | 18.59 | 30.37
16384 | 26.32 | 38.85
32768 | 47.18 | 58.44
65536 | 79.68 | 109.75
131072 | 130.79 | 171.54
=> TL/UCP: add reduce scatter knomial

src/ucc/api/ucc.h
Fixes a typo that make some (but not all) hints misspell optimize. 
Our OpenMPI code maintainer requested this fixup.
n/a
=> CORE: Fix/match spelling of collective hints

src/components/tl/sharp/tl_sharp.c, src/components/tl/sharp/tl_sharp_context.c, src/components/tl/sharp/tl_sharp_lib.c
Try use ICC internal OOB if available. 
Interl OOB is optimal while external OOB BCAST is implemented using allgather which is not optimal.
=> TL/SHARP: Use internal OOB if available.

config/m4/rocm.m4, configure.ac, cuda_lt.sh, src/components/ec/rocm/kernel/Makefile.am
Added ability to specify ROCM architecture on configure with --with-rocm-arch
options are:
`all` which does the same behavior as before,
`all-arch-no-native` does all default rocm architectures with the exception of native (to be used if no rocm enabled gpus exist in the system)
`--offload-arch=gfx###` for specifying a specific architecture
This allows specifying a specific architecture. It will fix the https://github.com/openucx/ucc/issues/969 issue
=> BUILD: add support for specific gpu ach with ROCM

src/components/tl/mlx5/Makefile.am, src/components/tl/mlx5/mcast/p2p/ucc_tl_mlx5_mcast_p2p.c, src/components/tl/mlx5/mcast/p2p/ucc_tl_mlx5_mcast_p2p.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_context.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_one_sided_reliability.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_one_sided_reliability.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_service_coll.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_service_coll.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c
TL/MLX5: one-sided mcast reliability init that will be used for mcast-based allgather
=> TL/MLX5: one-sided mcast reliability init

src/components/tl/sharp/tl_sharp_context.c
Don't create sharp ctx if world size is less than 2
fixes
```
==== backtrace (tid:   1051) ====
0 0x0000000000042520 __sigaction()  ???:0
1 0x0000000000025562 ucc_sbgp_create()  /build-result/src/hpcx-v2.19-gcc-mlnx_ofed-redhat7-cuda12-x86_64/ucc-0b4a0780918900fa497b1e6a65485247fecec4a2/src/components/topo/ucc_sbgp.c:599
2 0x0000000000024c95 ucc_topo_get_sbgp()  /build-result/src/hpcx-v2.19-gcc-mlnx_ofed-redhat7-cuda12-x86_64/ucc-0b4a0780918900fa497b1e6a65485247fecec4a2/src/components/topo/ucc_topo.c:224
3 0x0000000000004ce2 ucc_tl_sharp_context_init()  /build-result/src/hpcx-v2.19-gcc-mlnx_ofed-redhat7-cuda12-x86_64/ucc-0b4a0780918900fa497b1e6a65485247fecec4a2/src/components/tl/sharp/tl_sharp_context.c:294
4 0x0000000000005158 ucc_tl_sharp_context_create_epilog()  …
```
=> TL/SHARP: check comm size in sharp ctx create

src/utils/ucc_parser.c
Check for auto pipeline params by comparing fields of pipeline params struct
memset doesn't work due to possible uninitialized paddings between structure fields
=> UTIL: fix pipeline params check for auto

src/components/cl/hier/cl_hier.h
Adding reduce to list of supported colls in CL HIER.
UCC_COLL_TYPE_REDUCE was missing. CL HIER never selects 2step reduce algorithm.
=> CL/HIER: add reduce to supported colls

src/components/tl/mlx5/tl_mlx5_team.c, src/utils/ucc_rcache.h
Related bug: https://redmine.mellanox.com/issues/3706049
Set rcache alignment back from `ucc_get_page_size()` to `UCS_PGT_ADDR_ALIGN`
Re-activate tl/mlx5 alltoall
This bug reproduces only when using ucx anterior to https://github.com/openucx/ucx/commit/85d2d9d0f, which introduced dynamic rcache alignment. 
https://github.com/openucx/ucc/pull/877 (specifically https://github.com/openucx/ucc/commit/b13b87d0a32a326bf60a322525979e5e12533807) sets the alignment to `ucc_get_page_size()` whereas it was `UCS_PGT_ADDR_ALIGN` before.
Setting the alignment back to `UCS_PGT_ADDR_ALIGN` solves the bug.
The reason is yet to be found out.
Below is a comparison of the performances with tl/ucp and hcoll
``` 
TL/UCP:
$ mpirun \
--mca coll_ucc_cts alltoall \
--mca coll_ucc_enable 1 \
--mca coll_hcoll_enable …
```
=> TL/MLX5: Fix segmentation fault in a2a mpi test

config/m4/ucx.m4, src/components/tl/mlx5/mcast/tl_mlx5_mcast_rcache.c, src/components/tl/mlx5/tl_mlx5_rcache.c, src/components/tl/sharp/tl_sharp_context.c, src/utils/ucc_rcache.h
Need to provide merge callback to rcache ops due to interface change in https://github.com/openucx/ucx/pull/9859
Fixes Internal issue [3884209](https://redmine.mellanox.com/issues/4039176)
=> UTIL: fix rcache merge cb

tools/perf/ucc_pt_config.cc
The parameter was implemented by https://github.com/openucx/ucc/pull/949 but not exposed
=> TOOLS: expose -f param 

src/components/mc/ucc_mc.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_coll.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_coll.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_progress.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c, src/components/tl/mlx5/tl_mlx5.c, src/components/tl/mlx5/tl_mlx5_coll.c
TL/MLX5: add device mem mcast bcast
=> TL/MLX5: add device mem mcast bcast

src/components/tl/ucp/tl_ucp_coll.h, src/utils/ucc_compiler_def.h
Add special field to algorithms union in tl ucp task. 
Plugin data field might be used by tl ucp plugins to store algorithm specific data inside tl ucp task
=> TL/UCP: add task plugin data

src/schedule/ucc_schedule.c
This PR initializes the scratch buffer to NULL in `ucc_coll_task_init`. The value not being NULL was causing the asymmetric memory copy-out to run for triggered tasks, making the DLRM jenkins test fail.
=> CORE: Fix asym mem for triggered tasks

.github/workflows/docs.yaml
Fixes docs build actions.
upload actions v2 is deprecated, https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
=> CI: fix docs gh actions

src/components/base/ucc_base_iface.h, src/components/cl/basic/cl_basic_context.c, src/components/cl/basic/cl_basic_lib.c, src/components/cl/doca_urom/cl_doca_urom_context.c, src/components/cl/hier/cl_hier_context.c, src/components/tl/cuda/tl_cuda_context.c, src/components/tl/mlx5/tl_mlx5_context.c, src/components/tl/nccl/tl_nccl_context.c, src/components/tl/rccl/tl_rccl_context.c, src/components/tl/self/tl_self_context.c, src/components/tl/sharp/tl_sharp_context.c, src/components/tl/ucp/tl_ucp_context.c
From the UCC Backlog:
```
Check all TLs and CLs lib and context attributes
Attribute query function should follow this scheme:
if attr.mask is not zero check each attributed defined in mask
Set attribute according to Tl/CL capabilities
Set attr.flags always
This logic is generally broker in UCC, for example
ucc_tl_self_get_context_attr(const ucc_base_context_t *context, /* NOLINT */
ucc_base_ctx_attr_t      *attr)
{
return UCC_OK;
}
attr.topo_required is not set (returns something random)
attr.global_work_buffer_size is not set
etc.
```
This PR updates UCC so that all context attribute queries read the mask for each field and then write a value, usually 0. Some of these were missing.
The backlog task mentions updating lib attributes as well, but it seems to me that both CL and TL lib …
=> Update context attribute query

src/components/topo/ucc_sbgp.c
On the lego-grace system, I found that no socket leader groups are created. This is making it so the tuning perfkey being picked up in TL_SHM is wrong. I traced the issue back to the line I'm updating in this PR.
What's happening is that on this system there is no installation of libnuma.so. This is causing every topo's `topo->numa_bound` to be equal to 0. In the macro that I updated, it will check to see if the group type is SOCKET, and if it's not it will use the value of `topo->numa_bound` to determine boundedness. Since numa_bound is zero, socket leader subgroup creation is skipped in `ucc_sbgp_create` in the switch `case UCC_SBGP_SOCKET_LEADERS:`.
After the update in this PR to use `topo->sock_bound` in the case that the group type is `UCC_SBGP_SOCKET_LEADERS`, the socket leader …
=> TOPO: Fix socket leader sbgp creation if libnuma.so is not installed

src/coll_patterns/recursive_knomial.h, src/coll_patterns/sra_knomial.h, src/components/tl/ucp/Makefile.am, src/components/tl/ucp/allgather/allgather_knomial.c, src/components/tl/ucp/allgatherv/allgatherv.c, src/components/tl/ucp/allgatherv/allgatherv.h, src/components/tl/ucp/allgatherv/allgatherv_knomial.c, src/components/tl/ucp/allgatherv/allgatherv_ring.c, src/components/tl/ucp/tl_ucp_coll.c, src/components/tl/ucp/tl_ucp_coll.h, src/utils/ucc_coll_utils.h, test/gtest/coll/test_allgatherv.cc, test/mpi/test_allgatherv.cc, tools/perf/ucc_pt_coll_allgatherv.cc
Adding knomial allgatherv algorithm in TL/UCP. The algorithm requires contig dst buffer and based on knomial allgather implementation where count and offset computed based on user provided args.
Improves small msg allgatherv performance.
=> TL/UCP: add knomial allgatherv

contrib/ucc.conf, src/utils/ini.h, src/utils/ucc_parser.c, src/utils/ucc_parser.h
This PR updates UCC to allow a socket range in ucc.conf in addition to vendor/arch/nodes/ppn and uses it to tune TL/UCP for Grace systems.
=> TL/UCP: Grace tuning

src/components/mc/cuda/mc_cuda.c
Don't print error if cuCtx doesn't exist
UCC can continue and fallback to default ctx
=> MC/CUDA: reduce verbosity for cu ctx doesn't exist

.ci/job_matrix.yaml, .ci/scripts/run_docker.sh
Solving collision issue with a place of docker id file and issue with running sshd
CI fail
=> CI: FiX for CI, issue with docker id collision

Makefile.am, configure.ac, ucc.pc.in
Add a ucc pkg-config file
DOCA requires it to build UROM_UCC. Plus, UCX has it since it's pretty standard. It would be good for UCC to have it too.
`ucc.pc` is automatically generated from ucc.pc.in via `AC_CONFIG` macro. The changes to the Makefile make it so `ucc.pc` is installed with `make install` into the prefix.
=> BUILD: Add ucc pkg-config

src/components/tl/mlx5/mcast/p2p/ucc_tl_mlx5_mcast_p2p.c, src/components/tl/mlx5/mcast/p2p/ucc_tl_mlx5_mcast_p2p.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_coll.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_coll.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_progress.c, src/components/tl/mlx5/tl_mlx5_coll.c
TL/MLX5: fix memtype in bcast reliability
=> TL/MLX5: fix memtype in bcast reliability

contrib/doca_urom_ucc_plugin/dpu/worker_ucc.c
Disabling core pinning in the DOCA UROM worker unless worker sharing can be used.
When using more than 1 PPN, CL DOCA UROM will create multiple DOCA UROM workers that do not have knowledge of each other. Each worker will pin to the first core resulting in poor performance reduction. Disabling core pinning allows the Linux scheduler to assign a core and results in performance similar to the 1 PPN case.
=> CL/DOCA_UROM: disable core pinning in doca worker

src/components/tl/mlx5/Makefile.am, src/components/tl/mlx5/alltoall/alltoall.c, src/components/tl/mlx5/alltoall/alltoall.h, src/components/tl/mlx5/alltoall/alltoall_mkeys.c, src/components/tl/mlx5/alltoall/alltoall_mkeys.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_allgather.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_allgather.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_coll.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_context.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_one_sided_progress.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_one_sided_progress.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_one_sided_reliability.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_progress.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c, src/components/tl/mlx5/tl_mlx5.c, src/components/tl/mlx5/tl_mlx5_coll.c, src/components/tl/mlx5/tl_mlx5_coll.h, src/components/tl/mlx5/tl_mlx5_context.c, src/components/tl/mlx5/tl_mlx5_dm.c, src/components/tl/mlx5/tl_mlx5_dm.h, src/components/tl/mlx5/tl_mlx5_lib.c, src/components/tl/mlx5/tl_mlx5_pd.c, src/components/tl/mlx5/tl_mlx5_pd.h, src/components/tl/mlx5/tl_mlx5_team.c, src/components/tl/mlx5/tl_mlx5_wqe.c, src/components/tl/mlx5/tl_mlx5_wqe.h
add the algorithm for mcast-based allgather
scalability and performance improvement over sw based allgather
Realizing the Allgather operations as N (team-size) concurrent Bcast operations (every process becomes the root). We use the one-sided design that was merged before for its reliability.
=> TL/MLX5: adding mcast allgather staging based algo

src/components/tl/mlx5/tl_mlx5.h, src/components/tl/mlx5/tl_mlx5_context.c, src/components/tl/sharp/tl_sharp_context.c, src/components/tl/ucc_tl.h, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_ep.c, src/components/tl/ucp/tl_ucp_ep.h, src/components/tl/ucp/tl_ucp_team.c, src/core/ucc_service_coll.c, src/core/ucc_service_coll.h
Fixes segfault when service team finalizes collective and UCC_COLL_TRACE=debug is set
TL SHARP and TL MLX5 bypass service_coll interface and use function pointers directly, in this case some fields in request object are not valid and coll trace doesn't work. In this patch appropriate finalize function is used instead
=> CORE: fix coll trace for service team

src/schedule/ucc_schedule.h, src/schedule/ucc_schedule_pipelined.c
Fixes overflow which happens if number of restarts in pipelined schedule is bigger than 256
=> CORE: fix n deps overflow in pipelined schedule

src/coll_patterns/recursive_knomial.h, src/coll_patterns/sra_knomial.h, src/components/tl/ucp/gather/gather.c, src/components/tl/ucp/gather/gather.h, src/components/tl/ucp/gather/gather_knomial.c, src/components/tl/ucp/tl_ucp_coll.h
Use knomial pattern data structure in gather knomial algorithm in TL UCP
part of https://github.com/openucx/ucc/pull/1035
_
=> TL/UCP: use knomial pattern in gather

src/core/ucc_global_opts.h
Make the bitmap-type config `profile_mode` uint64_t to align with recent UCX(S) changes.
UCX(S) now uses uint64_t for bitmap-type (declared via UCS_CONFIG_TYPE_BITMAP) configurations (see https://github.com/openucx/ucx/commit/8a84af89e87b57e72a2e9f6a8945e5ff5ab24295). UCC should align with this change, otherwise setting bitmap-type config may overwrite the next 4-byte memory during config parsing (see https://github.com/openucx/ucx/commit/8a84af89e87b57e72a2e9f6a8945e5ff5ab24295#diff-8dd28fc04f39623f32e719552443482db8a07986754b3ba0ba48387db94d8bbdL446). In the case of UCC, the `profile_file` option of `ucc_global_opts` will be overwritten when `profile_mode` is set.
=> CORE: Use uint64_t for bitmap configs

src/components/tl/mlx5/mcast/tl_mlx5_mcast.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_coll.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_coll.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_progress.c, src/components/tl/mlx5/tl_mlx5_coll.c
adding support for nonblocking cuda memcpy in mcast
=> TL/MLX5: add nonblocking cudaMemcpy support

src/components/tl/mlx5/mcast/tl_mlx5_mcast.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_one_sided_reliability.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c, src/components/tl/mlx5/tl_mlx5_team.c
This patch adds support for multiple multicast groups in UCC. Since each group needs its own QP (and AH, address, etc.), it changes the code to use arrays instead of single variables (for example, ```comm->mcast.qp_list[]``` instead of ```comm->mcast.qp```). This is the first step in a bigger set of changes that will fully support multiple MCAST groups. In this patch, some references are still hardcoded to ```qp_list[0]```, but these will be replaced in Part 2 so that every group can use its own QP.
=> TL/MLX5: mcast multi-group support part 1

src/components/tl/mlx5/alltoall/alltoall_inline.h, src/components/tl/mlx5/tl_mlx5_wqe.c
[Edited]
Fix fences in WQEs.
**QPs used by each node leader:**
- a QP with loop-back connection, which we call "UMR QP"
- one QP per remote peer (+1 with loop-back connection), which we call "RDMA QP"
**Here the different WQEs in the algorithm:**
1. UMR WQE posted to "UMR QP". CPU then blocks until completion of this WQE.
2. Transpose WQE+ RDMA write WQE + atomic fetch_and_add WQE, all posted to "RDMA QP"
3. wait-on-data posted to "UMR QP"
**Conclusion regarding flags:**
- UMR WQE doesn't need any fence since it is the first WQE posted.
- The transpose WQE, ~~which consumes UMR, needs a **small** fence.~~ doesn't need any fence.
- RDMA write, which consumes transpose, needs a **small** fence because it only uses local data
- atomic fetch_and_add WQE ~~needs a **strong fence** because it …
=> TL/MLX5: fix fences in a2a's WQEs

src/components/tl/cuda/Makefile.am, src/components/tl/cuda/allgather/allgather.c, src/components/tl/cuda/allgather/allgather_linear.c, src/components/tl/cuda/allgatherv/allgatherv.c, src/components/tl/cuda/allgatherv/allgatherv_linear.c, src/components/tl/cuda/bcast/bcast.c, src/components/tl/cuda/bcast/bcast.h, src/components/tl/cuda/bcast/bcast_linear.c, src/components/tl/cuda/reduce_scatter/reduce_scatter.c, src/components/tl/cuda/reduce_scatter/reduce_scatter_linear.c, src/components/tl/cuda/reduce_scatterv/reduce_scatterv.c, src/components/tl/cuda/reduce_scatterv/reduce_scatterv_linear.c, src/components/tl/cuda/tl_cuda.c, src/components/tl/cuda/tl_cuda.h, src/components/tl/cuda/tl_cuda_coll.c, src/components/tl/cuda/tl_cuda_coll.h, src/components/tl/cuda/tl_cuda_context.c, src/components/tl/cuda/tl_cuda_ring.h, src/components/tl/cuda/tl_cuda_team.c, src/components/tl/cuda/tl_cuda_team_topo.h, src/components/tl/ucp/bcast/bcast_knomial.c, src/utils/ucc_atomic.h, test/gtest/coll/test_bcast.cc
Linear CUDA Broadcast implementation with Active set feature support.
- Functional improvement, parity with others communication libraries.
- Ability to place many ranks on single GPU
- No GPU blocking, communication initiated from host
- Active set might be used to emulate P2P send/receive on top of broadcast collective
Naive approach where root rank writes data to own shared buffer and others ranks read from it through NVLink (bi-copy).
The algorithm enables the initiation of multiple simultaneous peer-to-peer (P2P) communications, constrained only by user-defined tags. During its execution, the algorithm identifies the first available free barrier and acquires it. This barrier, along with associated resources, is then utilized as a scratch buffer to facilitate efficient operations.
=> TL/CUDA: Linear Broadcast for GPU

.github/workflows/clang-tidy.yaml
This PR enhances memory leak detection during testing by configuring AddressSanitizer (ASan) and LeakSanitizer (LSan) with more robust options.  Specifically, it disables fast unwinding on malloc (fast_unwind_on_malloc=0) for more reliable leak detection, enables leak detection (detect_leaks=1), and disables printing of suppressions (print_suppressions=0) in ASan.  For LSan, it enables reporting of leaked objects (report_objects=1) to provide more detailed information about memory leaks. 
These changes will provide more comprehensive memory leak reports, helping to identify and fix potential memory issues.  
An example of such a feature is the below CI output (taken from https://github.com/openucx/ucc/pull/1023 after applying this new changes) that detects where the memory is leaking and …
=> CI: enhance ASAN/LSAN memory leak detection

src/components/tl/mlx5/mcast/tl_mlx5_mcast.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_allgather.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c, src/components/tl/mlx5/tl_mlx5.c
The PR focuses on optimizing allgather communication by leveraging a pipelined multicast mechanism with configurable concurrency and prepost bucket sizes for recv buffers. It implements a new function, ````ucc_tl_mlx5_mcast_prepare_zero_copy_allgather````, which calculates and sets up a pipelined schedule for the zero-copy allgather. The function validates parameters, allocates schedules, and registers the receive buffers as well.
=> TL/MLX5: generate schedule for zcopy allgather

src/components/tl/mlx5/tl_mlx5_ib.c, src/core/ucc_global_opts.h, test/gtest/common/gtest-all.cc, test/gtest/tl/mlx5/test_tl_mlx5.cc, test/gtest/tl/mlx5/test_tl_mlx5.h, test/gtest/tl/mlx5/test_tl_mlx5_qps.cc, test/gtest/tl/mlx5/test_tl_mlx5_qps.h, test/gtest/tl/mlx5/test_tl_mlx5_wqe.cc, test/gtest/tl/mlx5/test_tl_mlx5_wqe.h
When a gtest unit is skipped or failed, using gtest macros like `GTEST_ASSERT_EQ`, or `GTEST_SKIP`, the program only exits the current function, but not the whole test. Therefore, the error/skip must be propagated through all frames of the unit test. Bottom line, each time we call a function that is susceptible to call one of this macro, we need to check on return the test status and return if relevant.
Related issue:
- [CI failure](https://nbuprod.blsm.nvidia.com/hpcx-01/job/UCC/job/ucc/232/console) in https://github.com/openucx/ucc/pull/1077
- https://redmine.mellanox.com/issues/4148913
- (maybe) https://redmine.mellanox.com/issues/4280707
=> TEST: add error checking and exit in gtest

src/components/tl/ucp/allgather/allgather_knomial.c, src/components/tl/ucp/allreduce/allreduce_sra_knomial.c, src/components/tl/ucp/bcast/bcast_sag_knomial.c, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_coll.h, src/components/tl/ucp/tl_ucp_lib.c, src/components/tl/ucp/tl_ucp_team.c
Select optimal knomial radix for non host memory
=> TL/UCP: add radix selection to kn radix

src/components/tl/ucp/Makefile.am, src/components/tl/ucp/allgather/allgather_knomial.c, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_coll.h, src/components/tl/ucp/tl_ucp_context.c, src/components/tl/ucp/tl_ucp_copy.c, src/components/tl/ucp/tl_ucp_copy.h
Add option to use ec copy, mc copy or ucp copy for local copy in TL UCP 
See PR https://github.com/openucx/ucc/pull/1021 for more details
=> TL/UCP: add local copy option

config/m4/sharp.m4, src/components/tl/sharp/tl_sharp.h, src/components/tl/sharp/tl_sharp_coll.c, src/components/tl/sharp/tl_sharp_coll.h, src/components/tl/sharp/tl_sharp_team.c
Add support SHARP allgather. Fix regsitration in reduce scatter
=> TL/SHARP: add support for allgather

src/components/tl/sharp/tl_sharp.c, src/components/tl/sharp/tl_sharp.h, src/components/tl/sharp/tl_sharp_coll.c, src/components/tl/sharp/tl_sharp_context.c, src/components/tl/sharp/tl_sharp_team.c
Enable SHARP reduce-scatter only when SAT is enabled
=> TL/SHARP: enable reduce-scatter only when SAT is enabled.

config/m4/ucx.m4, src/utils/ucc_parser.c, src/utils/ucc_parser.h
This commit adds compatibility for a newer version of UCX's config parser print function by conditionally adding an optional NULL filter argument. The changes include:
- Modifying config/m4/ucx.m4 to check for the new function signature
- Updating src/utils/ucc_parser.c and src/utils/ucc_parser.h to conditionally call the function with an additional NULL argument
- Using preprocessor macros to maintain backward compatibility
=> BUILD: Add support for optional filter argument in config parser print function

test/gtest/tl/mlx5/test_tl_mlx5_qps.h
This should fix the recent CI failures (shown below) on multiple PRs  when CI gtest is running under torch_ucc containers. This error was only reproducible when it was running under that container environment. 
```qp_conf``` had uninitialized values that were set to junk values, leading to incorrect configuration and failures when creating the UMR QP.
On bare metal, uninitialized ```qp_conf``` was probably zeroed out and it did not have random garbage values, so the issue didn’t appear. This PR makes sure that the configuration is set properly. 
```
15:28:27  /opt/nvidia/src/ucc/test/gtest/tl/mlx5/test_tl_mlx5_qps.h:90: Failure
15:28:27  Expected equality of these values:
15:28:27    create_rc_umr_qp(ctx, pd, cq, port, &umr_qp.qp, &umr_qp_conf, &lib)
15:28:27      Which is: -6
15:28:27 …
```
=> GTEST: fix UMR QP create config set

src/components/cl/hier/Makefile.am, src/components/cl/hier/allgatherv/allgatherv.c, src/components/cl/hier/allgatherv/allgatherv.h, src/components/cl/hier/allgatherv/unpack.c, src/components/cl/hier/allgatherv/unpack.h, src/components/cl/hier/cl_hier.c, src/components/cl/hier/cl_hier.h, src/components/cl/hier/cl_hier_coll.c, src/components/cl/hier/cl_hier_coll.h, src/components/cl/hier/cl_hier_team.c, src/components/topo/ucc_sbgp.c, src/components/topo/ucc_sbgp.h, src/utils/ucc_coll_utils.h, test/gtest/coll/test_allgatherv.cc, test/gtest/common/test_ucc.cc, test/gtest/common/test_ucc.h
This PR adds CL/HIER allgatherv and updates the allgatherv gtest to test non-contiguous dst buffers. It is meant to be used in conjunction with my TL/SHM gatherv implementation.
The algorithm is:
- Node-level gatherv, all sendbufs on the node are put into a scratch buffer
- Leader-level allgatherv on the scratch buffer, the result is put into the dst buffer
- Node-level in-place bcast on the dst buffer
- If the buffer is non-contig, unpack by memcpying the packed buffer into the right displacements
2 nodes, 32 PPN on lego-grace cg (1 socket, 72 cores/socket)
Size | UCC after PR (cl_hier + tl_shm + tl_ucp) | UCC before PR (cl_basic + tl_ucp) | HCOLL | %-Gain, After vs. HCOLL | %-Gain, Old vs. HCOLL | %-Gain, Before vs. After
-- | -- | -- | -- | -- | -- | --
1 | 7.37 | 19.88 | 7.41 | 0.54% …
=> CL/HIER: Add allgatherv

src/utils/ucc_parser.c
we see memory leaks from CI tests in https://github.com/openucx/ucc/pull/1023
This PR fixes these memory leaks. One instance of leaks can happen when a function such ```ucc_cl_basic_get_lib_attr()``` gets called multiple times, which can potentially lead to calling ```ucc_config_names_array_dup``` on the same cl_lib object. Each time this ```duplicate``` function is called, we were allocating new memory for names array, without making sure that that array has already been allocated or not.
=> UTIL: fix names array memory leak

test/gtest/coll/test_bcast.cc
=> TL/MLX5: add gtest for mcast

src/components/topo/ucc_sbgp.c, src/components/topo/ucc_sbgp.h, src/components/topo/ucc_topo.c, src/components/topo/ucc_topo.h, test/gtest/core/test_topo.cc
This is a followup PR to https://github.com/openucx/ucc/pull/1050.
It adds two fields to `ucc_topo_t`, `node_leaders` and `all_nodes` and corresponding functions to calculate them on demand. `all_nodes` is the node-sbgp equivalent of `all_sockets`, i.e. it's an array of every node subgroup in the comm.
Knowing the node subgroup mapping on other nodes than the one I'm on is useful in the allgatherv unpack stage from my PR. For example, say you ran with `mpirun --map-by node ...`. Then the node/rank mapping might look like:
```
node0: {rank0, rank2}
node1: {rank1, rank3}
```
Then the destination buffer after the allgatherv is done on each node will look like `{0,2,1,3}`, when it really should be in order of the ranks in the team, like `{0,1,2,3}`. To fix this, I will unpack the elements …
=> CORE: Get node sbgps and leaders

src/components/tl/ucp/tl_ucp_service_coll.c
Fix checking if allgather should use the in-place version or not, by checking the **logical ranks** of the team. (No need to remap to physical ranks.)
In situations involving team odd-even, this results in a problem where, for instance, the tl/cuda cannot communicate.
This issue starts to become visible after fixing another issue in #1089.
=> TL/UCP: fix inplace checking in service allgather

src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c, src/components/tl/mlx5/tl_mlx5.h, src/components/tl/mlx5/tl_mlx5_context.c, src/components/tl/mlx5/tl_mlx5_team.c
- Introduced functions to check for GPU Direct driver availability.
- Enhanced context initialization to support CUDA memory types if the GPU Direct driver is present.
- Adjusted memory type handling in team score retrieval and multicast team initialization to reflect CUDA support.
Fixes following CI issue in MLX5 Alltoall
```
tl_mlx5_rcache.c:28   TL_MLX5 ERROR failed to register memory
alltoall_coll.c:150  TL_MLX5 ERROR Failed to register send_bf memory (errno=14)
ucc_coll.c:301  UCC_COLL INFO  coll_init: Alltoall: src={0x7f2325a00000, 8, uint8, Cuda}, dst={0x7f2325b00000, 8, uint8, Cuda}; CL_BASIC {TL_MLX5}, team_id 1
tl_mlx5_rcache.c:28   TL_MLX5 ERROR failed to register memory
alltoall_coll.c:150  TL_MLX5 ERROR Failed to register send_bf memory (errno=14)
```
=> TL/MLX5: gdr checks and support for CUDA mt

src/components/ec/cuda/ec_cuda_executor_persistent_wait.c
Batch cuda stream memory operations to single call to reduce cpu and gpu execution overhead.
Experiments with profiling shows noticable holes in gpu stream activity related to stream mem ops.
`mpirun --mca coll ^hcoll --mca coll_ucc_enable 0 -x LD_LIBRARY_PATH=<user>/ucc/install/lib:$LD_LIBRARY_PATH -x UCC_CLS=basic -x UCC_TLS=ucp -x UCX_TLS=rc,cuda -x UCX_RNDV_THRESH=0 -x UCC_LOG_LEVEL=info -x UCC_CONFIG_FILE= -np 2 ./install/bin/ucc_perftest -m cuda -c bcast -F -d uint8 -b 1 -e 8k -T`
```
Master:
Collective:             Bcast
Memory type:            cuda
Datatype:               uint8
Reduction:              N/A
Inplace:                N/A
Warmup:                 
small                 100
large                 20
Iterations:             
small                 1000
large …
```
=> EC/CUDA: batch memory operations

src/components/tl/mlx5/alltoall/alltoall_coll.c, src/components/tl/mlx5/alltoall/alltoall_mkeys.c, src/components/tl/mlx5/tl_mlx5.c, src/components/tl/mlx5/tl_mlx5.h, src/components/tl/mlx5/tl_mlx5_coll.h, src/components/tl/mlx5/tl_mlx5_dm.c, src/components/tl/mlx5/tl_mlx5_wqe.c, src/utils/ucc_math.h, test/gtest/tl/mlx5/test_tl_mlx5_wqe.cc
This PR contains various optimizations for TL/MLX5/a2a, leading to significant performance gain
this is a critical optimization that brings immediate performance benefits since it gives more flexibility in choosing the block dimension to better saturate the transpose unit. To complete this feature, we expose two (independent) options for determining the block dimensions h and w:
- `ALLTOALL_BLOCK_SHAPE=long`, imposing `h >= w`
- `ALLTOALL_BLOCK_SHAPE=wide`, imposing `h <= w`
- `ALLTOALL_BLOCK_SHAPE=wide`, imposing `h = w`
as long as two blocks need to be sent to the same remote peer, the WQEs dealing with those blocks can 1) be enqueued on the same QPE and 2) use the same device memory chunks. This allows to use one dm chunk to post (and offload to the NIC) the processing of a batch of …
=> TL/MLX5: a2a various optimizations

src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_context.c
Disable protocols in UCX that needs memory type.
Requires https://github.com/openucx/ucx/pull/10490
=> TL/UCP: disable proto that need memory type copy

.ci/scripts/build_ucc.sh, .ci/scripts/coverity.sh
This PR modifies the CI build script to specifically build UCC for NVIDIA Volta (sm70) architecture only, by adding the --with-nvcc-gencode flag to the configure command.
This change is needed to ensure consistent CI builds targeting a specific GPU architecture (Volta/sm70). This helps in reducing build time in CI by compiling for a single architecture
The change is implemented by adding the --with-nvcc-gencode="-gencode=arch=compute_70,code=sm_70" flag to the configure command in .ci/scripts/build_ucc.sh. This flag tells NVCC to generate code specifically for the Volta architecture (compute capability 7.0).
=> TEST: build sm70 only in CI

src/components/tl/mlx5/Makefile.am, src/components/tl/mlx5/mcast/tl_mlx5_mcast.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_allgather.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_helper.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_one_sided_progress.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_one_sided_progress.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_one_sided_reliability.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_one_sided_reliability.h, src/components/tl/mlx5/mcast/tl_mlx5_mcast_service_coll.c, src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c, src/components/tl/mlx5/tl_mlx5.c, src/components/tl/mlx5/tl_mlx5.h, src/components/tl/mlx5/tl_mlx5_coll.c, src/components/tl/mlx5/tl_mlx5_team.c
This PR improves the **staging-based Allgather** and adds a **zero-copy Allgather** to TL/MLX5. The staging approach is now more stable, fixing issues like message truncation, MTU handling, and CQ polling. This PR also enhances **one-sided reliability**, adding RDMA reads to handle dropped or out-of-order packets. Other fixes include preventing hangs by avoiding recursive progress calls, cleaning up reliability resources, and simplifying data structures for better performance and maintainability.
=> TL/MLX5: Stabilize staging-based AG and Add zcopy AG

tools/perf/ucc_perftest.cc
Enhance error handling in the performance test tool by checking the return status of run_bench() and providing more detailed error reporting if the benchmark fails. This ensures better visibility into potential runtime issues during performance testing.
Fixes internal issue 4259479
=> TOOLS: Add error handling for benchmark run

src/components/tl/ucp/Makefile.am, src/components/tl/ucp/gather/gather_knomial.c, src/components/tl/ucp/reduce/reduce.c, src/components/tl/ucp/reduce/reduce.h, src/components/tl/ucp/reduce/reduce_srg_knomial.c, src/components/tl/ucp/reduce_scatter/reduce_scatter_knomial.c, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_coll.c, src/components/tl/ucp/tl_ucp_coll.h, test/gtest/Makefile.am, test/gtest/coll/test_reduce.cc
Add reduce srg knomial algorithm to TL UCP
Improves performance of large msg reduce collective
Implemented as schedule of reduce scatter knomial followed by gather knomial
=> TL/UCP: add reduce srg knomial

src/components/cl/hier/allgatherv/allgatherv.c, src/components/cl/hier/allgatherv/unpack.c
Follow up to https://github.com/openucx/ucc/pull/1103. This PR fixes the case where a node leader is the only rank on the node. In that case, the node subgroup wont exist and he'll have to memcpy the src buf to the scratch buffer.
=> CL/HIER: Allgatherv lone node leader

src/components/tl/sharp/tl_sharp_coll.c, src/components/tl/sharp/tl_sharp_coll.h, src/components/tl/sharp/tl_sharp_team.c
- Added default algorithm selection strings for allgather and reduce_scatter .
- Updated the team score retrieval function to apply these default settings.
SHARP SAT by default is enabled only for msg size > 16k.
=> TL/SHARP: enable AG and RS after 16k

src/coll_patterns/bruck_alltoall.h, src/utils/ucc_compiler_def.h
Introduce `ucc_assume` macro to fix clang tidy warnings
clang tidy reports errors division by zero, compiler unable to ensure that some variables couldn't be 0
=> UTIL: ucc_assume macro

src/components/tl/mlx5/alltoall/alltoall_coll.c, src/utils/ucc_math.h
Optimized version of `ucc_lowest_greater_power2()` using bitwise operations
- constant time
- mul free only bitwise ops
- prevent overflow
References: 
https://stackoverflow.com/questions/364985/algorithm-for-finding-the-smallest-power-of-two-thats-greater-or-equal-to-a-giv 
https://graphics.stanford.edu/~seander/bithacks.html#RoundUpPowerOf2
=> UTIL: Optimized ucc_round_up_power2 function

test/gtest/tl/mlx5/test_tl_mlx5_wqe.cc
Skip transpose test if the NIC is not CX7
https://redmine.mellanox.com/issues/4280707
=> TEST: check device version in transpose test

src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_coll.c, src/components/tl/ucp/tl_ucp_context.c, src/components/tl/ucp/tl_ucp_sendrecv.h
This change introduces two separate code paths for single-threaded and multi-threaded scenarios. During context creation, a specific set of functions and callbacks is selected based on the threading mode, avoiding branching in performance-critical (hot) paths. The single-threaded implementation avoids the use of atomics, which are unnecessary in that context and have been shown to impact performance on ARM systems (3–7% regression on small messages).
Recent performance analysis has revealed regressions in TL/UCP, particularly noticeable on ARM platforms. The atomics introduced in #932 addressed correctness in multi-threaded environments but introduced overhead even in single-threaded use cases. This PR mitigates that overhead for single-threaded configurations. A future update will …
=> TL/UCP: Split single and multithreaded send/receive

src/utils/ucc_compiler_def.h
Add support NVC in assume macro
Latest HPC SDK (nvcr.io/nvidia/nvhpc:25.1-devel-cuda12.6-ubuntu24.04) reports error 
`unknown attribute "assume" [unrecognized_attribute]`
=> UTIL: Support for NVC in ucc_assume macro

src/components/cl/hier/allgatherv/allgatherv.c
The mask for the node leader allgatherv and node broadcast are not set. My tests passed previously because I used OMPI v5.0.x to test, which actually will set the mask before calling into UCC. HPCX testing with OMPI v4.1.x (which doesn't set the mask) exposed this bug.
=> CL/HIER: Set agv mask

.github/workflows/asan-test.yaml, .github/workflows/clang-tidy-nvidia.yaml, .github/workflows/clang-tidy-rocm.yaml, .github/workflows/clang-tidy.yaml, .github/workflows/codestyle.yaml, .github/workflows/hpcsdk.yaml, .github/workflows/main.yaml
Updated:
- runner ubuntu versions to 22.04 
- clang to 17 both for compilation and tidy 
- nvhpc:25.1-devel-cuda12.6-ubuntu24.04 (latest requires more disk size)
- moved ASAN gtest out of clang tidy job
- hpcx-v2.22.1
- MLNX_OFED 24.10-2.1.8.0
According to https://github.com/actions/runner-images/issues/11101 ubuntu 20.04 deprecated and will be removed
=> CI: Update versions

src/components/base/ucc_base_iface.h, src/components/cl/hier/allgatherv/allgatherv.c
Adds flag for cl/hier to tell tl/shm gatherv nonroots they can check coll_args->dst.info_v to determine max msg size
=> CL/HIER: Add flag for nonroot info

src/components/tl/ucp/allreduce/allreduce.c, src/core/ucc_coll.c, src/utils/ucc_coll_utils.h
- Improved error logging in `ucc_collective_init` to include detailed collective arguments on failure.
- Updated `ucc_tl_ucp_allreduce_knomial_init` to ensure proper task cleanup on initialization failure.
=> CORE: enhance error log in collective init

src/components/tl/mlx5/tl_mlx5_context.c
Added checks for successful creation of the rcache and topology initialization.
All the resource initialization must happen in context create epilog. Otherwise if context create fails on one rank the other ranks will hang in context create epilog broadcast
=> TL/MLX5: ctx global status check

src/core/ucc_context.c
Improved error messages in `ucc_context_create_proc_info` to include status codes for address exchange, team creation, and epilogue failures, aiding in debugging and clarity during context creation.
While creating the binding for rust, faced issues that were challenging to identify and understand without proper logging.
=> CORE: enhance error logs in context creation

src/components/tl/mlx5/tl_mlx5.c, src/components/tl/mlx5/tl_mlx5.h, src/components/tl/mlx5/tl_mlx5_ib.c, test/gtest/tl/mlx5/test_tl_mlx5_qps.h
Add possibility to set IB QP Service Level for TL/MLX5 transport.
It's worth setting IB Service Level in multi-tenant cloud to provide guaranteed network bandwidth for some workloads while other can use a lower priority SL.
1. Introduce Service Level environment variable for TL/MLX5.
2. Provide configured SL to address handle attributes when modifying QP (or DCI/DCT) from INIT to RTR state.
=> TL/MLX5: Add configuration to set IB QP SL

src/components/cl/hier/allgatherv/allgatherv.c, src/components/cl/hier/allgatherv/allgatherv.h, src/components/cl/hier/cl_hier.h, src/components/cl/hier/cl_hier_team.c, src/components/topo/ucc_sbgp.c
This PR sorts the node leader subgroup rank mapping by team rank to avoid unnecessary unpacking in allgatherv. It also removes the `is_host_ordered` function in the allgatherv code, because it was previously checking whether or not the leaders were sorted by team rank. Now it always will be.
Previously the node leader subgroup was sorted by hostid, meaning that if a hostname happened to be lower than another hostname by the comparator that UCC uses, the node leader allgatherv step in my cl/hier allgatherv might actually be incorrect and need the extra unpack step to rearrange the buffer to have the right order.
Previous PR for reference here: https://github.com/openucx/ucc/pull/1103
Sorts the rank mapping and updates group_rank. In addition to removing `is_host_ordered`, I also updated …
=> TOPO: Node ldr ordered by team

src/components/base/ucc_base_iface.h, src/components/cl/basic/cl_basic.c, src/components/cl/basic/cl_basic_context.c, src/components/cl/doca_urom/cl_doca_urom.c, src/components/cl/doca_urom/cl_doca_urom_context.c, src/components/cl/hier/cl_hier.c, src/components/cl/hier/cl_hier_context.c, src/components/tl/cuda/tl_cuda.c, src/components/tl/cuda/tl_cuda_context.c, src/components/tl/mlx5/tl_mlx5.c, src/components/tl/mlx5/tl_mlx5_context.c, src/components/tl/nccl/tl_nccl.c, src/components/tl/nccl/tl_nccl_context.c, src/components/tl/rccl/tl_rccl.c, src/components/tl/rccl/tl_rccl_context.c, src/components/tl/self/tl_self.c, src/components/tl/self/tl_self_context.c, src/components/tl/sharp/tl_sharp.c, src/components/tl/sharp/tl_sharp_context.c, src/components/tl/ucp/alltoall/alltoall.c, src/components/tl/ucp/alltoall/alltoall_onesided.c, src/components/tl/ucp/alltoallv/alltoallv_onesided.c, src/components/tl/ucp/tl_ucp.c, src/components/tl/ucp/tl_ucp.h, src/components/tl/ucp/tl_ucp_context.c, src/components/tl/ucp/tl_ucp_sendrecv.h, src/core/ucc_context.c, src/core/ucc_context.h, src/ucc/api/ucc.h
Implementation of PR #1037 
NOTE: branch is branched from #1037 and will need to be rebased before merging
=> Add support for ucc_mem_map and ucc_mem_unmap

src/components/tl/mlx5/mcast/tl_mlx5_mcast_team.c, src/components/tl/mlx5/tl_mlx5_team.c
TL/MLX5: Recover from ipoib failure in mcast init and it avoids a segfault. It removes the unnecessary dereg function as registration has not happened before we fail here.
=> TL/MLX5: recover from ipoib issue in mcast init

tools/perf/ucc_pt_comm.cc
Add ucc_context_progress() calls to team creation and destruction loops to prevent hangs when collective operations need progress to complete.
This fixes a hang  in team creatation observed during the mcast-enabled ucc_perftest.
=> TOOLS/UCC_PERFTEST:  Adding missing progress calls

src/components/ec/rocm/ec_rocm_executor_interruptible.c
This PR includes stdbool.h in a rocm file.
In ROCM 7.0 Hip is removing some library inclusions. This will allow usage of `bool`
=> EC/ROCM: Include stdbool.h for new versions of ROCM

src/components/tl/cuda/tl_cuda.c, src/components/tl/cuda/tl_cuda.h, src/components/tl/cuda/tl_cuda_context.c, src/components/tl/cuda/tl_cuda_lib.c
- Store topology in lib and reuse for context creation.
- Fixed IPC cache leak. 
- Improved logging. 
- Added comments. 
The topology information includes:
- PCI device IDs
- NVLink connections between GPUs
- Device types (GPU or switch)
- Link widths and counts
- Topology discovery is expensive (requires NVML calls)
- The topology rarely changes during runtime
- Multiple contexts can share the same topology information
- When use_topo_cache is enabled (default):
- The topology information is stored in `lib->topo` (library level)
- If a cached topology exists `(lib->topo != NULL)`, it is reused for new contexts
- If no cached topology exists, a new one is created and stored in lib->topo
- When use_topo_cache is disabled:
- Each context gets its own topology instance stored in `self->topo` …
=> TL/CUDA: Topology Cache

src/coll_score/ucc_coll_score.c, src/components/tl/cuda/Makefile.am, src/components/tl/cuda/allreduce/allreduce.c, src/components/tl/cuda/allreduce/allreduce.h, src/components/tl/cuda/allreduce/allreduce_nvls.c, src/components/tl/cuda/kernels/Makefile.am, src/components/tl/cuda/kernels/allreduce_kernel.cu, src/components/tl/cuda/kernels/allreduce_kernel.h, src/components/tl/cuda/kernels/nvls.cuh, src/components/tl/cuda/kernels/reduce_scatter_kernel.cu, src/components/tl/cuda/kernels/reduce_scatter_kernel.h, src/components/tl/cuda/reduce_scatter/reduce_scatter.c, src/components/tl/cuda/reduce_scatter/reduce_scatter.h, src/components/tl/cuda/reduce_scatter/reduce_scatter_nvls.c, src/components/tl/cuda/tl_cuda.h, src/components/tl/cuda/tl_cuda_coll.c, src/components/tl/cuda/tl_cuda_coll.h, src/components/tl/cuda/tl_cuda_context.c, src/components/tl/cuda/tl_cuda_lib.c, src/components/tl/cuda/tl_cuda_team.c
UCC now supports the latest NVLink SHARP (NVLS) technology, unlocking advanced hardware features on modern GPUs (H100+). NVLS enables offloading collective operations to in-network hardware (NVSwitch), reducing SM usage and improving compute resource efficiency compared to traditional GPU-based implementations. 
Allreduce initial implementation with NVLS. (NVLS related initialization you could find in #1144 )
Command line:
```
mpirun --mca coll ^hcoll --mca coll_ucc_enable 0 -x LD_LIBRARY_PATH=/.autodirect/swgwork/ikryukov/ucc_build/install/lib:$LD_LIBRARY_PATH -x UCC_TLS=cuda,ucp -x UCC_LOG_LEVEL=info -x UCC_TL_CUDA_TUNE=allreduce:cuda:@0 -np 8 /.autodirect/swgwork/ikryukov/ucc_build/install/bin/ucc_perftest -c allreduce -F -m cuda -b 1k -e 16M -d float32 -o sum
```
=> TL/CUDA: NVLink SHARP (NVLS) Allreduce

src/ucc/api/ucc.h
Fixes a typo. Switches the word `team` to `context`
=> API: switch team to context

src/components/tl/cuda/allreduce/allreduce_nvls.c, src/components/tl/cuda/kernels/Makefile.am, src/components/tl/cuda/kernels/allreduce_kernel.cu, src/components/tl/cuda/kernels/allreduce_kernel.h, src/components/tl/cuda/kernels/nvls.cuh, src/components/tl/cuda/kernels/reduce_scatter_kernel.cu, src/components/tl/cuda/tl_cuda.h, src/components/tl/cuda/tl_cuda_cache.c, src/components/tl/cuda/tl_cuda_coll.h, src/components/tl/cuda/tl_cuda_nvls.c, src/components/tl/cuda/tl_cuda_nvls.h, src/components/tl/cuda/tl_cuda_team.c
Introduce a cross-GPU barrier implementation using NVLS symmetric memory, eliminating the need for host-side synchronization.
The existing barrier relies on a host-managed shared memory synchronization mechanism. While functional, this approach is:
- **Expensive in performance** - frequent host-device roundtrips add latency.
- **Not scalable across nodes** - shared memory is not available in multinode deployments, making the current design unsuitable for larger topologies.
This PR addresses both issues by moving barrier management fully into device-side execution.
- **Control space**: Reserve 1024 bytes in the NVLS symmetric buffer for barrier control segments.
- **Mechanism**:
- The barrier is represented by a single monotonically incremented **uint64_t** counter.
- Each participating …
=> TL/CUDA: NVLS barrier
